-- 003_n5_words_inari
-- N5 單字匯入：伏見稻荷大社（前 100 字，あ-お 開頭）
-- 資料源：stephenmk/yomitan-jlpt-vocab (CC-BY, Jonathan Waller / Tanos)
-- 中文翻譯：Claude（學生友善口語風格）
-- 注意：scripts/import-n5.py 可重複再跑來補 meiji 等其他神社的字

with new_words as (
  insert into words (lang_code, lemma, meaning_zh, meta, source) values
    ('ja', '会う',     '見面',     '{"kana":"あう","jlpt":"N5","jmdict_seq":1198180,"meaning_en":"to meet"}'::jsonb, 'jmdict'),
    ('ja', '青',       '藍色',     '{"kana":"あお","jlpt":"N5","jmdict_seq":1381380,"meaning_en":"blue"}'::jsonb, 'jmdict'),
    ('ja', '青い',     '藍色的',   '{"kana":"あおい","jlpt":"N5","jmdict_seq":1381390,"meaning_en":"blue"}'::jsonb, 'jmdict'),
    ('ja', '赤',       '紅色',     '{"kana":"あか","jlpt":"N5","jmdict_seq":2013900,"meaning_en":"red"}'::jsonb, 'jmdict'),
    ('ja', '赤い',     '紅色的',   '{"kana":"あかい","jlpt":"N5","jmdict_seq":1383240,"meaning_en":"red"}'::jsonb, 'jmdict'),
    ('ja', '明い',     '明亮的',   '{"kana":"あかるい","jlpt":"N5","jmdict_seq":1532350,"meaning_en":"bright"}'::jsonb, 'jmdict'),
    ('ja', '秋',       '秋天',     '{"kana":"あき","jlpt":"N5","jmdict_seq":1332650,"meaning_en":"autumn"}'::jsonb, 'jmdict'),
    ('ja', '開く',     '開（自動）', '{"kana":"あく","jlpt":"N5","jmdict_seq":1586270,"meaning_en":"to open, to become open"}'::jsonb, 'jmdict'),
    ('ja', '開ける',   '打開',     '{"kana":"あける","jlpt":"N5","jmdict_seq":1202450,"meaning_en":"to open"}'::jsonb, 'jmdict'),
    ('ja', '上げる',   '給',       '{"kana":"あげる","jlpt":"N5","jmdict_seq":1352320,"meaning_en":"to give"}'::jsonb, 'jmdict'),
    ('ja', '朝',       '早上',     '{"kana":"あさ","jlpt":"N5","jmdict_seq":1428280,"meaning_en":"morning"}'::jsonb, 'jmdict'),
    ('ja', '朝御飯',   '早餐',     '{"kana":"あさごはん","jlpt":"N5","jmdict_seq":1586330,"meaning_en":"breakfast"}'::jsonb, 'jmdict'),
    ('ja', 'あさって', '後天',     '{"kana":"あさって","jlpt":"N5","jmdict_seq":1584640,"meaning_en":"day after tomorrow"}'::jsonb, 'jmdict'),
    ('ja', '足',       '腳',       '{"kana":"あし","jlpt":"N5","jmdict_seq":1404630,"meaning_en":"foot, leg"}'::jsonb, 'jmdict'),
    ('ja', '明日',     '明天',     '{"kana":"あした","jlpt":"N5","jmdict_seq":1584660,"meaning_en":"tomorrow"}'::jsonb, 'jmdict'),
    ('ja', 'あそこ',   '那裡',     '{"kana":"あそこ","jlpt":"N5","jmdict_seq":1000320,"meaning_en":"over there"}'::jsonb, 'jmdict'),
    ('ja', '遊ぶ',     '玩',       '{"kana":"あそぶ","jlpt":"N5","jmdict_seq":1542160,"meaning_en":"to play, to make a visit"}'::jsonb, 'jmdict'),
    ('ja', '暖かい',   '溫暖',     '{"kana":"あたたかい","jlpt":"N5","jmdict_seq":1586420,"meaning_en":"warm"}'::jsonb, 'jmdict'),
    ('ja', '頭',       '頭',       '{"kana":"あたま","jlpt":"N5","jmdict_seq":1582310,"meaning_en":"head"}'::jsonb, 'jmdict'),
    ('ja', '新しい',   '新的',     '{"kana":"あたらしい","jlpt":"N5","jmdict_seq":1361490,"meaning_en":"new"}'::jsonb, 'jmdict'),
    ('ja', 'あちら',   '那邊（禮貌）', '{"kana":"あちら","jlpt":"N5","jmdict_seq":1483185,"meaning_en":"there"}'::jsonb, 'jmdict'),
    ('ja', '暑い',     '熱（天氣）', '{"kana":"あつい","jlpt":"N5","jmdict_seq":1343460,"meaning_en":"hot"}'::jsonb, 'jmdict'),
    ('ja', '熱い',     '燙（觸感）', '{"kana":"あつい","jlpt":"N5","jmdict_seq":1467720,"meaning_en":"hot to the touch"}'::jsonb, 'jmdict'),
    ('ja', '厚い',     '厚的',     '{"kana":"あつい","jlpt":"N5","jmdict_seq":1275320,"meaning_en":"kind, deep, thick"}'::jsonb, 'jmdict'),
    ('ja', 'あっち',   '那邊（口語）', '{"kana":"あっち","jlpt":"N5","jmdict_seq":1483185,"meaning_en":"over there"}'::jsonb, 'jmdict'),
    ('ja', '後',       '之後',     '{"kana":"あと","jlpt":"N5","jmdict_seq":1269320,"meaning_en":"afterwards"}'::jsonb, 'jmdict'),
    ('ja', '貴方',     '你',       '{"kana":"あなた","jlpt":"N5","jmdict_seq":1223615,"meaning_en":"you"}'::jsonb, 'jmdict'),
    ('ja', '兄',       '哥哥',     '{"kana":"あに","jlpt":"N5","jmdict_seq":1249900,"meaning_en":"(humble) older brother"}'::jsonb, 'jmdict'),
    ('ja', '姉',       '姊姊',     '{"kana":"あね","jlpt":"N5","jmdict_seq":1307630,"meaning_en":"(humble) older sister"}'::jsonb, 'jmdict'),
    ('ja', 'あの',     '那個（語助）', '{"kana":"あの","jlpt":"N5","jmdict_seq":1000430,"meaning_en":"um..."}'::jsonb, 'jmdict'),
    ('ja', 'アパート', '公寓',     '{"kana":"アパート","jlpt":"N5","jmdict_seq":1017760,"meaning_en":"apartment"}'::jsonb, 'jmdict'),
    ('ja', 'あびる',   '沖澡',     '{"kana":"あびる","jlpt":"N5","jmdict_seq":1547450,"meaning_en":"to bathe, to shower"}'::jsonb, 'jmdict'),
    ('ja', '危ない',   '危險',     '{"kana":"あぶない","jlpt":"N5","jmdict_seq":1218380,"meaning_en":"dangerous"}'::jsonb, 'jmdict'),
    ('ja', '甘い',     '甜',       '{"kana":"あまい","jlpt":"N5","jmdict_seq":1213400,"meaning_en":"sweet"}'::jsonb, 'jmdict'),
    ('ja', 'あまり',   '不太',     '{"kana":"あまり","jlpt":"N5","jmdict_seq":1584930,"meaning_en":"not very"}'::jsonb, 'jmdict'),
    ('ja', '雨',       '雨',       '{"kana":"あめ","jlpt":"N5","jmdict_seq":1171900,"meaning_en":"rain"}'::jsonb, 'jmdict'),
    ('ja', '飴',       '糖果',     '{"kana":"あめ","jlpt":"N5","jmdict_seq":1153520,"meaning_en":"candy"}'::jsonb, 'jmdict'),
    ('ja', '洗う',     '洗',       '{"kana":"あらう","jlpt":"N5","jmdict_seq":1390930,"meaning_en":"to wash"}'::jsonb, 'jmdict'),
    ('ja', '有る',     '有（物品）', '{"kana":"ある","jlpt":"N5","jmdict_seq":1296400,"meaning_en":"to be, to have"}'::jsonb, 'jmdict'),
    ('ja', '歩く',     '走路',     '{"kana":"あるく","jlpt":"N5","jmdict_seq":1514320,"meaning_en":"to walk"}'::jsonb, 'jmdict'),
    ('ja', 'あれ',     '那個',     '{"kana":"あれ","jlpt":"N5","jmdict_seq":2847612,"meaning_en":"that"}'::jsonb, 'jmdict'),
    ('ja', 'いい',     '好',       '{"kana":"いい","jlpt":"N5","jmdict_seq":2820690,"meaning_en":"good"}'::jsonb, 'jmdict'),
    ('ja', '良い',     '好（書面）', '{"kana":"よい","jlpt":"N5","jmdict_seq":1605820,"meaning_en":"good"}'::jsonb, 'jmdict'),
    ('ja', 'いいえ',   '不是',     '{"kana":"いいえ","jlpt":"N5","jmdict_seq":1583250,"meaning_en":"no"}'::jsonb, 'jmdict'),
    ('ja', '言う',     '說',       '{"kana":"いう","jlpt":"N5","jmdict_seq":1587040,"meaning_en":"to say"}'::jsonb, 'jmdict'),
    ('ja', '家',       '家',       '{"kana":"いえ","jlpt":"N5","jmdict_seq":1191730,"meaning_en":"house"}'::jsonb, 'jmdict'),
    ('ja', 'いかが',   '如何',     '{"kana":"いかが","jlpt":"N5","jmdict_seq":2845606,"meaning_en":"how"}'::jsonb, 'jmdict'),
    ('ja', '行く',     '去',       '{"kana":"いく","jlpt":"N5","jmdict_seq":1578850,"meaning_en":"to go"}'::jsonb, 'jmdict'),
    ('ja', 'いくつ',   '幾個',     '{"kana":"いくつ","jlpt":"N5","jmdict_seq":1219960,"meaning_en":"how many?, how old?"}'::jsonb, 'jmdict'),
    ('ja', 'いくら',   '多少錢',   '{"kana":"いくら","jlpt":"N5","jmdict_seq":1219980,"meaning_en":"how much?"}'::jsonb, 'jmdict'),
    ('ja', '池',       '池塘',     '{"kana":"いけ","jlpt":"N5","jmdict_seq":1421700,"meaning_en":"pond"}'::jsonb, 'jmdict'),
    ('ja', '医者',     '醫生',     '{"kana":"いしゃ","jlpt":"N5","jmdict_seq":1159980,"meaning_en":"medical doctor"}'::jsonb, 'jmdict'),
    ('ja', 'いす',     '椅子',     '{"kana":"いす","jlpt":"N5","jmdict_seq":1157070,"meaning_en":"chair"}'::jsonb, 'jmdict'),
    ('ja', '忙しい',   '忙',       '{"kana":"いそがしい","jlpt":"N5","jmdict_seq":1519290,"meaning_en":"busy, irritated"}'::jsonb, 'jmdict'),
    ('ja', '痛い',     '痛',       '{"kana":"いたい","jlpt":"N5","jmdict_seq":1432680,"meaning_en":"painful"}'::jsonb, 'jmdict'),
    ('ja', '一',       '一',       '{"kana":"いち","jlpt":"N5","jmdict_seq":1160790,"meaning_en":"one"}'::jsonb, 'jmdict'),
    ('ja', '一日',     '一號',     '{"kana":"いちにち","jlpt":"N5","jmdict_seq":1576260,"meaning_en":"first of the month"}'::jsonb, 'jmdict'),
    ('ja', 'いちばん', '最',       '{"kana":"いちばん","jlpt":"N5","jmdict_seq":1165970,"meaning_en":"best, first"}'::jsonb, 'jmdict'),
    ('ja', '何時',     '何時',     '{"kana":"いつ","jlpt":"N5","jmdict_seq":1188760,"meaning_en":"when"}'::jsonb, 'jmdict'),
    ('ja', '五日',     '五號',     '{"kana":"いつか","jlpt":"N5","jmdict_seq":1268570,"meaning_en":"five days, fifth day"}'::jsonb, 'jmdict'),
    ('ja', '一緒',     '一起',     '{"kana":"いっしょ","jlpt":"N5","jmdict_seq":1163400,"meaning_en":"together"}'::jsonb, 'jmdict'),
    ('ja', '五つ',     '五個',     '{"kana":"いつつ","jlpt":"N5","jmdict_seq":1268070,"meaning_en":"five"}'::jsonb, 'jmdict'),
    ('ja', 'いつも',   '總是',     '{"kana":"いつも","jlpt":"N5","jmdict_seq":1188890,"meaning_en":"always"}'::jsonb, 'jmdict'),
    ('ja', '犬',       '狗',       '{"kana":"いぬ","jlpt":"N5","jmdict_seq":1258330,"meaning_en":"dog"}'::jsonb, 'jmdict'),
    ('ja', '今',       '現在',     '{"kana":"いま","jlpt":"N5","jmdict_seq":1288850,"meaning_en":"now"}'::jsonb, 'jmdict'),
    ('ja', '意味',     '意思',     '{"kana":"いみ","jlpt":"N5","jmdict_seq":1156800,"meaning_en":"meaning"}'::jsonb, 'jmdict'),
    ('ja', '妹',       '妹妹',     '{"kana":"いもうと","jlpt":"N5","jmdict_seq":1524590,"meaning_en":"(humble) younger sister"}'::jsonb, 'jmdict'),
    ('ja', '嫌',       '討厭',     '{"kana":"いや","jlpt":"N5","jmdict_seq":1587610,"meaning_en":"unpleasant"}'::jsonb, 'jmdict'),
    ('ja', '入口',     '入口',     '{"kana":"いりぐち","jlpt":"N5","jmdict_seq":1582820,"meaning_en":"entrance"}'::jsonb, 'jmdict'),
    ('ja', '居る',     '在（生物）', '{"kana":"いる","jlpt":"N5","jmdict_seq":1577980,"meaning_en":"to be, to have (used for people and animals)"}'::jsonb, 'jmdict'),
    ('ja', '要る',     '需要',     '{"kana":"いる","jlpt":"N5","jmdict_seq":1546640,"meaning_en":"to need"}'::jsonb, 'jmdict'),
    ('ja', '入れる',   '放入',     '{"kana":"いれる","jlpt":"N5","jmdict_seq":1465610,"meaning_en":"to put in"}'::jsonb, 'jmdict'),
    ('ja', '色',       '顏色',     '{"kana":"いろ","jlpt":"N5","jmdict_seq":1357600,"meaning_en":"colour"}'::jsonb, 'jmdict'),
    ('ja', 'いろいろ', '各種各樣', '{"kana":"いろいろ","jlpt":"N5","jmdict_seq":1587850,"meaning_en":"various"}'::jsonb, 'jmdict'),
    ('ja', '上',       '上面',     '{"kana":"うえ","jlpt":"N5","jmdict_seq":1352130,"meaning_en":"on top of"}'::jsonb, 'jmdict'),
    ('ja', '後ろ',     '後面',     '{"kana":"うしろ","jlpt":"N5","jmdict_seq":1269410,"meaning_en":"behind"}'::jsonb, 'jmdict'),
    ('ja', '薄い',     '薄',       '{"kana":"うすい","jlpt":"N5","jmdict_seq":1475480,"meaning_en":"thin, weak"}'::jsonb, 'jmdict'),
    ('ja', '歌',       '歌',       '{"kana":"うた","jlpt":"N5","jmdict_seq":1193180,"meaning_en":"song"}'::jsonb, 'jmdict'),
    ('ja', '歌う',     '唱歌',     '{"kana":"うたう","jlpt":"N5","jmdict_seq":1588120,"meaning_en":"to sing"}'::jsonb, 'jmdict'),
    ('ja', '生まれる', '出生',     '{"kana":"うまれる","jlpt":"N5","jmdict_seq":1378690,"meaning_en":"to be born"}'::jsonb, 'jmdict'),
    ('ja', '海',       '海',       '{"kana":"うみ","jlpt":"N5","jmdict_seq":1201190,"meaning_en":"sea"}'::jsonb, 'jmdict'),
    ('ja', '売る',     '賣',       '{"kana":"うる","jlpt":"N5","jmdict_seq":1473950,"meaning_en":"to sell"}'::jsonb, 'jmdict'),
    ('ja', '煩い',     '吵',       '{"kana":"うるさい","jlpt":"N5","jmdict_seq":1481920,"meaning_en":"noisy, annoying"}'::jsonb, 'jmdict'),
    ('ja', '上着',     '外套',     '{"kana":"うわぎ","jlpt":"N5","jmdict_seq":1580340,"meaning_en":"jacket"}'::jsonb, 'jmdict'),
    ('ja', '絵',       '畫',       '{"kana":"え","jlpt":"N5","jmdict_seq":1202270,"meaning_en":"picture"}'::jsonb, 'jmdict'),
    ('ja', '映画',     '電影',     '{"kana":"えいが","jlpt":"N5","jmdict_seq":1173720,"meaning_en":"movie"}'::jsonb, 'jmdict'),
    ('ja', '映画館',   '電影院',   '{"kana":"えいがかん","jlpt":"N5","jmdict_seq":1173750,"meaning_en":"cinema"}'::jsonb, 'jmdict'),
    ('ja', '英語',     '英文',     '{"kana":"えいご","jlpt":"N5","jmdict_seq":1174420,"meaning_en":"English language"}'::jsonb, 'jmdict'),
    ('ja', 'ええ',     '嗯（肯定）', '{"kana":"ええ","jlpt":"N5","jmdict_seq":1001140,"meaning_en":"yes"}'::jsonb, 'jmdict'),
    ('ja', '駅',       '車站',     '{"kana":"えき","jlpt":"N5","jmdict_seq":1175140,"meaning_en":"station"}'::jsonb, 'jmdict'),
    ('ja', 'エレベーター', '電梯', '{"kana":"エレベーター","jlpt":"N5","jmdict_seq":1030630,"meaning_en":"elevator"}'::jsonb, 'jmdict'),
    ('ja', '鉛筆',     '鉛筆',     '{"kana":"えんぴつ","jlpt":"N5","jmdict_seq":1178590,"meaning_en":"pencil"}'::jsonb, 'jmdict'),
    ('ja', 'おいしい', '好吃',     '{"kana":"おいしい","jlpt":"N5","jmdict_seq":1486650,"meaning_en":"delicious"}'::jsonb, 'jmdict'),
    ('ja', '多い',     '多',       '{"kana":"おおい","jlpt":"N5","jmdict_seq":1407460,"meaning_en":"many"}'::jsonb, 'jmdict'),
    ('ja', '大きい',   '大',       '{"kana":"おおきい","jlpt":"N5","jmdict_seq":1588880,"meaning_en":"big"}'::jsonb, 'jmdict'),
    ('ja', '大きな',   '大的',     '{"kana":"おおきな","jlpt":"N5","jmdict_seq":1412890,"meaning_en":"big"}'::jsonb, 'jmdict'),
    ('ja', '大勢',     '很多人',   '{"kana":"おおぜい","jlpt":"N5","jmdict_seq":1414220,"meaning_en":"great number of people"}'::jsonb, 'jmdict'),
    ('ja', 'お母さん', '媽媽',     '{"kana":"おかあさん","jlpt":"N5","jmdict_seq":1002650,"meaning_en":"(honorable) mother"}'::jsonb, 'jmdict'),
    ('ja', 'お菓子',   '點心',     '{"kana":"おかし","jlpt":"N5","jmdict_seq":1001710,"meaning_en":"sweets, candy"}'::jsonb, 'jmdict'),
    ('ja', 'お金',     '錢',       '{"kana":"おかね","jlpt":"N5","jmdict_seq":1001820,"meaning_en":"money"}'::jsonb, 'jmdict')
  returning id, lemma
)
insert into shrine_words (shrine_id, word_id, position)
select
  (select id from shrines where slug = 'inari'),
  nw.id,
  row_number() over (order by nw.lemma)
from new_words nw;
