-- 004_n5_words_inari_part2
-- N5 單字補匯：伏見稻荷大社 part 2（CSV 行 102-343，共 242 字）
-- 資料源：stephenmk/yomitan-jlpt-vocab (CC-BY, Jonathan Waller / Tanos)
-- 中文翻譯：Claude（學生友善口語風格）

with new_words as (
  insert into words (lang_code, lemma, meaning_zh, meta, source) values
    ('ja', '起きる', '起床', '{"kana": "おきる", "jlpt": "N5", "jmdict_seq": 1223640, "meaning_en": "to get up"}'::jsonb, 'jmdict'),
    ('ja', '置く', '放', '{"kana": "おく", "jlpt": "N5", "jmdict_seq": 1421850, "meaning_en": "to put"}'::jsonb, 'jmdict'),
    ('ja', '奥さん', '太太', '{"kana": "おくさん", "jlpt": "N5", "jmdict_seq": 1179330, "meaning_en": "(honorable) wife"}'::jsonb, 'jmdict'),
    ('ja', 'お酒', '酒', '{"kana": "おさけ", "jlpt": "N5", "jmdict_seq": 1329015, "meaning_en": "alcohol, rice wine"}'::jsonb, 'jmdict'),
    ('ja', 'お皿', '盤子', '{"kana": "おさら", "jlpt": "N5", "jmdict_seq": 1299685, "meaning_en": "plate, dish"}'::jsonb, 'jmdict'),
    ('ja', 'おじいさん', '爺爺', '{"kana": "おじいさん", "jlpt": "N5", "jmdict_seq": 1002320, "meaning_en": "grandfather, male senior citizen"}'::jsonb, 'jmdict'),
    ('ja', '教える', '教', '{"kana": "おしえる", "jlpt": "N5", "jmdict_seq": 1236900, "meaning_en": "to teach, to tell"}'::jsonb, 'jmdict'),
    ('ja', 'おじさん', '叔叔', '{"kana": "おじさん", "jlpt": "N5", "jmdict_seq": 2261490, "meaning_en": "uncle, middle aged gentleman"}'::jsonb, 'jmdict'),
    ('ja', '押す', '推', '{"kana": "おす", "jlpt": "N5", "jmdict_seq": 1180470, "meaning_en": "to push, to stamp something"}'::jsonb, 'jmdict'),
    ('ja', '遅い', '慢', '{"kana": "おそい", "jlpt": "N5", "jmdict_seq": 1421970, "meaning_en": "late, slow"}'::jsonb, 'jmdict'),
    ('ja', 'お茶', '茶', '{"kana": "おちゃ", "jlpt": "N5", "jmdict_seq": 1002430, "meaning_en": "green tea"}'::jsonb, 'jmdict'),
    ('ja', 'お手洗い', '洗手間', '{"kana": "おてあらい", "jlpt": "N5", "jmdict_seq": 1002100, "meaning_en": "bathroom"}'::jsonb, 'jmdict'),
    ('ja', 'お父さん', '爸爸', '{"kana": "おとうさん", "jlpt": "N5", "jmdict_seq": 1002590, "meaning_en": "(honorable) father"}'::jsonb, 'jmdict'),
    ('ja', '弟', '弟弟', '{"kana": "おとうと", "jlpt": "N5", "jmdict_seq": 1581930, "meaning_en": "younger brother"}'::jsonb, 'jmdict'),
    ('ja', '男', '男生', '{"kana": "おとこ", "jlpt": "N5", "jmdict_seq": 1419990, "meaning_en": "Man"}'::jsonb, 'jmdict'),
    ('ja', '男の子', '男孩', '{"kana": "おとこのこ", "jlpt": "N5", "jmdict_seq": 1420010, "meaning_en": "Boy"}'::jsonb, 'jmdict'),
    ('ja', '一昨日', '前天', '{"kana": "おととい", "jlpt": "N5", "jmdict_seq": 1576050, "meaning_en": "day before yesterday"}'::jsonb, 'jmdict'),
    ('ja', '一昨年', '前年', '{"kana": "おととし", "jlpt": "N5", "jmdict_seq": 1576060, "meaning_en": "year before last"}'::jsonb, 'jmdict'),
    ('ja', '大人', '大人', '{"kana": "おとな", "jlpt": "N5", "jmdict_seq": 1414170, "meaning_en": "Adult"}'::jsonb, 'jmdict'),
    ('ja', 'おなか', '肚子', '{"kana": "おなか", "jlpt": "N5", "jmdict_seq": 1002610, "meaning_en": "stomach"}'::jsonb, 'jmdict'),
    ('ja', '同じ', '一樣', '{"kana": "おなじ", "jlpt": "N5", "jmdict_seq": 1451750, "meaning_en": "same"}'::jsonb, 'jmdict'),
    ('ja', 'お兄さん', '哥哥', '{"kana": "おにいさん", "jlpt": "N5", "jmdict_seq": 1001830, "meaning_en": "(honorable) older brother"}'::jsonb, 'jmdict'),
    ('ja', 'お姉さん', '姊姊', '{"kana": "おねえさん", "jlpt": "N5", "jmdict_seq": 1001990, "meaning_en": "(honorable) older sister"}'::jsonb, 'jmdict'),
    ('ja', 'おばあさん', '奶奶', '{"kana": "おばあさん", "jlpt": "N5", "jmdict_seq": 1002330, "meaning_en": "grandmother, female senior-citizen"}'::jsonb, 'jmdict'),
    ('ja', '伯母さん', '阿姨', '{"kana": "おばさん", "jlpt": "N5", "jmdict_seq": 2261500, "meaning_en": "Aunt"}'::jsonb, 'jmdict'),
    ('ja', 'お風呂', '澡', '{"kana": "おふろ", "jlpt": "N5", "jmdict_seq": 2220600, "meaning_en": "Bath"}'::jsonb, 'jmdict'),
    ('ja', 'お弁当', '便當', '{"kana": "おべんとう", "jlpt": "N5", "jmdict_seq": 1513065, "meaning_en": "boxed lunch"}'::jsonb, 'jmdict'),
    ('ja', '覚える', '記住', '{"kana": "おぼえる", "jlpt": "N5", "jmdict_seq": 1206050, "meaning_en": "to remember"}'::jsonb, 'jmdict'),
    ('ja', 'おまわりさん', '警察先生', '{"kana": "おまわりさん", "jlpt": "N5", "jmdict_seq": 1002120, "meaning_en": "friendly term for policeman"}'::jsonb, 'jmdict'),
    ('ja', '重い', '重', '{"kana": "おもい", "jlpt": "N5", "jmdict_seq": 1335750, "meaning_en": "Heavy"}'::jsonb, 'jmdict'),
    ('ja', 'おもしろい', '有趣', '{"kana": "おもしろい", "jlpt": "N5", "jmdict_seq": 1533580, "meaning_en": "Interesting"}'::jsonb, 'jmdict'),
    ('ja', '泳ぐ', '游泳', '{"kana": "およぐ", "jlpt": "N5", "jmdict_seq": 1174340, "meaning_en": "to swim"}'::jsonb, 'jmdict'),
    ('ja', '降りる', '下車', '{"kana": "おりる", "jlpt": "N5", "jmdict_seq": 1589500, "meaning_en": "to get off, to descend"}'::jsonb, 'jmdict'),
    ('ja', '終る', '結束', '{"kana": "おわる", "jlpt": "N5", "jmdict_seq": 1589600, "meaning_en": "to finish"}'::jsonb, 'jmdict'),
    ('ja', '音楽', '音樂', '{"kana": "おんがく", "jlpt": "N5", "jmdict_seq": 1183720, "meaning_en": "Music"}'::jsonb, 'jmdict'),
    ('ja', '女', '女生', '{"kana": "おんな", "jlpt": "N5", "jmdict_seq": 1344930, "meaning_en": "Woman"}'::jsonb, 'jmdict'),
    ('ja', '女の子', '女孩', '{"kana": "おんなのこ", "jlpt": "N5", "jmdict_seq": 1344970, "meaning_en": "Girl"}'::jsonb, 'jmdict'),
    ('ja', '外国', '外國', '{"kana": "がいこく", "jlpt": "N5", "jmdict_seq": 1203620, "meaning_en": "foreign country"}'::jsonb, 'jmdict'),
    ('ja', '外国人', '外國人', '{"kana": "がいこくじん", "jlpt": "N5", "jmdict_seq": 1203650, "meaning_en": "Foreigner"}'::jsonb, 'jmdict'),
    ('ja', '会社', '公司', '{"kana": "かいしゃ", "jlpt": "N5", "jmdict_seq": 1198550, "meaning_en": "Company"}'::jsonb, 'jmdict'),
    ('ja', '階段', '樓梯', '{"kana": "かいだん", "jlpt": "N5", "jmdict_seq": 1203090, "meaning_en": "Stairs"}'::jsonb, 'jmdict'),
    ('ja', '買い物', '購物', '{"kana": "かいもの", "jlpt": "N5", "jmdict_seq": 1589730, "meaning_en": "Shopping"}'::jsonb, 'jmdict'),
    ('ja', '買う', '買', '{"kana": "かう", "jlpt": "N5", "jmdict_seq": 1473740, "meaning_en": "to buy"}'::jsonb, 'jmdict'),
    ('ja', '返す', '歸還', '{"kana": "かえす", "jlpt": "N5", "jmdict_seq": 1512130, "meaning_en": "to return something"}'::jsonb, 'jmdict'),
    ('ja', '帰る', '回家', '{"kana": "かえる", "jlpt": "N5", "jmdict_seq": 1221270, "meaning_en": "to go back"}'::jsonb, 'jmdict'),
    ('ja', '掛かる', '花費（時間/錢）', '{"kana": "かかる", "jlpt": "N5", "jmdict_seq": 1207590, "meaning_en": "to take time or money"}'::jsonb, 'jmdict'),
    ('ja', '鍵', '鑰匙', '{"kana": "かぎ", "jlpt": "N5", "jmdict_seq": 1260490, "meaning_en": "Key"}'::jsonb, 'jmdict'),
    ('ja', '書く', '寫', '{"kana": "かく", "jlpt": "N5", "jmdict_seq": 1343950, "meaning_en": "to write"}'::jsonb, 'jmdict'),
    ('ja', '学生', '學生', '{"kana": "がくせい", "jlpt": "N5", "jmdict_seq": 1206900, "meaning_en": "Student"}'::jsonb, 'jmdict'),
    ('ja', '掛ける', '打電話', '{"kana": "かける", "jlpt": "N5", "jmdict_seq": 1207610, "meaning_en": "to call by phone"}'::jsonb, 'jmdict'),
    ('ja', '傘', '雨傘', '{"kana": "かさ", "jlpt": "N5", "jmdict_seq": 1301940, "meaning_en": "Umbrella"}'::jsonb, 'jmdict'),
    ('ja', '貸す', '借出', '{"kana": "かす", "jlpt": "N5", "jmdict_seq": 1411160, "meaning_en": "to lend"}'::jsonb, 'jmdict'),
    ('ja', '風', '風', '{"kana": "かぜ", "jlpt": "N5", "jmdict_seq": 1499720, "meaning_en": "Wind"}'::jsonb, 'jmdict'),
    ('ja', '風邪', '感冒', '{"kana": "かぜ", "jlpt": "N5", "jmdict_seq": 1583720, "meaning_en": "a cold"}'::jsonb, 'jmdict'),
    ('ja', '家族', '家人', '{"kana": "かぞく", "jlpt": "N5", "jmdict_seq": 1192150, "meaning_en": "Family"}'::jsonb, 'jmdict'),
    ('ja', '方', '方式（人/作法）', '{"kana": "かた", "jlpt": "N5", "jmdict_seq": 1516925, "meaning_en": "person, way of doing"}'::jsonb, 'jmdict'),
    ('ja', '学校', '學校', '{"kana": "がっこう", "jlpt": "N5", "jmdict_seq": 1206730, "meaning_en": "School"}'::jsonb, 'jmdict'),
    ('ja', 'カップ', '杯子', '{"kana": "カップ", "jlpt": "N5", "jmdict_seq": 1037670, "meaning_en": "Cup"}'::jsonb, 'jmdict'),
    ('ja', '家庭', '家庭', '{"kana": "かてい", "jlpt": "N5", "jmdict_seq": 1192280, "meaning_en": "Household"}'::jsonb, 'jmdict'),
    ('ja', '角', '轉角', '{"kana": "かど", "jlpt": "N5", "jmdict_seq": 1206110, "meaning_en": "a corner"}'::jsonb, 'jmdict'),
    ('ja', '鞄', '包包', '{"kana": "かばん", "jlpt": "N5", "jmdict_seq": 1208910, "meaning_en": "bag, basket"}'::jsonb, 'jmdict'),
    ('ja', '花瓶', '花瓶', '{"kana": "かびん", "jlpt": "N5", "jmdict_seq": 1194870, "meaning_en": "a vase"}'::jsonb, 'jmdict'),
    ('ja', '紙', '紙', '{"kana": "かみ", "jlpt": "N5", "jmdict_seq": 1311530, "meaning_en": "paper"}'::jsonb, 'jmdict'),
    ('ja', 'カメラ', '相機', '{"kana": "カメラ", "jlpt": "N5", "jmdict_seq": 1038350, "meaning_en": "camera"}'::jsonb, 'jmdict'),
    ('ja', '火曜日', '星期二', '{"kana": "かようび", "jlpt": "N5", "jmdict_seq": 1194290, "meaning_en": "Tuesday"}'::jsonb, 'jmdict'),
    ('ja', '辛い', '辣', '{"kana": "からい", "jlpt": "N5", "jmdict_seq": 1365850, "meaning_en": "Spicy"}'::jsonb, 'jmdict'),
    ('ja', '体', '身體', '{"kana": "からだ", "jlpt": "N5", "jmdict_seq": 1409140, "meaning_en": "Body"}'::jsonb, 'jmdict'),
    ('ja', '借りる', '借入', '{"kana": "かりる", "jlpt": "N5", "jmdict_seq": 1323560, "meaning_en": "to borrow"}'::jsonb, 'jmdict'),
    ('ja', '軽い', '輕', '{"kana": "かるい", "jlpt": "N5", "jmdict_seq": 1252560, "meaning_en": "Light"}'::jsonb, 'jmdict'),
    ('ja', 'カレー', '咖哩', '{"kana": "カレー", "jlpt": "N5", "jmdict_seq": 1039140, "meaning_en": "Curry"}'::jsonb, 'jmdict'),
    ('ja', 'カレンダー', '月曆', '{"kana": "カレンダー", "jlpt": "N5", "jmdict_seq": 1039220, "meaning_en": "calendar"}'::jsonb, 'jmdict'),
    ('ja', '川', '河（小）', '{"kana": "かわ", "jlpt": "N5", "jmdict_seq": 1390020, "meaning_en": "River"}'::jsonb, 'jmdict'),
    ('ja', '河', '河（大）', '{"kana": "かわ", "jlpt": "N5", "jmdict_seq": 1390020, "meaning_en": "River"}'::jsonb, 'jmdict'),
    ('ja', 'かわいい', '可愛', '{"kana": "かわいい", "jlpt": "N5", "jmdict_seq": 1577200, "meaning_en": "Cute"}'::jsonb, 'jmdict'),
    ('ja', '漢字', '漢字', '{"kana": "かんじ", "jlpt": "N5", "jmdict_seq": 1213170, "meaning_en": "Chinese character"}'::jsonb, 'jmdict'),
    ('ja', '木', '樹', '{"kana": "き", "jlpt": "N5", "jmdict_seq": 1534520, "meaning_en": "tree, wood"}'::jsonb, 'jmdict'),
    ('ja', '黄色', '黃色', '{"kana": "きいろ", "jlpt": "N5", "jmdict_seq": 1576760, "meaning_en": "yellow"}'::jsonb, 'jmdict'),
    ('ja', '黄色い', '黃色的', '{"kana": "きいろい", "jlpt": "N5", "jmdict_seq": 1182030, "meaning_en": "yellow"}'::jsonb, 'jmdict'),
    ('ja', '消える', '消失', '{"kana": "きえる", "jlpt": "N5", "jmdict_seq": 1350040, "meaning_en": "to disappear"}'::jsonb, 'jmdict'),
    ('ja', '聞く', '聽/問', '{"kana": "きく", "jlpt": "N5", "jmdict_seq": 1591110, "meaning_en": "to hear, to listen to, to ask"}'::jsonb, 'jmdict'),
    ('ja', '北', '北邊', '{"kana": "きた", "jlpt": "N5", "jmdict_seq": 1520670, "meaning_en": "North"}'::jsonb, 'jmdict'),
    ('ja', 'ギター', '吉他', '{"kana": "ギター", "jlpt": "N5", "jmdict_seq": 1042820, "meaning_en": "Guitar"}'::jsonb, 'jmdict'),
    ('ja', '汚い', '髒', '{"kana": "きたない", "jlpt": "N5", "jmdict_seq": 1178940, "meaning_en": "Dirty"}'::jsonb, 'jmdict'),
    ('ja', '喫茶店', '咖啡廳', '{"kana": "きっさてん", "jlpt": "N5", "jmdict_seq": 1226440, "meaning_en": "coffee lounge"}'::jsonb, 'jmdict'),
    ('ja', '切手', '郵票', '{"kana": "きって", "jlpt": "N5", "jmdict_seq": 1385070, "meaning_en": "postage stamp"}'::jsonb, 'jmdict'),
    ('ja', '切符', '票', '{"kana": "きっぷ", "jlpt": "N5", "jmdict_seq": 1385170, "meaning_en": "Ticket"}'::jsonb, 'jmdict'),
    ('ja', '昨日', '昨天', '{"kana": "きのう", "jlpt": "N5", "jmdict_seq": 1579260, "meaning_en": "Yesterday"}'::jsonb, 'jmdict'),
    ('ja', '九', '九（きゅう）', '{"kana": "きゅう", "jlpt": "N5", "jmdict_seq": 1578150, "meaning_en": "Nine"}'::jsonb, 'jmdict'),
    ('ja', '九', '九（く）', '{"kana": "く", "jlpt": "N5", "jmdict_seq": 1578150, "meaning_en": "Nine"}'::jsonb, 'jmdict'),
    ('ja', '牛肉', '牛肉', '{"kana": "ぎゅうにく", "jlpt": "N5", "jmdict_seq": 1231580, "meaning_en": "Beef"}'::jsonb, 'jmdict'),
    ('ja', '牛乳', '牛奶', '{"kana": "ぎゅうにゅう", "jlpt": "N5", "jmdict_seq": 1231590, "meaning_en": "Milk"}'::jsonb, 'jmdict'),
    ('ja', '今日', '今天', '{"kana": "きょう", "jlpt": "N5", "jmdict_seq": 1579110, "meaning_en": "Today"}'::jsonb, 'jmdict'),
    ('ja', '教室', '教室', '{"kana": "きょうしつ", "jlpt": "N5", "jmdict_seq": 1237150, "meaning_en": "Classroom"}'::jsonb, 'jmdict'),
    ('ja', '兄弟', '兄弟姊妹', '{"kana": "きょうだい", "jlpt": "N5", "jmdict_seq": 1249960, "meaning_en": "(humble) siblings"}'::jsonb, 'jmdict'),
    ('ja', '去年', '去年', '{"kana": "きょねん", "jlpt": "N5", "jmdict_seq": 1231690, "meaning_en": "last year"}'::jsonb, 'jmdict'),
    ('ja', '嫌い', '討厭', '{"kana": "きらい", "jlpt": "N5", "jmdict_seq": 1257240, "meaning_en": "Hate"}'::jsonb, 'jmdict'),
    ('ja', '切る', '切', '{"kana": "きる", "jlpt": "N5", "jmdict_seq": 1384830, "meaning_en": "to cut"}'::jsonb, 'jmdict'),
    ('ja', '着る', '穿（上身）', '{"kana": "きる", "jlpt": "N5", "jmdict_seq": 1423000, "meaning_en": "to put on from the shoulders down"}'::jsonb, 'jmdict'),
    ('ja', 'きれい', '漂亮/乾淨', '{"kana": "きれい", "jlpt": "N5", "jmdict_seq": 1591900, "meaning_en": "pretty, clean"}'::jsonb, 'jmdict'),
    ('ja', 'キロ', '公斤（簡稱）', '{"kana": "キロ", "jlpt": "N5", "jmdict_seq": 1042610, "meaning_en": "Kilogram"}'::jsonb, 'jmdict'),
    ('ja', 'キログラム', '公斤', '{"kana": "キログラム", "jlpt": "N5", "jmdict_seq": 1042620, "meaning_en": "Kilogram"}'::jsonb, 'jmdict'),
    ('ja', 'キロメートル', '公里', '{"kana": "キロメートル", "jlpt": "N5", "jmdict_seq": 1042650, "meaning_en": "Kilometer"}'::jsonb, 'jmdict'),
    ('ja', '銀行', '銀行', '{"kana": "ぎんこう", "jlpt": "N5", "jmdict_seq": 1243490, "meaning_en": "Bank"}'::jsonb, 'jmdict'),
    ('ja', '金曜日', '星期五', '{"kana": "きんようび", "jlpt": "N5", "jmdict_seq": 1243320, "meaning_en": "Friday"}'::jsonb, 'jmdict'),
    ('ja', '薬', '藥', '{"kana": "くすり", "jlpt": "N5", "jmdict_seq": 1538160, "meaning_en": "medicine"}'::jsonb, 'jmdict'),
    ('ja', 'ください', '請（給我）', '{"kana": "ください", "jlpt": "N5", "jmdict_seq": 1184270, "meaning_en": "Please"}'::jsonb, 'jmdict'),
    ('ja', '果物', '水果', '{"kana": "くだもの", "jlpt": "N5", "jmdict_seq": 1193060, "meaning_en": "Fruit"}'::jsonb, 'jmdict'),
    ('ja', '口', '嘴巴', '{"kana": "くち", "jlpt": "N5", "jmdict_seq": 1275640, "meaning_en": "mouth, opening"}'::jsonb, 'jmdict'),
    ('ja', '靴', '鞋子', '{"kana": "くつ", "jlpt": "N5", "jmdict_seq": 1246700, "meaning_en": "Shoes"}'::jsonb, 'jmdict'),
    ('ja', '靴下', '襪子', '{"kana": "くつした", "jlpt": "N5", "jmdict_seq": 1246740, "meaning_en": "Socks"}'::jsonb, 'jmdict'),
    ('ja', '国', '國家', '{"kana": "くに", "jlpt": "N5", "jmdict_seq": 1592250, "meaning_en": "Country"}'::jsonb, 'jmdict'),
    ('ja', '曇り', '陰天', '{"kana": "くもり", "jlpt": "N5", "jmdict_seq": 1592340, "meaning_en": "cloudy weather"}'::jsonb, 'jmdict'),
    ('ja', '曇る', '變陰', '{"kana": "くもる", "jlpt": "N5", "jmdict_seq": 1457560, "meaning_en": "to become cloudy, to become dim"}'::jsonb, 'jmdict'),
    ('ja', '暗い', '暗', '{"kana": "くらい", "jlpt": "N5", "jmdict_seq": 1154330, "meaning_en": "Gloomy"}'::jsonb, 'jmdict'),
    ('ja', 'クラス', '班級', '{"kana": "クラス", "jlpt": "N5", "jmdict_seq": 1044070, "meaning_en": "Class"}'::jsonb, 'jmdict'),
    ('ja', 'グラム', '公克', '{"kana": "グラム", "jlpt": "N5", "jmdict_seq": 1046810, "meaning_en": "Gram"}'::jsonb, 'jmdict'),
    ('ja', '来る', '來', '{"kana": "くる", "jlpt": "N5", "jmdict_seq": 1547720, "meaning_en": "to come"}'::jsonb, 'jmdict'),
    ('ja', '車', '車', '{"kana": "くるま", "jlpt": "N5", "jmdict_seq": 1323080, "meaning_en": "car, vehicle"}'::jsonb, 'jmdict'),
    ('ja', '黒', '黑色', '{"kana": "くろ", "jlpt": "N5", "jmdict_seq": 1287410, "meaning_en": "Black"}'::jsonb, 'jmdict'),
    ('ja', '黒い', '黑色的', '{"kana": "くろい", "jlpt": "N5", "jmdict_seq": 1287420, "meaning_en": "black"}'::jsonb, 'jmdict'),
    ('ja', '警官', '警察', '{"kana": "けいかん", "jlpt": "N5", "jmdict_seq": 1252330, "meaning_en": "policeman"}'::jsonb, 'jmdict'),
    ('ja', '今朝', '今天早上', '{"kana": "けさ", "jlpt": "N5", "jmdict_seq": 1579100, "meaning_en": "this morning"}'::jsonb, 'jmdict'),
    ('ja', '消す', '關掉/擦掉', '{"kana": "けす", "jlpt": "N5", "jmdict_seq": 1350110, "meaning_en": "to erase, to turn off power"}'::jsonb, 'jmdict'),
    ('ja', '結構', '不錯/夠了', '{"kana": "けっこう", "jlpt": "N5", "jmdict_seq": 1254760, "meaning_en": "splendid, enough"}'::jsonb, 'jmdict'),
    ('ja', '結婚', '結婚', '{"kana": "けっこん", "jlpt": "N5", "jmdict_seq": 1254790, "meaning_en": "Marriage"}'::jsonb, 'jmdict'),
    ('ja', '月曜日', '星期一', '{"kana": "げつようび", "jlpt": "N5", "jmdict_seq": 1255890, "meaning_en": "Monday"}'::jsonb, 'jmdict'),
    ('ja', '玄関', '玄關', '{"kana": "げんかん", "jlpt": "N5", "jmdict_seq": 1263400, "meaning_en": "entry hall"}'::jsonb, 'jmdict'),
    ('ja', '元気', '健康有活力', '{"kana": "げんき", "jlpt": "N5", "jmdict_seq": 1260720, "meaning_en": "health, vitality"}'::jsonb, 'jmdict'),
    ('ja', '五', '五', '{"kana": "ご", "jlpt": "N5", "jmdict_seq": 1268060, "meaning_en": "Five"}'::jsonb, 'jmdict'),
    ('ja', '公園', '公園', '{"kana": "こうえん", "jlpt": "N5", "jmdict_seq": 1273270, "meaning_en": "Park"}'::jsonb, 'jmdict'),
    ('ja', '交差点', '十字路口', '{"kana": "こうさてん", "jlpt": "N5", "jmdict_seq": 1592970, "meaning_en": "intersection"}'::jsonb, 'jmdict'),
    ('ja', '紅茶', '紅茶', '{"kana": "こうちゃ", "jlpt": "N5", "jmdict_seq": 1280770, "meaning_en": "black tea"}'::jsonb, 'jmdict'),
    ('ja', '交番', '派出所', '{"kana": "こうばん", "jlpt": "N5", "jmdict_seq": 1272500, "meaning_en": "police box"}'::jsonb, 'jmdict'),
    ('ja', '声', '聲音', '{"kana": "こえ", "jlpt": "N5", "jmdict_seq": 1380440, "meaning_en": "Voice"}'::jsonb, 'jmdict'),
    ('ja', 'コート', '外套', '{"kana": "コート", "jlpt": "N5", "jmdict_seq": 1049000, "meaning_en": "coat, tennis court"}'::jsonb, 'jmdict'),
    ('ja', 'コーヒー', '咖啡', '{"kana": "コーヒー", "jlpt": "N5", "jmdict_seq": 1049180, "meaning_en": "Coffee"}'::jsonb, 'jmdict'),
    ('ja', '此処', '這裡', '{"kana": "ここ", "jlpt": "N5", "jmdict_seq": 1288810, "meaning_en": "Here"}'::jsonb, 'jmdict'),
    ('ja', '午後', '下午', '{"kana": "ごご", "jlpt": "N5", "jmdict_seq": 1268990, "meaning_en": "afternoon"}'::jsonb, 'jmdict'),
    ('ja', '九日', '九號', '{"kana": "ここのか", "jlpt": "N5", "jmdict_seq": 1243850, "meaning_en": "nine days, ninth day"}'::jsonb, 'jmdict'),
    ('ja', '九つ', '九個', '{"kana": "ここのつ", "jlpt": "N5", "jmdict_seq": 1243600, "meaning_en": "Nine"}'::jsonb, 'jmdict'),
    ('ja', '午前', '上午', '{"kana": "ごぜん", "jlpt": "N5", "jmdict_seq": 1269060, "meaning_en": "morning"}'::jsonb, 'jmdict'),
    ('ja', '答える', '回答', '{"kana": "こたえる", "jlpt": "N5", "jmdict_seq": 1449540, "meaning_en": "to answer"}'::jsonb, 'jmdict'),
    ('ja', 'こちら', '這邊（禮貌）', '{"kana": "こちら", "jlpt": "N5", "jmdict_seq": 1004500, "meaning_en": "this person or way"}'::jsonb, 'jmdict'),
    ('ja', '此方', '這邊（口語）', '{"kana": "こっち", "jlpt": "N5", "jmdict_seq": 1004500, "meaning_en": "this person or way"}'::jsonb, 'jmdict'),
    ('ja', 'コップ', '玻璃杯', '{"kana": "コップ", "jlpt": "N5", "jmdict_seq": 2846389, "meaning_en": "a glass"}'::jsonb, 'jmdict'),
    ('ja', '今年', '今年', '{"kana": "ことし", "jlpt": "N5", "jmdict_seq": 1579130, "meaning_en": "this year"}'::jsonb, 'jmdict'),
    ('ja', '言葉', '話/詞', '{"kana": "ことば", "jlpt": "N5", "jmdict_seq": 1264540, "meaning_en": "word, language"}'::jsonb, 'jmdict'),
    ('ja', '子供', '小孩', '{"kana": "こども", "jlpt": "N5", "jmdict_seq": 1307850, "meaning_en": "Child"}'::jsonb, 'jmdict'),
    ('ja', '此の', '這個', '{"kana": "この", "jlpt": "N5", "jmdict_seq": 1582920, "meaning_en": "This"}'::jsonb, 'jmdict'),
    ('ja', '御飯', '飯', '{"kana": "ごはん", "jlpt": "N5", "jmdict_seq": 1270590, "meaning_en": "cooked rice, meal"}'::jsonb, 'jmdict'),
    ('ja', 'コピー', '影印', '{"kana": "コピー", "jlpt": "N5", "jmdict_seq": 1050590, "meaning_en": "to copy"}'::jsonb, 'jmdict'),
    ('ja', '困る', '困擾', '{"kana": "こまる", "jlpt": "N5", "jmdict_seq": 1289590, "meaning_en": "to be worried"}'::jsonb, 'jmdict'),
    ('ja', 'これ', '這個（東西）', '{"kana": "これ", "jlpt": "N5", "jmdict_seq": 2216120, "meaning_en": "This"}'::jsonb, 'jmdict'),
    ('ja', '今月', '這個月', '{"kana": "こんげつ", "jlpt": "N5", "jmdict_seq": 1289100, "meaning_en": "this month"}'::jsonb, 'jmdict'),
    ('ja', '今週', '這週', '{"kana": "こんしゅう", "jlpt": "N5", "jmdict_seq": 1289220, "meaning_en": "this week"}'::jsonb, 'jmdict'),
    ('ja', 'こんな', '這樣的', '{"kana": "こんな", "jlpt": "N5", "jmdict_seq": 1004880, "meaning_en": "Such"}'::jsonb, 'jmdict'),
    ('ja', '今晩', '今晚', '{"kana": "こんばん", "jlpt": "N5", "jmdict_seq": 1289470, "meaning_en": "this evening"}'::jsonb, 'jmdict'),
    ('ja', 'さあ', '那麼...', '{"kana": "さあ", "jlpt": "N5", "jmdict_seq": 1005110, "meaning_en": "well…"}'::jsonb, 'jmdict'),
    ('ja', '財布', '錢包', '{"kana": "さいふ", "jlpt": "N5", "jmdict_seq": 1296970, "meaning_en": "Wallet"}'::jsonb, 'jmdict'),
    ('ja', '魚', '魚', '{"kana": "さかな", "jlpt": "N5", "jmdict_seq": 1578010, "meaning_en": "Fish"}'::jsonb, 'jmdict'),
    ('ja', '先', '前面/先', '{"kana": "さき", "jlpt": "N5", "jmdict_seq": 1387210, "meaning_en": "the future, previous"}'::jsonb, 'jmdict'),
    ('ja', '咲く', '開花', '{"kana": "さく", "jlpt": "N5", "jmdict_seq": 1297210, "meaning_en": "to bloom"}'::jsonb, 'jmdict'),
    ('ja', '作文', '作文', '{"kana": "さくぶん", "jlpt": "N5", "jmdict_seq": 1297960, "meaning_en": "composition, writing"}'::jsonb, 'jmdict'),
    ('ja', '差す', '撐（傘）/伸（手）', '{"kana": "さす", "jlpt": "N5", "jmdict_seq": 1291330, "meaning_en": "to stretch out hands, to raise an umbrella"}'::jsonb, 'jmdict'),
    ('ja', '雑誌', '雜誌', '{"kana": "ざっし", "jlpt": "N5", "jmdict_seq": 1299400, "meaning_en": "Magazine"}'::jsonb, 'jmdict'),
    ('ja', '砂糖', '糖', '{"kana": "さとう", "jlpt": "N5", "jmdict_seq": 1291600, "meaning_en": "Sugar"}'::jsonb, 'jmdict'),
    ('ja', '寒い', '冷', '{"kana": "さむい", "jlpt": "N5", "jmdict_seq": 1210360, "meaning_en": "Cold"}'::jsonb, 'jmdict'),
    ('ja', 'さ来年', '後年', '{"kana": "さらいねん", "jlpt": "N5", "jmdict_seq": 1293660, "meaning_en": "year after next"}'::jsonb, 'jmdict'),
    ('ja', '三', '三', '{"kana": "さん", "jlpt": "N5", "jmdict_seq": 1579350, "meaning_en": "Three"}'::jsonb, 'jmdict'),
    ('ja', '散歩', '散步', '{"kana": "さんぽ", "jlpt": "N5", "jmdict_seq": 1303620, "meaning_en": "to stroll"}'::jsonb, 'jmdict'),
    ('ja', '四', '四（し）', '{"kana": "し", "jlpt": "N5", "jmdict_seq": 1579470, "meaning_en": "Four"}'::jsonb, 'jmdict'),
    ('ja', '四', '四（よん）', '{"kana": "よん", "jlpt": "N5", "jmdict_seq": 1579470, "meaning_en": "Four"}'::jsonb, 'jmdict'),
    ('ja', '塩', '鹽', '{"kana": "しお", "jlpt": "N5", "jmdict_seq": 1576630, "meaning_en": "Salt"}'::jsonb, 'jmdict'),
    ('ja', '然し', '但是', '{"kana": "しかし", "jlpt": "N5", "jmdict_seq": 1505990, "meaning_en": "However"}'::jsonb, 'jmdict'),
    ('ja', '時間', '時間', '{"kana": "じかん", "jlpt": "N5", "jmdict_seq": 1315920, "meaning_en": "Time"}'::jsonb, 'jmdict'),
    ('ja', '仕事', '工作', '{"kana": "しごと", "jlpt": "N5", "jmdict_seq": 1304970, "meaning_en": "Job"}'::jsonb, 'jmdict'),
    ('ja', '辞書', '字典', '{"kana": "じしょ", "jlpt": "N5", "jmdict_seq": 1318970, "meaning_en": "Dictionary"}'::jsonb, 'jmdict'),
    ('ja', '静か', '安靜', '{"kana": "しずか", "jlpt": "N5", "jmdict_seq": 1381820, "meaning_en": "Quiet"}'::jsonb, 'jmdict'),
    ('ja', '下', '下面', '{"kana": "した", "jlpt": "N5", "jmdict_seq": 1184140, "meaning_en": "Below"}'::jsonb, 'jmdict'),
    ('ja', '七', '七（しち）', '{"kana": "しち", "jlpt": "N5", "jmdict_seq": 1319210, "meaning_en": "Seven"}'::jsonb, 'jmdict'),
    ('ja', '七', '七（なな）', '{"kana": "なな", "jlpt": "N5", "jmdict_seq": 1319210, "meaning_en": "Seven"}'::jsonb, 'jmdict'),
    ('ja', '質問', '問題（提問）', '{"kana": "しつもん", "jlpt": "N5", "jmdict_seq": 1320760, "meaning_en": "Question"}'::jsonb, 'jmdict'),
    ('ja', '自転車', '腳踏車', '{"kana": "じてんしゃ", "jlpt": "N5", "jmdict_seq": 1318290, "meaning_en": "Bicycle"}'::jsonb, 'jmdict'),
    ('ja', '自動車', '汽車', '{"kana": "じどうしゃ", "jlpt": "N5", "jmdict_seq": 1318400, "meaning_en": "Automobile"}'::jsonb, 'jmdict'),
    ('ja', '死ぬ', '死', '{"kana": "しぬ", "jlpt": "N5", "jmdict_seq": 1310730, "meaning_en": "to die"}'::jsonb, 'jmdict'),
    ('ja', '字引', '字典（舊式說法）', '{"kana": "じびき", "jlpt": "N5", "jmdict_seq": 1315140, "meaning_en": "Dictionary"}'::jsonb, 'jmdict'),
    ('ja', '自分', '自己', '{"kana": "じぶん", "jlpt": "N5", "jmdict_seq": 1318610, "meaning_en": "Oneself"}'::jsonb, 'jmdict'),
    ('ja', '閉まる', '關（自動）', '{"kana": "しまる", "jlpt": "N5", "jmdict_seq": 1436560, "meaning_en": "to close, to be closed"}'::jsonb, 'jmdict'),
    ('ja', '閉める', '關上', '{"kana": "しめる", "jlpt": "N5", "jmdict_seq": 1508590, "meaning_en": "to close something"}'::jsonb, 'jmdict'),
    ('ja', '締める', '繫（領帶）', '{"kana": "しめる", "jlpt": "N5", "jmdict_seq": 1436570, "meaning_en": "to tie"}'::jsonb, 'jmdict'),
    ('ja', 'じゃ', '那麼（口語）', '{"kana": "じゃ", "jlpt": "N5", "jmdict_seq": 1005900, "meaning_en": "well then…"}'::jsonb, 'jmdict'),
    ('ja', 'じゃあ', '那麼（口語拉長）', '{"kana": "じゃあ", "jlpt": "N5", "jmdict_seq": 1005900, "meaning_en": "well then…"}'::jsonb, 'jmdict'),
    ('ja', '写真', '照片', '{"kana": "しゃしん", "jlpt": "N5", "jmdict_seq": 1321900, "meaning_en": "photograph"}'::jsonb, 'jmdict'),
    ('ja', 'シャツ', '襯衫', '{"kana": "シャツ", "jlpt": "N5", "jmdict_seq": 1061520, "meaning_en": "Shirt"}'::jsonb, 'jmdict'),
    ('ja', 'シャワー', '蓮蓬頭', '{"kana": "シャワー", "jlpt": "N5", "jmdict_seq": 1061820, "meaning_en": "Shower"}'::jsonb, 'jmdict'),
    ('ja', '十', '十（じゅう）', '{"kana": "じゅう", "jlpt": "N5", "jmdict_seq": 1579840, "meaning_en": "Ten"}'::jsonb, 'jmdict'),
    ('ja', '十', '十（とお）', '{"kana": "とお", "jlpt": "N5", "jmdict_seq": 1579840, "meaning_en": "Ten"}'::jsonb, 'jmdict'),
    ('ja', '授業', '上課', '{"kana": "じゅぎょう", "jlpt": "N5", "jmdict_seq": 1330290, "meaning_en": "lesson, class work"}'::jsonb, 'jmdict'),
    ('ja', '宿題', '作業', '{"kana": "しゅくだい", "jlpt": "N5", "jmdict_seq": 1337270, "meaning_en": "homework"}'::jsonb, 'jmdict'),
    ('ja', '上手', '厲害（拿手）', '{"kana": "じょうず", "jlpt": "N5", "jmdict_seq": 1353320, "meaning_en": "Skillful"}'::jsonb, 'jmdict'),
    ('ja', '丈夫', '堅固', '{"kana": "じょうぶ", "jlpt": "N5", "jmdict_seq": 1580480, "meaning_en": "strong, durable"}'::jsonb, 'jmdict'),
    ('ja', 'しょうゆ', '醬油', '{"kana": "しょうゆ", "jlpt": "N5", "jmdict_seq": 1595020, "meaning_en": "soy sauce"}'::jsonb, 'jmdict'),
    ('ja', '食堂', '食堂', '{"kana": "しょくどう", "jlpt": "N5", "jmdict_seq": 1358550, "meaning_en": "dining hall"}'::jsonb, 'jmdict'),
    ('ja', '知る', '知道', '{"kana": "しる", "jlpt": "N5", "jmdict_seq": 1420470, "meaning_en": "to know"}'::jsonb, 'jmdict'),
    ('ja', '白', '白色', '{"kana": "しろ", "jlpt": "N5", "jmdict_seq": 1474900, "meaning_en": "White"}'::jsonb, 'jmdict'),
    ('ja', '白い', '白色的', '{"kana": "しろい", "jlpt": "N5", "jmdict_seq": 1474910, "meaning_en": "White"}'::jsonb, 'jmdict'),
    ('ja', '新聞', '報紙', '{"kana": "しんぶん", "jlpt": "N5", "jmdict_seq": 1362360, "meaning_en": "newspaper"}'::jsonb, 'jmdict'),
    ('ja', '水曜日', '星期三', '{"kana": "すいようび", "jlpt": "N5", "jmdict_seq": 1372190, "meaning_en": "Wednesday"}'::jsonb, 'jmdict'),
    ('ja', '吸う', '吸（菸/氣）', '{"kana": "すう", "jlpt": "N5", "jmdict_seq": 1228260, "meaning_en": "to smoke, to suck"}'::jsonb, 'jmdict'),
    ('ja', 'スカート', '裙子', '{"kana": "スカート", "jlpt": "N5", "jmdict_seq": 1067470, "meaning_en": "Skirt"}'::jsonb, 'jmdict'),
    ('ja', '好き', '喜歡', '{"kana": "すき", "jlpt": "N5", "jmdict_seq": 1277450, "meaning_en": "Likeable"}'::jsonb, 'jmdict'),
    ('ja', '少ない', '少', '{"kana": "すくない", "jlpt": "N5", "jmdict_seq": 1348910, "meaning_en": "a few"}'::jsonb, 'jmdict'),
    ('ja', 'すぐに', '馬上', '{"kana": "すぐに", "jlpt": "N5", "jmdict_seq": 1430620, "meaning_en": "Instantly"}'::jsonb, 'jmdict'),
    ('ja', '少し', '一點點', '{"kana": "すこし", "jlpt": "N5", "jmdict_seq": 1348870, "meaning_en": "Few"}'::jsonb, 'jmdict'),
    ('ja', '涼しい', '涼爽', '{"kana": "すずしい", "jlpt": "N5", "jmdict_seq": 1554370, "meaning_en": "Refreshing"}'::jsonb, 'jmdict'),
    ('ja', 'ストーブ', '暖爐', '{"kana": "ストーブ", "jlpt": "N5", "jmdict_seq": 1070790, "meaning_en": "Heater"}'::jsonb, 'jmdict'),
    ('ja', 'スプーン', '湯匙', '{"kana": "スプーン", "jlpt": "N5", "jmdict_seq": 1072590, "meaning_en": "Spoon"}'::jsonb, 'jmdict'),
    ('ja', 'スポーツ', '運動', '{"kana": "スポーツ", "jlpt": "N5", "jmdict_seq": 1073210, "meaning_en": "Sport"}'::jsonb, 'jmdict'),
    ('ja', 'ズボン', '長褲', '{"kana": "ズボン", "jlpt": "N5", "jmdict_seq": 1074260, "meaning_en": "Trousers"}'::jsonb, 'jmdict'),
    ('ja', '住む', '住', '{"kana": "すむ", "jlpt": "N5", "jmdict_seq": 1334040, "meaning_en": "to live in"}'::jsonb, 'jmdict'),
    ('ja', 'スリッパ', '拖鞋', '{"kana": "スリッパ", "jlpt": "N5", "jmdict_seq": 1073900, "meaning_en": "Slippers"}'::jsonb, 'jmdict'),
    ('ja', '為る', '做', '{"kana": "する", "jlpt": "N5", "jmdict_seq": 1157170, "meaning_en": "to do"}'::jsonb, 'jmdict'),
    ('ja', '座る', '坐', '{"kana": "すわる", "jlpt": "N5", "jmdict_seq": 1291800, "meaning_en": "to sit"}'::jsonb, 'jmdict'),
    ('ja', '背', '身高/背', '{"kana": "せ", "jlpt": "N5", "jmdict_seq": 2147990, "meaning_en": "height, stature"}'::jsonb, 'jmdict'),
    ('ja', '生徒', '學生（中小學）', '{"kana": "せいと", "jlpt": "N5", "jmdict_seq": 1379380, "meaning_en": "Pupil"}'::jsonb, 'jmdict'),
    ('ja', 'セーター', '毛衣', '{"kana": "セーター", "jlpt": "N5", "jmdict_seq": 1074270, "meaning_en": "sweater, jumper"}'::jsonb, 'jmdict'),
    ('ja', 'せっけん', '肥皂', '{"kana": "せっけん", "jlpt": "N5", "jmdict_seq": 1382590, "meaning_en": "soap"}'::jsonb, 'jmdict'),
    ('ja', '背広', '西裝', '{"kana": "せびろ", "jlpt": "N5", "jmdict_seq": 1472740, "meaning_en": "business suit"}'::jsonb, 'jmdict'),
    ('ja', '狭い', '狹窄', '{"kana": "せまい", "jlpt": "N5", "jmdict_seq": 1237680, "meaning_en": "Narrow"}'::jsonb, 'jmdict'),
    ('ja', 'ゼロ', '零（ゼロ）', '{"kana": "ゼロ", "jlpt": "N5", "jmdict_seq": 2839962, "meaning_en": "Zero"}'::jsonb, 'jmdict'),
    ('ja', '千', '千', '{"kana": "せん", "jlpt": "N5", "jmdict_seq": 1388740, "meaning_en": "Thousand"}'::jsonb, 'jmdict'),
    ('ja', '先月', '上個月', '{"kana": "せんげつ", "jlpt": "N5", "jmdict_seq": 1387500, "meaning_en": "last month"}'::jsonb, 'jmdict'),
    ('ja', '先週', '上週', '{"kana": "せんしゅう", "jlpt": "N5", "jmdict_seq": 1387870, "meaning_en": "last week"}'::jsonb, 'jmdict'),
    ('ja', '先生', '老師', '{"kana": "せんせい", "jlpt": "N5", "jmdict_seq": 1387990, "meaning_en": "teacher, doctor"}'::jsonb, 'jmdict'),
    ('ja', '洗濯', '洗衣服', '{"kana": "せんたく", "jlpt": "N5", "jmdict_seq": 1390980, "meaning_en": "Washing"}'::jsonb, 'jmdict'),
    ('ja', '全部', '全部', '{"kana": "ぜんぶ", "jlpt": "N5", "jmdict_seq": 1396130, "meaning_en": "All"}'::jsonb, 'jmdict'),
    ('ja', '掃除', '打掃', '{"kana": "そうじ", "jlpt": "N5", "jmdict_seq": 1399790, "meaning_en": "to clean, to sweep"}'::jsonb, 'jmdict'),
    ('ja', 'そうして', '然後（書面）', '{"kana": "そうして", "jlpt": "N5", "jmdict_seq": 1612860, "meaning_en": "And"}'::jsonb, 'jmdict'),
    ('ja', 'そして', '然後', '{"kana": "そして", "jlpt": "N5", "jmdict_seq": 1006730, "meaning_en": "And"}'::jsonb, 'jmdict'),
    ('ja', '其処', '那裡', '{"kana": "そこ", "jlpt": "N5", "jmdict_seq": 1006670, "meaning_en": "that place"}'::jsonb, 'jmdict'),
    ('ja', 'そちら', '那邊（禮貌）', '{"kana": "そちら", "jlpt": "N5", "jmdict_seq": 1006780, "meaning_en": "over there"}'::jsonb, 'jmdict'),
    ('ja', 'そっち', '那邊（口語）', '{"kana": "そっち", "jlpt": "N5", "jmdict_seq": 1006780, "meaning_en": "over there"}'::jsonb, 'jmdict')
  returning id, lemma
)
insert into shrine_words (shrine_id, word_id, position)
select
  (select id from shrines where slug = 'inari'),
  nw.id,
  100 + row_number() over (order by nw.lemma)
from new_words nw;
