-- 005_n5_words_meiji
-- N5 單字匯入：明治神宮（CSV 行 344-685，共 342 字）
-- 資料源：stephenmk/yomitan-jlpt-vocab (CC-BY, Jonathan Waller / Tanos)
-- 中文翻譯：Claude（學生友善口語風格）

with new_words as (
  insert into words (lang_code, lemma, meaning_zh, meta, source) values
    ('ja', '外', '外面', '{"kana": "そと", "jlpt": "N5", "jmdict_seq": 1203250, "meaning_en": "Outside"}'::jsonb, 'jmdict'),
    ('ja', '其の', '那個', '{"kana": "その", "jlpt": "N5", "jmdict_seq": 1006830, "meaning_en": "That"}'::jsonb, 'jmdict'),
    ('ja', '側', '旁邊', '{"kana": "そば", "jlpt": "N5", "jmdict_seq": 1403830, "meaning_en": "near, beside"}'::jsonb, 'jmdict'),
    ('ja', '空', '天空', '{"kana": "そら", "jlpt": "N5", "jmdict_seq": 1245290, "meaning_en": "Sky"}'::jsonb, 'jmdict'),
    ('ja', 'それ', '那個（東西）', '{"kana": "それ", "jlpt": "N5", "jmdict_seq": 2216210, "meaning_en": "that"}'::jsonb, 'jmdict'),
    ('ja', 'それから', '然後', '{"kana": "それから", "jlpt": "N5", "jmdict_seq": 1006980, "meaning_en": "after that"}'::jsonb, 'jmdict'),
    ('ja', 'それでは', '那麼', '{"kana": "それでは", "jlpt": "N5", "jmdict_seq": 1406050, "meaning_en": "in that situation"}'::jsonb, 'jmdict'),
    ('ja', '大学', '大學', '{"kana": "だいがく", "jlpt": "N5", "jmdict_seq": 1413240, "meaning_en": "university"}'::jsonb, 'jmdict'),
    ('ja', '大使館', '大使館', '{"kana": "たいしかん", "jlpt": "N5", "jmdict_seq": 1413890, "meaning_en": "embassy"}'::jsonb, 'jmdict'),
    ('ja', '大丈夫', '沒問題', '{"kana": "だいじょうぶ", "jlpt": "N5", "jmdict_seq": 1414150, "meaning_en": "all right"}'::jsonb, 'jmdict'),
    ('ja', '大好き', '最喜歡', '{"kana": "だいすき", "jlpt": "N5", "jmdict_seq": 1413660, "meaning_en": "to be very likeable"}'::jsonb, 'jmdict'),
    ('ja', '大切', '重要', '{"kana": "たいせつ", "jlpt": "N5", "jmdict_seq": 1414340, "meaning_en": "important"}'::jsonb, 'jmdict'),
    ('ja', '台所', '廚房', '{"kana": "だいどころ", "jlpt": "N5", "jmdict_seq": 1412640, "meaning_en": "kitchen"}'::jsonb, 'jmdict'),
    ('ja', '大変', '很/糟糕', '{"kana": "たいへん", "jlpt": "N5", "jmdict_seq": 1415000, "meaning_en": "difficult situation"}'::jsonb, 'jmdict'),
    ('ja', '高い', '高/貴', '{"kana": "たかい", "jlpt": "N5", "jmdict_seq": 1283190, "meaning_en": "tall, expensive"}'::jsonb, 'jmdict'),
    ('ja', 'たくさん', '很多', '{"kana": "たくさん", "jlpt": "N5", "jmdict_seq": 1415870, "meaning_en": "many"}'::jsonb, 'jmdict'),
    ('ja', 'タクシー', '計程車', '{"kana": "タクシー", "jlpt": "N5", "jmdict_seq": 1076190, "meaning_en": "taxi"}'::jsonb, 'jmdict'),
    ('ja', '出す', '拿出', '{"kana": "だす", "jlpt": "N5", "jmdict_seq": 1338180, "meaning_en": "to put out"}'::jsonb, 'jmdict'),
    ('ja', '立つ', '站', '{"kana": "たつ", "jlpt": "N5", "jmdict_seq": 1597040, "meaning_en": "to stand"}'::jsonb, 'jmdict'),
    ('ja', '縦', '長度（直）', '{"kana": "たて", "jlpt": "N5", "jmdict_seq": 1335640, "meaning_en": "length,height"}'::jsonb, 'jmdict'),
    ('ja', '建物', '建築物', '{"kana": "たてもの", "jlpt": "N5", "jmdict_seq": 1257540, "meaning_en": "building"}'::jsonb, 'jmdict'),
    ('ja', '楽しい', '開心', '{"kana": "たのしい", "jlpt": "N5", "jmdict_seq": 1207240, "meaning_en": "enjoyable"}'::jsonb, 'jmdict'),
    ('ja', '頼む', '拜託', '{"kana": "たのむ", "jlpt": "N5", "jmdict_seq": 1548370, "meaning_en": "to ask"}'::jsonb, 'jmdict'),
    ('ja', 'たばこ', '香菸', '{"kana": "たばこ", "jlpt": "N5", "jmdict_seq": 1597150, "meaning_en": "tobacco,cigarettes"}'::jsonb, 'jmdict'),
    ('ja', '多分', '大概', '{"kana": "たぶん", "jlpt": "N5", "jmdict_seq": 1407980, "meaning_en": "probably"}'::jsonb, 'jmdict'),
    ('ja', '食べ物', '食物', '{"kana": "たべもの", "jlpt": "N5", "jmdict_seq": 1358340, "meaning_en": "food"}'::jsonb, 'jmdict'),
    ('ja', '食べる', '吃', '{"kana": "たべる", "jlpt": "N5", "jmdict_seq": 1358280, "meaning_en": "to eat"}'::jsonb, 'jmdict'),
    ('ja', '卵', '蛋', '{"kana": "たまご", "jlpt": "N5", "jmdict_seq": 1549140, "meaning_en": "egg"}'::jsonb, 'jmdict'),
    ('ja', '誰', '誰', '{"kana": "だれ", "jlpt": "N5", "jmdict_seq": 1416830, "meaning_en": "who"}'::jsonb, 'jmdict'),
    ('ja', '誰か', '某人', '{"kana": "だれか", "jlpt": "N5", "jmdict_seq": 1416840, "meaning_en": "somebody"}'::jsonb, 'jmdict'),
    ('ja', '誕生日', '生日', '{"kana": "たんじょうび", "jlpt": "N5", "jmdict_seq": 1419110, "meaning_en": "birthday"}'::jsonb, 'jmdict'),
    ('ja', 'だんだん', '漸漸', '{"kana": "だんだん", "jlpt": "N5", "jmdict_seq": 2546180, "meaning_en": "gradually"}'::jsonb, 'jmdict'),
    ('ja', '小さい', '小', '{"kana": "ちいさい", "jlpt": "N5", "jmdict_seq": 1347750, "meaning_en": "little"}'::jsonb, 'jmdict'),
    ('ja', '小さな', '小的', '{"kana": "ちいさな", "jlpt": "N5", "jmdict_seq": 2136180, "meaning_en": "little"}'::jsonb, 'jmdict'),
    ('ja', '近い', '近', '{"kana": "ちかい", "jlpt": "N5", "jmdict_seq": 1242130, "meaning_en": "near"}'::jsonb, 'jmdict'),
    ('ja', '違う', '不一樣', '{"kana": "ちがう", "jlpt": "N5", "jmdict_seq": 1158880, "meaning_en": "to differ"}'::jsonb, 'jmdict'),
    ('ja', '近く', '附近', '{"kana": "ちかく", "jlpt": "N5", "jmdict_seq": 1242160, "meaning_en": "near"}'::jsonb, 'jmdict'),
    ('ja', '地下鉄', '地鐵', '{"kana": "ちかてつ", "jlpt": "N5", "jmdict_seq": 1420900, "meaning_en": "underground train"}'::jsonb, 'jmdict'),
    ('ja', '地図', '地圖', '{"kana": "ちず", "jlpt": "N5", "jmdict_seq": 1421290, "meaning_en": "map"}'::jsonb, 'jmdict'),
    ('ja', '茶色', '咖啡色', '{"kana": "ちゃいろ", "jlpt": "N5", "jmdict_seq": 1422720, "meaning_en": "brown"}'::jsonb, 'jmdict'),
    ('ja', 'ちゃわん', '飯碗', '{"kana": "ちゃわん", "jlpt": "N5", "jmdict_seq": 1597530, "meaning_en": "rice bowl"}'::jsonb, 'jmdict'),
    ('ja', '丁度', '剛好', '{"kana": "ちょうど", "jlpt": "N5", "jmdict_seq": 1427340, "meaning_en": "exactly"}'::jsonb, 'jmdict'),
    ('ja', 'ちょっと', '一下下', '{"kana": "ちょっと", "jlpt": "N5", "jmdict_seq": 1163940, "meaning_en": "somewhat"}'::jsonb, 'jmdict'),
    ('ja', '一日', '一號', '{"kana": "ついたち", "jlpt": "N5", "jmdict_seq": 2225040, "meaning_en": "first of month"}'::jsonb, 'jmdict'),
    ('ja', '使う', '使用', '{"kana": "つかう", "jlpt": "N5", "jmdict_seq": 1305990, "meaning_en": "to use"}'::jsonb, 'jmdict'),
    ('ja', '疲れる', '累', '{"kana": "つかれる", "jlpt": "N5", "jmdict_seq": 1483740, "meaning_en": "to get tired"}'::jsonb, 'jmdict'),
    ('ja', '次', '下一個', '{"kana": "つぎ", "jlpt": "N5", "jmdict_seq": 1316380, "meaning_en": "next"}'::jsonb, 'jmdict'),
    ('ja', '着く', '到達', '{"kana": "つく", "jlpt": "N5", "jmdict_seq": 1422970, "meaning_en": "to arrive at"}'::jsonb, 'jmdict'),
    ('ja', '机', '桌子', '{"kana": "つくえ", "jlpt": "N5", "jmdict_seq": 1220210, "meaning_en": "desk"}'::jsonb, 'jmdict'),
    ('ja', '作る', '做', '{"kana": "つくる", "jlpt": "N5", "jmdict_seq": 1597890, "meaning_en": "to make"}'::jsonb, 'jmdict'),
    ('ja', '付ける', '打開（電源）', '{"kana": "つける", "jlpt": "N5", "jmdict_seq": 1495770, "meaning_en": "to turn on"}'::jsonb, 'jmdict'),
    ('ja', '勤める', '上班', '{"kana": "つとめる", "jlpt": "N5", "jmdict_seq": 1240825, "meaning_en": "to work for someone"}'::jsonb, 'jmdict'),
    ('ja', 'つまらない', '無聊', '{"kana": "つまらない", "jlpt": "N5", "jmdict_seq": 1008190, "meaning_en": "boring"}'::jsonb, 'jmdict'),
    ('ja', '冷たい', '冰涼（觸感）', '{"kana": "つめたい", "jlpt": "N5", "jmdict_seq": 1556730, "meaning_en": "cold to the touch"}'::jsonb, 'jmdict'),
    ('ja', '強い', '強', '{"kana": "つよい", "jlpt": "N5", "jmdict_seq": 1236070, "meaning_en": "powerful"}'::jsonb, 'jmdict'),
    ('ja', '手', '手', '{"kana": "て", "jlpt": "N5", "jmdict_seq": 1327190, "meaning_en": "hand"}'::jsonb, 'jmdict'),
    ('ja', 'テープ', '膠帶', '{"kana": "テープ", "jlpt": "N5", "jmdict_seq": 1078750, "meaning_en": "tape"}'::jsonb, 'jmdict'),
    ('ja', 'テーブル', '桌子（西式）', '{"kana": "テーブル", "jlpt": "N5", "jmdict_seq": 1078630, "meaning_en": "table"}'::jsonb, 'jmdict'),
    ('ja', 'テープレコーダー', '錄音機', '{"kana": "テープレコーダー", "jlpt": "N5", "jmdict_seq": 1078810, "meaning_en": "tape recorder"}'::jsonb, 'jmdict'),
    ('ja', '出かける', '出門', '{"kana": "でかける", "jlpt": "N5", "jmdict_seq": 1598550, "meaning_en": "to go out"}'::jsonb, 'jmdict'),
    ('ja', '手紙', '信', '{"kana": "てがみ", "jlpt": "N5", "jmdict_seq": 1327720, "meaning_en": "letter"}'::jsonb, 'jmdict'),
    ('ja', '出来る', '可以/會', '{"kana": "できる", "jlpt": "N5", "jmdict_seq": 1340450, "meaning_en": "to be able to"}'::jsonb, 'jmdict'),
    ('ja', '出口', '出口', '{"kana": "でぐち", "jlpt": "N5", "jmdict_seq": 1338850, "meaning_en": "exit"}'::jsonb, 'jmdict'),
    ('ja', 'テスト', '考試', '{"kana": "テスト", "jlpt": "N5", "jmdict_seq": 1079760, "meaning_en": "test"}'::jsonb, 'jmdict'),
    ('ja', 'では', '那麼', '{"kana": "では", "jlpt": "N5", "jmdict_seq": 1008450, "meaning_en": "with that..."}'::jsonb, 'jmdict'),
    ('ja', 'デパート', '百貨公司', '{"kana": "デパート", "jlpt": "N5", "jmdict_seq": 1083590, "meaning_en": "department store"}'::jsonb, 'jmdict'),
    ('ja', 'でも', '不過', '{"kana": "でも", "jlpt": "N5", "jmdict_seq": 1008460, "meaning_en": "but"}'::jsonb, 'jmdict'),
    ('ja', '出る', '出去/出現', '{"kana": "でる", "jlpt": "N5", "jmdict_seq": 1338240, "meaning_en": "to appear,to leave"}'::jsonb, 'jmdict'),
    ('ja', 'テレビ', '電視', '{"kana": "テレビ", "jlpt": "N5", "jmdict_seq": 1080510, "meaning_en": "television"}'::jsonb, 'jmdict'),
    ('ja', '天気', '天氣', '{"kana": "てんき", "jlpt": "N5", "jmdict_seq": 1438690, "meaning_en": "weather"}'::jsonb, 'jmdict'),
    ('ja', '電気', '電/電燈', '{"kana": "でんき", "jlpt": "N5", "jmdict_seq": 1443000, "meaning_en": "electricity,electric light"}'::jsonb, 'jmdict'),
    ('ja', '電車', '電車', '{"kana": "でんしゃ", "jlpt": "N5", "jmdict_seq": 1443530, "meaning_en": "electric train"}'::jsonb, 'jmdict'),
    ('ja', '電話', '電話', '{"kana": "でんわ", "jlpt": "N5", "jmdict_seq": 1443840, "meaning_en": "telephone"}'::jsonb, 'jmdict'),
    ('ja', '戸', '門（日式）', '{"kana": "と", "jlpt": "N5", "jmdict_seq": 1266970, "meaning_en": "Japanese style door"}'::jsonb, 'jmdict'),
    ('ja', 'ドア', '門（西式）', '{"kana": "ドア", "jlpt": "N5", "jmdict_seq": 1087820, "meaning_en": "Western style door"}'::jsonb, 'jmdict'),
    ('ja', 'トイレ', '廁所', '{"kana": "トイレ", "jlpt": "N5", "jmdict_seq": 1084810, "meaning_en": "toilet"}'::jsonb, 'jmdict'),
    ('ja', '如何', '怎麼樣', '{"kana": "どう", "jlpt": "N5", "jmdict_seq": 1008910, "meaning_en": "how,in what way"}'::jsonb, 'jmdict'),
    ('ja', 'どうして', '為什麼', '{"kana": "どうして", "jlpt": "N5", "jmdict_seq": 1466940, "meaning_en": "for what reason"}'::jsonb, 'jmdict'),
    ('ja', 'どうぞ', '請（用）', '{"kana": "どうぞ", "jlpt": "N5", "jmdict_seq": 1189130, "meaning_en": "please"}'::jsonb, 'jmdict'),
    ('ja', '動物', '動物', '{"kana": "どうぶつ", "jlpt": "N5", "jmdict_seq": 1451470, "meaning_en": "animal"}'::jsonb, 'jmdict'),
    ('ja', 'どうも', '謝謝/實在', '{"kana": "どうも", "jlpt": "N5", "jmdict_seq": 1009000, "meaning_en": "thanks"}'::jsonb, 'jmdict'),
    ('ja', '遠い', '遠', '{"kana": "とおい", "jlpt": "N5", "jmdict_seq": 1177800, "meaning_en": "far"}'::jsonb, 'jmdict'),
    ('ja', '十日', '十號', '{"kana": "とおか", "jlpt": "N5", "jmdict_seq": 1335000, "meaning_en": "ten days,the tenth day"}'::jsonb, 'jmdict'),
    ('ja', '時々', '有時候', '{"kana": "ときどき", "jlpt": "N5", "jmdict_seq": 1598680, "meaning_en": "sometimes"}'::jsonb, 'jmdict'),
    ('ja', '時計', '時鐘', '{"kana": "とけい", "jlpt": "N5", "jmdict_seq": 1316140, "meaning_en": "watch,clock"}'::jsonb, 'jmdict'),
    ('ja', 'どこ', '哪裡', '{"kana": "どこ", "jlpt": "N5", "jmdict_seq": 1577140, "meaning_en": "where"}'::jsonb, 'jmdict'),
    ('ja', '所', '地方', '{"kana": "ところ", "jlpt": "N5", "jmdict_seq": 1343100, "meaning_en": "place"}'::jsonb, 'jmdict'),
    ('ja', '年', '年', '{"kana": "とし", "jlpt": "N5", "jmdict_seq": 1468060, "meaning_en": "year"}'::jsonb, 'jmdict'),
    ('ja', '図書館', '圖書館', '{"kana": "としょかん", "jlpt": "N5", "jmdict_seq": 1370420, "meaning_en": "library"}'::jsonb, 'jmdict'),
    ('ja', 'どちら', '哪邊（禮貌）', '{"kana": "どちら", "jlpt": "N5", "jmdict_seq": 1189360, "meaning_en": "which of two"}'::jsonb, 'jmdict'),
    ('ja', 'どっち', '哪邊（口語）', '{"kana": "どっち", "jlpt": "N5", "jmdict_seq": 1189360, "meaning_en": "which"}'::jsonb, 'jmdict'),
    ('ja', 'とても', '非常', '{"kana": "とても", "jlpt": "N5", "jmdict_seq": 1008630, "meaning_en": "very"}'::jsonb, 'jmdict'),
    ('ja', 'どなた', '哪位（禮貌）', '{"kana": "どなた", "jlpt": "N5", "jmdict_seq": 1189370, "meaning_en": "who"}'::jsonb, 'jmdict'),
    ('ja', '隣', '隔壁', '{"kana": "となり", "jlpt": "N5", "jmdict_seq": 1555830, "meaning_en": "next door to"}'::jsonb, 'jmdict'),
    ('ja', '何の', '哪個', '{"kana": "どの", "jlpt": "N5", "jmdict_seq": 1920240, "meaning_en": "which"}'::jsonb, 'jmdict'),
    ('ja', '飛ぶ', '飛', '{"kana": "とぶ", "jlpt": "N5", "jmdict_seq": 1429700, "meaning_en": "to fly,to hop"}'::jsonb, 'jmdict'),
    ('ja', '止まる', '停下', '{"kana": "とまる", "jlpt": "N5", "jmdict_seq": 1310620, "meaning_en": "to come to a halt"}'::jsonb, 'jmdict'),
    ('ja', '友達', '朋友', '{"kana": "ともだち", "jlpt": "N5", "jmdict_seq": 1540170, "meaning_en": "friend"}'::jsonb, 'jmdict'),
    ('ja', '土曜日', '星期六', '{"kana": "どようび", "jlpt": "N5", "jmdict_seq": 1445590, "meaning_en": "Saturday"}'::jsonb, 'jmdict'),
    ('ja', '鳥', '鳥', '{"kana": "とり", "jlpt": "N5", "jmdict_seq": 1430250, "meaning_en": "bird"}'::jsonb, 'jmdict'),
    ('ja', 'とり肉', '雞肉', '{"kana": "とりにく", "jlpt": "N5", "jmdict_seq": 1253020, "meaning_en": "chicken meat"}'::jsonb, 'jmdict'),
    ('ja', '取る', '拿', '{"kana": "とる", "jlpt": "N5", "jmdict_seq": 1326980, "meaning_en": "to take something"}'::jsonb, 'jmdict'),
    ('ja', '撮る', '拍（照）', '{"kana": "とる", "jlpt": "N5", "jmdict_seq": 1298790, "meaning_en": "to take a photo or record a film"}'::jsonb, 'jmdict'),
    ('ja', 'どれ', '哪一個', '{"kana": "どれ", "jlpt": "N5", "jmdict_seq": 1009290, "meaning_en": "which (of three or more)"}'::jsonb, 'jmdict'),
    ('ja', 'ナイフ', '刀子', '{"kana": "ナイフ", "jlpt": "N5", "jmdict_seq": 1089890, "meaning_en": "knife"}'::jsonb, 'jmdict'),
    ('ja', '中', '裡面', '{"kana": "なか", "jlpt": "N5", "jmdict_seq": 1423310, "meaning_en": "middle"}'::jsonb, 'jmdict'),
    ('ja', '長い', '長', '{"kana": "ながい", "jlpt": "N5", "jmdict_seq": 1429750, "meaning_en": "long"}'::jsonb, 'jmdict'),
    ('ja', '鳴く', '叫（動物）', '{"kana": "なく", "jlpt": "N5", "jmdict_seq": 1532870, "meaning_en": "animal noise. to chirp, roar or croak etc."}'::jsonb, 'jmdict'),
    ('ja', '無くす', '弄丟', '{"kana": "なくす", "jlpt": "N5", "jmdict_seq": 1529530, "meaning_en": "to lose something"}'::jsonb, 'jmdict'),
    ('ja', 'なぜ', '為什麼', '{"kana": "なぜ", "jlpt": "N5", "jmdict_seq": 1577120, "meaning_en": "why"}'::jsonb, 'jmdict'),
    ('ja', '夏', '夏天', '{"kana": "なつ", "jlpt": "N5", "jmdict_seq": 1191320, "meaning_en": "summer"}'::jsonb, 'jmdict'),
    ('ja', '夏休み', '暑假', '{"kana": "なつやすみ", "jlpt": "N5", "jmdict_seq": 1191420, "meaning_en": "summer holiday"}'::jsonb, 'jmdict'),
    ('ja', 'など', '等等', '{"kana": "など", "jlpt": "N5", "jmdict_seq": 1582300, "meaning_en": "et cetera"}'::jsonb, 'jmdict'),
    ('ja', '七つ', '七個', '{"kana": "ななつ", "jlpt": "N5", "jmdict_seq": 1319220, "meaning_en": "seven"}'::jsonb, 'jmdict'),
    ('ja', '七日', '七號', '{"kana": "なのか", "jlpt": "N5", "jmdict_seq": 1579630, "meaning_en": "seven days,the seventh day"}'::jsonb, 'jmdict'),
    ('ja', '名前', '名字', '{"kana": "なまえ", "jlpt": "N5", "jmdict_seq": 1531710, "meaning_en": "name"}'::jsonb, 'jmdict'),
    ('ja', '習う', '學', '{"kana": "ならう", "jlpt": "N5", "jmdict_seq": 1333070, "meaning_en": "to learn"}'::jsonb, 'jmdict'),
    ('ja', '並ぶ', '排隊', '{"kana": "ならぶ", "jlpt": "N5", "jmdict_seq": 1508380, "meaning_en": "to line up,to stand in a line"}'::jsonb, 'jmdict'),
    ('ja', '並べる', '排列', '{"kana": "ならべる", "jlpt": "N5", "jmdict_seq": 1508390, "meaning_en": "to line up,to set up"}'::jsonb, 'jmdict'),
    ('ja', 'なる', '變成', '{"kana": "なる", "jlpt": "N5", "jmdict_seq": 1375610, "meaning_en": "to become"}'::jsonb, 'jmdict'),
    ('ja', '何', '什麼（なん）', '{"kana": "なん", "jlpt": "N5", "jmdict_seq": 2846738, "meaning_en": "what"}'::jsonb, 'jmdict'),
    ('ja', '何', '什麼（なに）', '{"kana": "なに", "jlpt": "N5", "jmdict_seq": 1577100, "meaning_en": "what"}'::jsonb, 'jmdict'),
    ('ja', '二', '二', '{"kana": "に", "jlpt": "N5", "jmdict_seq": 1461140, "meaning_en": "two"}'::jsonb, 'jmdict'),
    ('ja', '賑やか', '熱鬧', '{"kana": "にぎやか", "jlpt": "N5", "jmdict_seq": 1463480, "meaning_en": "bustling,busy"}'::jsonb, 'jmdict'),
    ('ja', '肉', '肉', '{"kana": "にく", "jlpt": "N5", "jmdict_seq": 1463520, "meaning_en": "meat"}'::jsonb, 'jmdict'),
    ('ja', '西', '西邊', '{"kana": "にし", "jlpt": "N5", "jmdict_seq": 1380840, "meaning_en": "west"}'::jsonb, 'jmdict'),
    ('ja', '日曜日', '星期日', '{"kana": "にちようび", "jlpt": "N5", "jmdict_seq": 1464900, "meaning_en": "Sunday"}'::jsonb, 'jmdict'),
    ('ja', '荷物', '行李', '{"kana": "にもつ", "jlpt": "N5", "jmdict_seq": 1195430, "meaning_en": "luggage"}'::jsonb, 'jmdict'),
    ('ja', 'ニュース', '新聞', '{"kana": "ニュース", "jlpt": "N5", "jmdict_seq": 1091500, "meaning_en": "news"}'::jsonb, 'jmdict'),
    ('ja', '庭', '庭院', '{"kana": "にわ", "jlpt": "N5", "jmdict_seq": 1436130, "meaning_en": "garden"}'::jsonb, 'jmdict'),
    ('ja', '脱ぐ', '脫（衣服）', '{"kana": "ぬぐ", "jlpt": "N5", "jmdict_seq": 1416400, "meaning_en": "to take off clothes"}'::jsonb, 'jmdict'),
    ('ja', '温い', '溫（不夠熱）', '{"kana": "ぬるい", "jlpt": "N5", "jmdict_seq": 1183300, "meaning_en": "luke warm"}'::jsonb, 'jmdict'),
    ('ja', 'ネクタイ', '領帶', '{"kana": "ネクタイ", "jlpt": "N5", "jmdict_seq": 1092820, "meaning_en": "tie,necktie"}'::jsonb, 'jmdict'),
    ('ja', '猫', '貓', '{"kana": "ねこ", "jlpt": "N5", "jmdict_seq": 1467640, "meaning_en": "cat"}'::jsonb, 'jmdict'),
    ('ja', '寝る', '睡覺', '{"kana": "ねる", "jlpt": "N5", "jmdict_seq": 1360010, "meaning_en": "to go to bed,to sleep"}'::jsonb, 'jmdict'),
    ('ja', 'ノート', '筆記本', '{"kana": "ノート", "jlpt": "N5", "jmdict_seq": 1093450, "meaning_en": "notebook,exercise book"}'::jsonb, 'jmdict'),
    ('ja', '登る', '爬（山）', '{"kana": "のぼる", "jlpt": "N5", "jmdict_seq": 1352570, "meaning_en": "to climb"}'::jsonb, 'jmdict'),
    ('ja', '飲み物', '飲料', '{"kana": "のみもの", "jlpt": "N5", "jmdict_seq": 1600430, "meaning_en": "a drink"}'::jsonb, 'jmdict'),
    ('ja', '飲む', '喝', '{"kana": "のむ", "jlpt": "N5", "jmdict_seq": 1169870, "meaning_en": "to drink"}'::jsonb, 'jmdict'),
    ('ja', '乗る', '搭乘', '{"kana": "のる", "jlpt": "N5", "jmdict_seq": 1355120, "meaning_en": "to get on,to ride"}'::jsonb, 'jmdict'),
    ('ja', '歯', '牙齒', '{"kana": "は", "jlpt": "N5", "jmdict_seq": 1313000, "meaning_en": "tooth"}'::jsonb, 'jmdict'),
    ('ja', 'パーティー', '派對', '{"kana": "パーティー", "jlpt": "N5", "jmdict_seq": 1100760, "meaning_en": "party"}'::jsonb, 'jmdict'),
    ('ja', 'はい', '是/有', '{"kana": "はい", "jlpt": "N5", "jmdict_seq": 1010080, "meaning_en": "yes"}'::jsonb, 'jmdict'),
    ('ja', '灰皿', '菸灰缸', '{"kana": "はいざら", "jlpt": "N5", "jmdict_seq": 1201940, "meaning_en": "ashtray"}'::jsonb, 'jmdict'),
    ('ja', '入る', '進入', '{"kana": "はいる", "jlpt": "N5", "jmdict_seq": 1465590, "meaning_en": "to enter,to contain"}'::jsonb, 'jmdict'),
    ('ja', '葉書', '明信片', '{"kana": "はがき", "jlpt": "N5", "jmdict_seq": 1546590, "meaning_en": "postcard"}'::jsonb, 'jmdict'),
    ('ja', '履く', '穿（下身）', '{"kana": "はく", "jlpt": "N5", "jmdict_seq": 1607260, "meaning_en": "to wear,to put on trousers"}'::jsonb, 'jmdict'),
    ('ja', '箱', '箱子', '{"kana": "はこ", "jlpt": "N5", "jmdict_seq": 1585650, "meaning_en": "box"}'::jsonb, 'jmdict'),
    ('ja', '橋', '橋', '{"kana": "はし", "jlpt": "N5", "jmdict_seq": 1237410, "meaning_en": "bridge"}'::jsonb, 'jmdict'),
    ('ja', '箸', '筷子', '{"kana": "はし", "jlpt": "N5", "jmdict_seq": 1476410, "meaning_en": "chopsticks"}'::jsonb, 'jmdict'),
    ('ja', '始まる', '開始（自動）', '{"kana": "はじまる", "jlpt": "N5", "jmdict_seq": 1307500, "meaning_en": "to begin"}'::jsonb, 'jmdict'),
    ('ja', '初め', '一開始', '{"kana": "はじめ", "jlpt": "N5", "jmdict_seq": 1342540, "meaning_en": "beginning"}'::jsonb, 'jmdict'),
    ('ja', '始め', '開頭', '{"kana": "はじめ", "jlpt": "N5", "jmdict_seq": 1342540, "meaning_en": "beginning"}'::jsonb, 'jmdict'),
    ('ja', '初めて', '第一次', '{"kana": "はじめて", "jlpt": "N5", "jmdict_seq": 1342550, "meaning_en": "for the first time"}'::jsonb, 'jmdict'),
    ('ja', '走る', '跑', '{"kana": "はしる", "jlpt": "N5", "jmdict_seq": 1402540, "meaning_en": "to run"}'::jsonb, 'jmdict'),
    ('ja', 'バス', '公車', '{"kana": "バス", "jlpt": "N5", "jmdict_seq": 1098390, "meaning_en": "bus"}'::jsonb, 'jmdict'),
    ('ja', 'バター', '奶油', '{"kana": "バター", "jlpt": "N5", "jmdict_seq": 1098620, "meaning_en": "butter"}'::jsonb, 'jmdict'),
    ('ja', '二十歳', '二十歲', '{"kana": "はたち", "jlpt": "N5", "jmdict_seq": 1600790, "meaning_en": "20 years old,20th year"}'::jsonb, 'jmdict'),
    ('ja', '働く', '工作', '{"kana": "はたらく", "jlpt": "N5", "jmdict_seq": 1451150, "meaning_en": "to work"}'::jsonb, 'jmdict'),
    ('ja', '八', '八', '{"kana": "はち", "jlpt": "N5", "jmdict_seq": 1583090, "meaning_en": "eight"}'::jsonb, 'jmdict'),
    ('ja', '二十日', '二十號', '{"kana": "はつか", "jlpt": "N5", "jmdict_seq": 1600850, "meaning_en": "twenty days,twentieth"}'::jsonb, 'jmdict'),
    ('ja', '花', '花', '{"kana": "はな", "jlpt": "N5", "jmdict_seq": 1194500, "meaning_en": "flower"}'::jsonb, 'jmdict'),
    ('ja', '鼻', '鼻子', '{"kana": "はな", "jlpt": "N5", "jmdict_seq": 1486720, "meaning_en": "nose"}'::jsonb, 'jmdict'),
    ('ja', '話', '故事/話題', '{"kana": "はなし", "jlpt": "N5", "jmdict_seq": 1600900, "meaning_en": "talk,story"}'::jsonb, 'jmdict'),
    ('ja', '話す', '說話', '{"kana": "はなす", "jlpt": "N5", "jmdict_seq": 1562350, "meaning_en": "to speak"}'::jsonb, 'jmdict'),
    ('ja', '早い', '早', '{"kana": "はやい", "jlpt": "N5", "jmdict_seq": 1404975, "meaning_en": "early"}'::jsonb, 'jmdict'),
    ('ja', '速い', '快', '{"kana": "はやい", "jlpt": "N5", "jmdict_seq": 1404975, "meaning_en": "quick"}'::jsonb, 'jmdict'),
    ('ja', '春', '春天', '{"kana": "はる", "jlpt": "N5", "jmdict_seq": 1341000, "meaning_en": "spring"}'::jsonb, 'jmdict'),
    ('ja', '貼る', '貼', '{"kana": "はる", "jlpt": "N5", "jmdict_seq": 1427900, "meaning_en": "to stick"}'::jsonb, 'jmdict'),
    ('ja', '晴れ', '晴天', '{"kana": "はれ", "jlpt": "N5", "jmdict_seq": 1376460, "meaning_en": "clear weather"}'::jsonb, 'jmdict'),
    ('ja', '晴れる', '放晴', '{"kana": "はれる", "jlpt": "N5", "jmdict_seq": 1376470, "meaning_en": "to be sunny"}'::jsonb, 'jmdict'),
    ('ja', '半', '半', '{"kana": "はん", "jlpt": "N5", "jmdict_seq": 1478750, "meaning_en": "half"}'::jsonb, 'jmdict'),
    ('ja', '晩', '晚上', '{"kana": "ばん", "jlpt": "N5", "jmdict_seq": 1482110, "meaning_en": "evening"}'::jsonb, 'jmdict'),
    ('ja', 'パン', '麵包', '{"kana": "パン", "jlpt": "N5", "jmdict_seq": 1103090, "meaning_en": "bread"}'::jsonb, 'jmdict'),
    ('ja', 'ハンカチ', '手帕', '{"kana": "ハンカチ", "jlpt": "N5", "jmdict_seq": 1096420, "meaning_en": "handkerchief"}'::jsonb, 'jmdict'),
    ('ja', '番号', '號碼', '{"kana": "ばんごう", "jlpt": "N5", "jmdict_seq": 1482290, "meaning_en": "number"}'::jsonb, 'jmdict'),
    ('ja', '晩御飯', '晚餐', '{"kana": "ばんごはん", "jlpt": "N5", "jmdict_seq": 1601340, "meaning_en": "evening meal"}'::jsonb, 'jmdict'),
    ('ja', '半分', '一半', '{"kana": "はんぶん", "jlpt": "N5", "jmdict_seq": 1479890, "meaning_en": "half minute"}'::jsonb, 'jmdict'),
    ('ja', '東', '東邊', '{"kana": "ひがし", "jlpt": "N5", "jmdict_seq": 1447440, "meaning_en": "east"}'::jsonb, 'jmdict'),
    ('ja', '引く', '拉', '{"kana": "ひく", "jlpt": "N5", "jmdict_seq": 1169250, "meaning_en": "to pull"}'::jsonb, 'jmdict'),
    ('ja', '弾く', '彈（樂器）', '{"kana": "ひく", "jlpt": "N5", "jmdict_seq": 1419370, "meaning_en": "to play an instrument with strings, including piano"}'::jsonb, 'jmdict'),
    ('ja', '低い', '矮/低', '{"kana": "ひくい", "jlpt": "N5", "jmdict_seq": 1434180, "meaning_en": "short,low"}'::jsonb, 'jmdict'),
    ('ja', '飛行機', '飛機', '{"kana": "ひこうき", "jlpt": "N5", "jmdict_seq": 1485470, "meaning_en": "aeroplane"}'::jsonb, 'jmdict'),
    ('ja', '左', '左邊', '{"kana": "ひだり", "jlpt": "N5", "jmdict_seq": 1290800, "meaning_en": "left hand side"}'::jsonb, 'jmdict'),
    ('ja', '人', '人', '{"kana": "ひと", "jlpt": "N5", "jmdict_seq": 1580640, "meaning_en": "person"}'::jsonb, 'jmdict'),
    ('ja', '一つ', '一個', '{"kana": "ひとつ", "jlpt": "N5", "jmdict_seq": 1160820, "meaning_en": "one"}'::jsonb, 'jmdict'),
    ('ja', '一月', '一個月', '{"kana": "ひとつき", "jlpt": "N5", "jmdict_seq": 1162130, "meaning_en": "one month"}'::jsonb, 'jmdict'),
    ('ja', '一人', '一個人', '{"kana": "ひとり", "jlpt": "N5", "jmdict_seq": 1576150, "meaning_en": "one person"}'::jsonb, 'jmdict'),
    ('ja', '暇', '有空', '{"kana": "ひま", "jlpt": "N5", "jmdict_seq": 1577280, "meaning_en": "free time"}'::jsonb, 'jmdict'),
    ('ja', '百', '百', '{"kana": "ひゃく", "jlpt": "N5", "jmdict_seq": 1488000, "meaning_en": "hundred"}'::jsonb, 'jmdict'),
    ('ja', '病院', '醫院', '{"kana": "びょういん", "jlpt": "N5", "jmdict_seq": 1490220, "meaning_en": "hospital"}'::jsonb, 'jmdict'),
    ('ja', '病気', '生病', '{"kana": "びょうき", "jlpt": "N5", "jmdict_seq": 1490230, "meaning_en": "illness"}'::jsonb, 'jmdict'),
    ('ja', '昼', '中午', '{"kana": "ひる", "jlpt": "N5", "jmdict_seq": 1426250, "meaning_en": "noon, daytime"}'::jsonb, 'jmdict'),
    ('ja', '昼御飯', '午餐', '{"kana": "ひるごはん", "jlpt": "N5", "jmdict_seq": 1602340, "meaning_en": "midday meal"}'::jsonb, 'jmdict'),
    ('ja', '広い', '寬廣', '{"kana": "ひろい", "jlpt": "N5", "jmdict_seq": 1278410, "meaning_en": "spacious,wide"}'::jsonb, 'jmdict'),
    ('ja', 'フィルム', '底片', '{"kana": "フィルム", "jlpt": "N5", "jmdict_seq": 1109380, "meaning_en": "roll of film"}'::jsonb, 'jmdict'),
    ('ja', '封筒', '信封', '{"kana": "ふうとう", "jlpt": "N5", "jmdict_seq": 1499690, "meaning_en": "envelope"}'::jsonb, 'jmdict'),
    ('ja', 'プール', '游泳池', '{"kana": "プール", "jlpt": "N5", "jmdict_seq": 1115150, "meaning_en": "swimming pool"}'::jsonb, 'jmdict'),
    ('ja', 'フォーク', '叉子', '{"kana": "フォーク", "jlpt": "N5", "jmdict_seq": 1110110, "meaning_en": "fork"}'::jsonb, 'jmdict'),
    ('ja', '吹く', '吹', '{"kana": "ふく", "jlpt": "N5", "jmdict_seq": 1370760, "meaning_en": "to blow"}'::jsonb, 'jmdict'),
    ('ja', '服', '衣服', '{"kana": "ふく", "jlpt": "N5", "jmdict_seq": 1500940, "meaning_en": "clothes"}'::jsonb, 'jmdict'),
    ('ja', '二つ', '兩個', '{"kana": "ふたつ", "jlpt": "N5", "jmdict_seq": 1461160, "meaning_en": "two"}'::jsonb, 'jmdict'),
    ('ja', '豚肉', '豬肉', '{"kana": "ぶたにく", "jlpt": "N5", "jmdict_seq": 1457440, "meaning_en": "pork"}'::jsonb, 'jmdict'),
    ('ja', '二人', '兩個人', '{"kana": "ふたり", "jlpt": "N5", "jmdict_seq": 1582670, "meaning_en": "two people"}'::jsonb, 'jmdict'),
    ('ja', '二日', '二號', '{"kana": "ふつか", "jlpt": "N5", "jmdict_seq": 1462900, "meaning_en": "two days, second day of the month"}'::jsonb, 'jmdict'),
    ('ja', '太い', '粗', '{"kana": "ふとい", "jlpt": "N5", "jmdict_seq": 1408180, "meaning_en": "fat"}'::jsonb, 'jmdict'),
    ('ja', '冬', '冬天', '{"kana": "ふゆ", "jlpt": "N5", "jmdict_seq": 1446070, "meaning_en": "winter"}'::jsonb, 'jmdict'),
    ('ja', '降る', '下（雨/雪）', '{"kana": "ふる", "jlpt": "N5", "jmdict_seq": 1282790, "meaning_en": "to fall, e.g. rain or snow"}'::jsonb, 'jmdict'),
    ('ja', '古い', '舊', '{"kana": "ふるい", "jlpt": "N5", "jmdict_seq": 1265070, "meaning_en": "old (not used for people)"}'::jsonb, 'jmdict'),
    ('ja', '風呂', '浴室', '{"kana": "ふろ", "jlpt": "N5", "jmdict_seq": 1500100, "meaning_en": "bath"}'::jsonb, 'jmdict'),
    ('ja', '文章', '文章', '{"kana": "ぶんしょう", "jlpt": "N5", "jmdict_seq": 1505470, "meaning_en": "sentence,text"}'::jsonb, 'jmdict'),
    ('ja', 'ページ', '頁', '{"kana": "ページ", "jlpt": "N5", "jmdict_seq": 1120410, "meaning_en": "page"}'::jsonb, 'jmdict'),
    ('ja', '下手', '不擅長', '{"kana": "へた", "jlpt": "N5", "jmdict_seq": 1185200, "meaning_en": "unskillful"}'::jsonb, 'jmdict'),
    ('ja', 'ベッド', '床', '{"kana": "ベッド", "jlpt": "N5", "jmdict_seq": 1119650, "meaning_en": "bed"}'::jsonb, 'jmdict'),
    ('ja', 'ペット', '寵物', '{"kana": "ペット", "jlpt": "N5", "jmdict_seq": 1120990, "meaning_en": "pet"}'::jsonb, 'jmdict'),
    ('ja', '部屋', '房間', '{"kana": "へや", "jlpt": "N5", "jmdict_seq": 1499320, "meaning_en": "room"}'::jsonb, 'jmdict'),
    ('ja', '辺', '附近', '{"kana": "へん", "jlpt": "N5", "jmdict_seq": 1512070, "meaning_en": "area"}'::jsonb, 'jmdict'),
    ('ja', 'ペン', '筆', '{"kana": "ペン", "jlpt": "N5", "jmdict_seq": 1121380, "meaning_en": "pen"}'::jsonb, 'jmdict'),
    ('ja', '勉強', '讀書', '{"kana": "べんきょう", "jlpt": "N5", "jmdict_seq": 1512670, "meaning_en": "to study"}'::jsonb, 'jmdict'),
    ('ja', '便利', '方便', '{"kana": "べんり", "jlpt": "N5", "jmdict_seq": 1512610, "meaning_en": "useful, convenient"}'::jsonb, 'jmdict'),
    ('ja', '帽子', '帽子', '{"kana": "ぼうし", "jlpt": "N5", "jmdict_seq": 1519170, "meaning_en": "hat"}'::jsonb, 'jmdict'),
    ('ja', 'ボールペン', '原子筆', '{"kana": "ボールペン", "jlpt": "N5", "jmdict_seq": 1123590, "meaning_en": "ball-point pen"}'::jsonb, 'jmdict'),
    ('ja', 'ほか', '其他', '{"kana": "ほか", "jlpt": "N5", "jmdict_seq": 1203260, "meaning_en": "other, the rest"}'::jsonb, 'jmdict'),
    ('ja', 'ポケット', '口袋', '{"kana": "ポケット", "jlpt": "N5", "jmdict_seq": 1124970, "meaning_en": "pocket"}'::jsonb, 'jmdict'),
    ('ja', '欲しい', '想要', '{"kana": "ほしい", "jlpt": "N5", "jmdict_seq": 1547330, "meaning_en": "want"}'::jsonb, 'jmdict'),
    ('ja', 'ポスト', '郵筒', '{"kana": "ポスト", "jlpt": "N5", "jmdict_seq": 1125150, "meaning_en": "post"}'::jsonb, 'jmdict'),
    ('ja', '細い', '細', '{"kana": "ほそい", "jlpt": "N5", "jmdict_seq": 1295510, "meaning_en": "thin"}'::jsonb, 'jmdict'),
    ('ja', 'ボタン', '按鈕', '{"kana": "ボタン", "jlpt": "N5", "jmdict_seq": 1182880, "meaning_en": "button"}'::jsonb, 'jmdict'),
    ('ja', 'ホテル', '飯店', '{"kana": "ホテル", "jlpt": "N5", "jmdict_seq": 1122650, "meaning_en": "hotel"}'::jsonb, 'jmdict'),
    ('ja', '本', '書', '{"kana": "ほん", "jlpt": "N5", "jmdict_seq": 1522150, "meaning_en": "book"}'::jsonb, 'jmdict'),
    ('ja', '本棚', '書架', '{"kana": "ほんだな", "jlpt": "N5", "jmdict_seq": 1522980, "meaning_en": "bookshelves"}'::jsonb, 'jmdict'),
    ('ja', '本当', '真的', '{"kana": "ほんとう", "jlpt": "N5", "jmdict_seq": 1523060, "meaning_en": "truth"}'::jsonb, 'jmdict'),
    ('ja', '毎朝', '每天早上', '{"kana": "まいあさ", "jlpt": "N5", "jmdict_seq": 1524700, "meaning_en": "every morning"}'::jsonb, 'jmdict'),
    ('ja', '毎月', '每月（まいげつ）', '{"kana": "まいげつ", "jlpt": "N5", "jmdict_seq": 1584350, "meaning_en": "every month"}'::jsonb, 'jmdict'),
    ('ja', '毎月', '每月（まいつき）', '{"kana": "まいつき", "jlpt": "N5", "jmdict_seq": 1584350, "meaning_en": "every month"}'::jsonb, 'jmdict'),
    ('ja', '毎週', '每週', '{"kana": "まいしゅう", "jlpt": "N5", "jmdict_seq": 1524690, "meaning_en": "every week"}'::jsonb, 'jmdict'),
    ('ja', '毎日', '每天', '{"kana": "まいにち", "jlpt": "N5", "jmdict_seq": 1524720, "meaning_en": "every day"}'::jsonb, 'jmdict'),
    ('ja', '毎年', '每年（まいねん）', '{"kana": "まいねん", "jlpt": "N5", "jmdict_seq": 1584360, "meaning_en": "every year"}'::jsonb, 'jmdict'),
    ('ja', '毎年', '每年（まいとし）', '{"kana": "まいとし", "jlpt": "N5", "jmdict_seq": 1584360, "meaning_en": "every year"}'::jsonb, 'jmdict'),
    ('ja', '毎晩', '每晚', '{"kana": "まいばん", "jlpt": "N5", "jmdict_seq": 1524730, "meaning_en": "every night"}'::jsonb, 'jmdict'),
    ('ja', '前', '前面', '{"kana": "まえ", "jlpt": "N5", "jmdict_seq": 1392580, "meaning_en": "before"}'::jsonb, 'jmdict'),
    ('ja', '曲る', '轉彎', '{"kana": "まがる", "jlpt": "N5", "jmdict_seq": 1239730, "meaning_en": "to turn,to bend"}'::jsonb, 'jmdict'),
    ('ja', '不味い', '難吃', '{"kana": "まずい", "jlpt": "N5", "jmdict_seq": 1495000, "meaning_en": "unpleasant"}'::jsonb, 'jmdict'),
    ('ja', '又', '又/再', '{"kana": "また", "jlpt": "N5", "jmdict_seq": 1524930, "meaning_en": "again,and"}'::jsonb, 'jmdict'),
    ('ja', 'まだ', '還沒', '{"kana": "まだ", "jlpt": "N5", "jmdict_seq": 1527110, "meaning_en": "yet,still"}'::jsonb, 'jmdict'),
    ('ja', '町', '城鎮', '{"kana": "まち", "jlpt": "N5", "jmdict_seq": 1603990, "meaning_en": "town,city"}'::jsonb, 'jmdict'),
    ('ja', '待つ', '等', '{"kana": "まつ", "jlpt": "N5", "jmdict_seq": 1410590, "meaning_en": "to wait"}'::jsonb, 'jmdict'),
    ('ja', 'まっすぐ', '直直地', '{"kana": "まっすぐ", "jlpt": "N5", "jmdict_seq": 1580600, "meaning_en": "straight ahead,direct"}'::jsonb, 'jmdict'),
    ('ja', 'マッチ', '火柴', '{"kana": "マッチ", "jlpt": "N5", "jmdict_seq": 2784220, "meaning_en": "match"}'::jsonb, 'jmdict'),
    ('ja', '窓', '窗戶', '{"kana": "まど", "jlpt": "N5", "jmdict_seq": 1401400, "meaning_en": "window"}'::jsonb, 'jmdict'),
    ('ja', '丸い', '圓的（丸）', '{"kana": "まるい", "jlpt": "N5", "jmdict_seq": 1604230, "meaning_en": "round,circular"}'::jsonb, 'jmdict'),
    ('ja', '円い', '圓的（円）', '{"kana": "まるい", "jlpt": "N5", "jmdict_seq": 1604230, "meaning_en": "round,circular"}'::jsonb, 'jmdict'),
    ('ja', '万', '萬', '{"kana": "まん", "jlpt": "N5", "jmdict_seq": 1584460, "meaning_en": "ten thousand"}'::jsonb, 'jmdict'),
    ('ja', '万年筆', '鋼筆', '{"kana": "まんねんひつ", "jlpt": "N5", "jmdict_seq": 1526360, "meaning_en": "fountain pen"}'::jsonb, 'jmdict'),
    ('ja', '磨く', '刷（牙）/擦亮', '{"kana": "みがく", "jlpt": "N5", "jmdict_seq": 1523940, "meaning_en": "to brush teeth, to polish"}'::jsonb, 'jmdict'),
    ('ja', '右', '右邊', '{"kana": "みぎ", "jlpt": "N5", "jmdict_seq": 1171010, "meaning_en": "right side"}'::jsonb, 'jmdict'),
    ('ja', '短い', '短', '{"kana": "みじかい", "jlpt": "N5", "jmdict_seq": 1418620, "meaning_en": "short"}'::jsonb, 'jmdict'),
    ('ja', '水', '水', '{"kana": "みず", "jlpt": "N5", "jmdict_seq": 1371260, "meaning_en": "water"}'::jsonb, 'jmdict'),
    ('ja', '店', '店', '{"kana": "みせ", "jlpt": "N5", "jmdict_seq": 1582120, "meaning_en": "shop"}'::jsonb, 'jmdict'),
    ('ja', '見せる', '給看', '{"kana": "みせる", "jlpt": "N5", "jmdict_seq": 1259210, "meaning_en": "to show"}'::jsonb, 'jmdict'),
    ('ja', '道', '路', '{"kana": "みち", "jlpt": "N5", "jmdict_seq": 1454080, "meaning_en": "street"}'::jsonb, 'jmdict'),
    ('ja', '三日', '三號', '{"kana": "みっか", "jlpt": "N5", "jmdict_seq": 1301330, "meaning_en": "three days, third day of the month"}'::jsonb, 'jmdict'),
    ('ja', '三つ', '三個', '{"kana": "みっつ", "jlpt": "N5", "jmdict_seq": 1299740, "meaning_en": "three"}'::jsonb, 'jmdict'),
    ('ja', '緑', '綠色', '{"kana": "みどり", "jlpt": "N5", "jmdict_seq": 1555300, "meaning_en": "green"}'::jsonb, 'jmdict'),
    ('ja', '皆さん', '大家（禮貌）', '{"kana": "みなさん", "jlpt": "N5", "jmdict_seq": 1202170, "meaning_en": "everyone"}'::jsonb, 'jmdict'),
    ('ja', '南', '南邊', '{"kana": "みなみ", "jlpt": "N5", "jmdict_seq": 1459870, "meaning_en": "south"}'::jsonb, 'jmdict'),
    ('ja', '耳', '耳朵', '{"kana": "みみ", "jlpt": "N5", "jmdict_seq": 1317170, "meaning_en": "ear"}'::jsonb, 'jmdict'),
    ('ja', '見る', '看', '{"kana": "みる", "jlpt": "N5", "jmdict_seq": 1259290, "meaning_en": "to see, to watch"}'::jsonb, 'jmdict'),
    ('ja', '観る', '觀看', '{"kana": "みる", "jlpt": "N5", "jmdict_seq": 1259290, "meaning_en": "to see, to watch"}'::jsonb, 'jmdict'),
    ('ja', 'みんな', '大家', '{"kana": "みんな", "jlpt": "N5", "jmdict_seq": 1202150, "meaning_en": "everyone"}'::jsonb, 'jmdict'),
    ('ja', '六日', '六號', '{"kana": "むいか", "jlpt": "N5", "jmdict_seq": 1561470, "meaning_en": "six days, sixth day of the month"}'::jsonb, 'jmdict'),
    ('ja', '向こう', '對面', '{"kana": "むこう", "jlpt": "N5", "jmdict_seq": 1277140, "meaning_en": "over there"}'::jsonb, 'jmdict'),
    ('ja', '難しい', '難', '{"kana": "むずかしい", "jlpt": "N5", "jmdict_seq": 1460850, "meaning_en": "difficult"}'::jsonb, 'jmdict'),
    ('ja', '六つ', '六個', '{"kana": "むっつ", "jlpt": "N5", "jmdict_seq": 1585315, "meaning_en": "six"}'::jsonb, 'jmdict'),
    ('ja', '村', '村莊', '{"kana": "むら", "jlpt": "N5", "jmdict_seq": 1406820, "meaning_en": "village"}'::jsonb, 'jmdict'),
    ('ja', '目', '眼睛', '{"kana": "め", "jlpt": "N5", "jmdict_seq": 1604890, "meaning_en": "eye"}'::jsonb, 'jmdict'),
    ('ja', 'メートル', '公尺', '{"kana": "メートル", "jlpt": "N5", "jmdict_seq": 1132570, "meaning_en": "metre"}'::jsonb, 'jmdict'),
    ('ja', '眼鏡', '眼鏡', '{"kana": "めがね", "jlpt": "N5", "jmdict_seq": 1577670, "meaning_en": "glasses"}'::jsonb, 'jmdict'),
    ('ja', 'もう', '已經', '{"kana": "もう", "jlpt": "N5", "jmdict_seq": 1012480, "meaning_en": "already"}'::jsonb, 'jmdict'),
    ('ja', 'もう一度', '再一次', '{"kana": "もういちど", "jlpt": "N5", "jmdict_seq": 2005860, "meaning_en": "again"}'::jsonb, 'jmdict'),
    ('ja', '木曜日', '星期四', '{"kana": "もくようび", "jlpt": "N5", "jmdict_seq": 1534890, "meaning_en": "Thursday"}'::jsonb, 'jmdict'),
    ('ja', '持つ', '拿著', '{"kana": "もつ", "jlpt": "N5", "jmdict_seq": 1315720, "meaning_en": "to hold"}'::jsonb, 'jmdict'),
    ('ja', 'もっと', '更', '{"kana": "もっと", "jlpt": "N5", "jmdict_seq": 1012620, "meaning_en": "more"}'::jsonb, 'jmdict'),
    ('ja', '物', '東西', '{"kana": "もの", "jlpt": "N5", "jmdict_seq": 1502390, "meaning_en": "thing"}'::jsonb, 'jmdict'),
    ('ja', '門', '大門', '{"kana": "もん", "jlpt": "N5", "jmdict_seq": 1584800, "meaning_en": "gate"}'::jsonb, 'jmdict'),
    ('ja', '問題', '問題', '{"kana": "もんだい", "jlpt": "N5", "jmdict_seq": 1536010, "meaning_en": "problem"}'::jsonb, 'jmdict'),
    ('ja', '八百屋', '蔬果店', '{"kana": "やおや", "jlpt": "N5", "jmdict_seq": 1476960, "meaning_en": "greengrocer"}'::jsonb, 'jmdict'),
    ('ja', '野菜', '蔬菜', '{"kana": "やさい", "jlpt": "N5", "jmdict_seq": 1537370, "meaning_en": "vegetable"}'::jsonb, 'jmdict'),
    ('ja', '易しい', '簡單', '{"kana": "やさしい", "jlpt": "N5", "jmdict_seq": 1157000, "meaning_en": "easy, simple"}'::jsonb, 'jmdict'),
    ('ja', '安い', '便宜', '{"kana": "やすい", "jlpt": "N5", "jmdict_seq": 1153670, "meaning_en": "cheap"}'::jsonb, 'jmdict'),
    ('ja', '休み', '休假', '{"kana": "やすみ", "jlpt": "N5", "jmdict_seq": 1227500, "meaning_en": "rest,holiday"}'::jsonb, 'jmdict'),
    ('ja', '休む', '休息', '{"kana": "やすむ", "jlpt": "N5", "jmdict_seq": 1227560, "meaning_en": "to rest"}'::jsonb, 'jmdict'),
    ('ja', '八つ', '八個', '{"kana": "やっつ", "jlpt": "N5", "jmdict_seq": 1583095, "meaning_en": "eight"}'::jsonb, 'jmdict'),
    ('ja', '山', '山', '{"kana": "やま", "jlpt": "N5", "jmdict_seq": 1302680, "meaning_en": "mountain"}'::jsonb, 'jmdict'),
    ('ja', '遣る', '做', '{"kana": "やる", "jlpt": "N5", "jmdict_seq": 1012980, "meaning_en": "to do"}'::jsonb, 'jmdict'),
    ('ja', '夕方', '傍晚', '{"kana": "ゆうがた", "jlpt": "N5", "jmdict_seq": 1542790, "meaning_en": "evening"}'::jsonb, 'jmdict'),
    ('ja', '夕飯', '晚餐', '{"kana": "ゆうはん", "jlpt": "N5", "jmdict_seq": 1584910, "meaning_en": "dinner"}'::jsonb, 'jmdict'),
    ('ja', '郵便局', '郵局', '{"kana": "ゆうびんきょく", "jlpt": "N5", "jmdict_seq": 1542430, "meaning_en": "post office"}'::jsonb, 'jmdict'),
    ('ja', '昨夜', '昨晚', '{"kana": "ゆうべ", "jlpt": "N5", "jmdict_seq": 1542640, "meaning_en": "last night"}'::jsonb, 'jmdict'),
    ('ja', '有名', '有名', '{"kana": "ゆうめい", "jlpt": "N5", "jmdict_seq": 1541620, "meaning_en": "famous"}'::jsonb, 'jmdict'),
    ('ja', '雪', '雪', '{"kana": "ゆき", "jlpt": "N5", "jmdict_seq": 1386500, "meaning_en": "snow"}'::jsonb, 'jmdict'),
    ('ja', '行く', '去（ゆく）', '{"kana": "ゆく", "jlpt": "N5", "jmdict_seq": 1578850, "meaning_en": "to go"}'::jsonb, 'jmdict'),
    ('ja', 'ゆっくり', '慢慢', '{"kana": "ゆっくり", "jlpt": "N5", "jmdict_seq": 1013050, "meaning_en": "slowly"}'::jsonb, 'jmdict'),
    ('ja', '八日', '八號', '{"kana": "ようか", "jlpt": "N5", "jmdict_seq": 1476920, "meaning_en": "eight days, eighth day of the month"}'::jsonb, 'jmdict'),
    ('ja', '洋服', '西式衣服', '{"kana": "ようふく", "jlpt": "N5", "jmdict_seq": 1546020, "meaning_en": "western-style clothes"}'::jsonb, 'jmdict'),
    ('ja', '良く', '常常/好好地', '{"kana": "よく", "jlpt": "N5", "jmdict_seq": 1605870, "meaning_en": "often, well"}'::jsonb, 'jmdict'),
    ('ja', '横', '旁邊', '{"kana": "よこ", "jlpt": "N5", "jmdict_seq": 1180570, "meaning_en": "beside,side,width"}'::jsonb, 'jmdict'),
    ('ja', '四日', '四號', '{"kana": "よっか", "jlpt": "N5", "jmdict_seq": 1307320, "meaning_en": "four days, fouth day of the month"}'::jsonb, 'jmdict'),
    ('ja', '四つ', '四個', '{"kana": "よっつ", "jlpt": "N5", "jmdict_seq": 1307040, "meaning_en": "four"}'::jsonb, 'jmdict'),
    ('ja', '呼ぶ', '叫（人）', '{"kana": "よぶ", "jlpt": "N5", "jmdict_seq": 1266440, "meaning_en": "to call out,to invite"}'::jsonb, 'jmdict'),
    ('ja', '読む', '讀', '{"kana": "よむ", "jlpt": "N5", "jmdict_seq": 1456360, "meaning_en": "to read"}'::jsonb, 'jmdict'),
    ('ja', '夜', '晚上', '{"kana": "よる", "jlpt": "N5", "jmdict_seq": 1536350, "meaning_en": "evening,night"}'::jsonb, 'jmdict'),
    ('ja', '弱い', '弱', '{"kana": "よわい", "jlpt": "N5", "jmdict_seq": 1324520, "meaning_en": "weak"}'::jsonb, 'jmdict'),
    ('ja', '来月', '下個月', '{"kana": "らいげつ", "jlpt": "N5", "jmdict_seq": 1547900, "meaning_en": "next month"}'::jsonb, 'jmdict'),
    ('ja', '来週', '下週', '{"kana": "らいしゅう", "jlpt": "N5", "jmdict_seq": 1548010, "meaning_en": "next week"}'::jsonb, 'jmdict'),
    ('ja', '来年', '明年', '{"kana": "らいねん", "jlpt": "N5", "jmdict_seq": 1548220, "meaning_en": "next year"}'::jsonb, 'jmdict'),
    ('ja', 'ラジオ', '收音機', '{"kana": "ラジオ", "jlpt": "N5", "jmdict_seq": 1138860, "meaning_en": "radio"}'::jsonb, 'jmdict'),
    ('ja', 'ラジカセ', '收錄音機', '{"kana": "ラジカセ", "jlpt": "N5", "jmdict_seq": 1138960, "meaning_en": "radio cassette player"}'::jsonb, 'jmdict'),
    ('ja', 'ラジオカセット', '收錄音機（全名）', '{"kana": "ラジオカセット", "jlpt": "N5", "jmdict_seq": 1138900, "meaning_en": "radio cassette player"}'::jsonb, 'jmdict'),
    ('ja', '立派', '出色', '{"kana": "りっぱ", "jlpt": "N5", "jmdict_seq": 1551790, "meaning_en": "splendid"}'::jsonb, 'jmdict'),
    ('ja', '留学生', '留學生', '{"kana": "りゅうがくせい", "jlpt": "N5", "jmdict_seq": 1552750, "meaning_en": "overseas student"}'::jsonb, 'jmdict'),
    ('ja', '両親', '雙親', '{"kana": "りょうしん", "jlpt": "N5", "jmdict_seq": 1602710, "meaning_en": "both parents"}'::jsonb, 'jmdict'),
    ('ja', '料理', '料理', '{"kana": "りょうり", "jlpt": "N5", "jmdict_seq": 1554310, "meaning_en": "cuisine"}'::jsonb, 'jmdict'),
    ('ja', '旅行', '旅行', '{"kana": "りょこう", "jlpt": "N5", "jmdict_seq": 1553170, "meaning_en": "travel"}'::jsonb, 'jmdict'),
    ('ja', '零', '零（れい）', '{"kana": "れい", "jlpt": "N5", "jmdict_seq": 1557630, "meaning_en": "zero"}'::jsonb, 'jmdict'),
    ('ja', '冷蔵庫', '冰箱', '{"kana": "れいぞうこ", "jlpt": "N5", "jmdict_seq": 1557110, "meaning_en": "refrigerator"}'::jsonb, 'jmdict'),
    ('ja', 'レコード', '唱片', '{"kana": "レコード", "jlpt": "N5", "jmdict_seq": 1144940, "meaning_en": "record"}'::jsonb, 'jmdict'),
    ('ja', 'レストラン', '餐廳', '{"kana": "レストラン", "jlpt": "N5", "jmdict_seq": 1145310, "meaning_en": "restaurant"}'::jsonb, 'jmdict'),
    ('ja', '練習', '練習', '{"kana": "れんしゅう", "jlpt": "N5", "jmdict_seq": 1559160, "meaning_en": "to practice"}'::jsonb, 'jmdict'),
    ('ja', '廊下', '走廊', '{"kana": "ろうか", "jlpt": "N5", "jmdict_seq": 1560670, "meaning_en": "corridor"}'::jsonb, 'jmdict'),
    ('ja', '六', '六', '{"kana": "ろく", "jlpt": "N5", "jmdict_seq": 1585310, "meaning_en": "six"}'::jsonb, 'jmdict'),
    ('ja', 'ワイシャツ', '白襯衫', '{"kana": "ワイシャツ", "jlpt": "N5", "jmdict_seq": 1148640, "meaning_en": "business shirt"}'::jsonb, 'jmdict'),
    ('ja', '若い', '年輕', '{"kana": "わかい", "jlpt": "N5", "jmdict_seq": 1324300, "meaning_en": "young"}'::jsonb, 'jmdict'),
    ('ja', '分かる', '懂', '{"kana": "わかる", "jlpt": "N5", "jmdict_seq": 1606560, "meaning_en": "to be understood"}'::jsonb, 'jmdict'),
    ('ja', '忘れる', '忘記', '{"kana": "わすれる", "jlpt": "N5", "jmdict_seq": 1519210, "meaning_en": "to forget"}'::jsonb, 'jmdict'),
    ('ja', '私', '我（謙稱）', '{"kana": "わたくし", "jlpt": "N5", "jmdict_seq": 2842390, "meaning_en": "(humble) I,myself"}'::jsonb, 'jmdict'),
    ('ja', '私', '我', '{"kana": "わたし", "jlpt": "N5", "jmdict_seq": 1311110, "meaning_en": "I,myself"}'::jsonb, 'jmdict'),
    ('ja', '渡す', '交給', '{"kana": "わたす", "jlpt": "N5", "jmdict_seq": 1444610, "meaning_en": "to hand over"}'::jsonb, 'jmdict'),
    ('ja', '渡る', '過（馬路）', '{"kana": "わたる", "jlpt": "N5", "jmdict_seq": 1444680, "meaning_en": "to go across"}'::jsonb, 'jmdict'),
    ('ja', '悪い', '不好/壞', '{"kana": "わるい", "jlpt": "N5", "jmdict_seq": 1151260, "meaning_en": "bad"}'::jsonb, 'jmdict'),
    ('ja', 'より', '比起', '{"kana": "より", "jlpt": "N5", "jmdict_seq": 1013190, "meaning_en": "Used for comparison."}'::jsonb, 'jmdict'),
    ('ja', '方', '方向（比較用）', '{"kana": "ほう", "jlpt": "N5", "jmdict_seq": 1516930, "meaning_en": "Used for comparison."}'::jsonb, 'jmdict')
  returning id, lemma
)
insert into shrine_words (shrine_id, word_id, position)
select
  (select id from shrines where slug = 'meiji'),
  nw.id,
  row_number() over (order by nw.lemma)
from new_words nw;
