-- 006_n4_words_yasaka
-- N4 單字匯入：八坂神社（CSV 行 2-321，共 320 字）
-- 資料源：stephenmk/yomitan-jlpt-vocab (CC-BY, Jonathan Waller / Tanos)
-- 中文翻譯：Claude（學生友善口語風格）

with new_words as (
  insert into words (lang_code, lemma, meaning_zh, meta, source) values
    ('ja', 'あ', '啊', '{"kana": "あ", "jlpt": "N4", "jmdict_seq": 2394370, "meaning_en": "Ah"}'::jsonb, 'jmdict'),
    ('ja', 'ああ', '那樣', '{"kana": "ああ", "jlpt": "N4", "jmdict_seq": 2085080, "meaning_en": "like that"}'::jsonb, 'jmdict'),
    ('ja', 'あいさつ', '打招呼', '{"kana": "あいさつ", "jlpt": "N4", "jmdict_seq": 1151120, "meaning_en": "to greet"}'::jsonb, 'jmdict'),
    ('ja', '間', '之間', '{"kana": "あいだ", "jlpt": "N4", "jmdict_seq": 1215230, "meaning_en": "a space"}'::jsonb, 'jmdict'),
    ('ja', '合う', '適合', '{"kana": "あう", "jlpt": "N4", "jmdict_seq": 1284430, "meaning_en": "to match"}'::jsonb, 'jmdict'),
    ('ja', 'あかちゃん', '小寶寶', '{"kana": "あかちゃん", "jlpt": "N4", "jmdict_seq": 1383260, "meaning_en": "infant"}'::jsonb, 'jmdict'),
    ('ja', '上る', '上升', '{"kana": "あがる", "jlpt": "N4", "jmdict_seq": 1352290, "meaning_en": "to rise"}'::jsonb, 'jmdict'),
    ('ja', '赤ん坊', '嬰兒', '{"kana": "あかんぼう", "jlpt": "N4", "jmdict_seq": 1383310, "meaning_en": "baby"}'::jsonb, 'jmdict'),
    ('ja', '空く', '空出來', '{"kana": "あく", "jlpt": "N4", "jmdict_seq": 1586270, "meaning_en": "to open, to become empty"}'::jsonb, 'jmdict'),
    ('ja', 'アクセサリー', '飾品', '{"kana": "アクセサリー", "jlpt": "N4", "jmdict_seq": 1015220, "meaning_en": "accessory"}'::jsonb, 'jmdict'),
    ('ja', 'あげる', '給', '{"kana": "あげる", "jlpt": "N4", "jmdict_seq": 1352320, "meaning_en": "to give"}'::jsonb, 'jmdict'),
    ('ja', '浅い', '淺', '{"kana": "あさい", "jlpt": "N4", "jmdict_seq": 1390800, "meaning_en": "shallow,superficial"}'::jsonb, 'jmdict'),
    ('ja', '味', '味道', '{"kana": "あじ", "jlpt": "N4", "jmdict_seq": 1526960, "meaning_en": "flavour"}'::jsonb, 'jmdict'),
    ('ja', 'アジア', '亞洲', '{"kana": "アジア", "jlpt": "N4", "jmdict_seq": 1015840, "meaning_en": "Asia"}'::jsonb, 'jmdict'),
    ('ja', '明日', '明天', '{"kana": "あす", "jlpt": "N4", "jmdict_seq": 1584660, "meaning_en": "tomorrow"}'::jsonb, 'jmdict'),
    ('ja', '遊び', '玩樂', '{"kana": "あそび", "jlpt": "N4", "jmdict_seq": 1542070, "meaning_en": "play"}'::jsonb, 'jmdict'),
    ('ja', '集る', '聚集（自動）', '{"kana": "あつまる", "jlpt": "N4", "jmdict_seq": 1333550, "meaning_en": "to gather"}'::jsonb, 'jmdict'),
    ('ja', '集める', '收集（他動）', '{"kana": "あつめる", "jlpt": "N4", "jmdict_seq": 1333560, "meaning_en": "to collect something"}'::jsonb, 'jmdict'),
    ('ja', 'アナウンサー', '播報員', '{"kana": "アナウンサー", "jlpt": "N4", "jmdict_seq": 1017330, "meaning_en": "announcer"}'::jsonb, 'jmdict'),
    ('ja', 'アフリカ', '非洲', '{"kana": "アフリカ", "jlpt": "N4", "jmdict_seq": 1929050, "meaning_en": "Africa"}'::jsonb, 'jmdict'),
    ('ja', 'アメリカ', '美國', '{"kana": "アメリカ", "jlpt": "N4", "jmdict_seq": 1149830, "meaning_en": "America"}'::jsonb, 'jmdict'),
    ('ja', '謝る', '道歉', '{"kana": "あやまる", "jlpt": "N4", "jmdict_seq": 1323010, "meaning_en": "to apologize"}'::jsonb, 'jmdict'),
    ('ja', 'アルコール', '酒精', '{"kana": "アルコール", "jlpt": "N4", "jmdict_seq": 1019280, "meaning_en": "alcohol"}'::jsonb, 'jmdict'),
    ('ja', 'アルバイト', '打工', '{"kana": "アルバイト", "jlpt": "N4", "jmdict_seq": 1019420, "meaning_en": "part-time job"}'::jsonb, 'jmdict'),
    ('ja', '安心', '放心', '{"kana": "あんしん", "jlpt": "N4", "jmdict_seq": 1153890, "meaning_en": "relief"}'::jsonb, 'jmdict'),
    ('ja', '安全', '安全', '{"kana": "あんぜん", "jlpt": "N4", "jmdict_seq": 1153930, "meaning_en": "safety"}'::jsonb, 'jmdict'),
    ('ja', 'あんな', '那樣的', '{"kana": "あんな", "jlpt": "N4", "jmdict_seq": 1000590, "meaning_en": "such"}'::jsonb, 'jmdict'),
    ('ja', '案内', '帶路', '{"kana": "あんない", "jlpt": "N4", "jmdict_seq": 1154860, "meaning_en": "to guide"}'::jsonb, 'jmdict'),
    ('ja', '以下', '以下', '{"kana": "いか", "jlpt": "N4", "jmdict_seq": 1155060, "meaning_en": "less than"}'::jsonb, 'jmdict'),
    ('ja', '以外', '除了...之外', '{"kana": "いがい", "jlpt": "N4", "jmdict_seq": 1155090, "meaning_en": "with the exception of"}'::jsonb, 'jmdict'),
    ('ja', '医学', '醫學', '{"kana": "いがく", "jlpt": "N4", "jmdict_seq": 1159810, "meaning_en": "medical science"}'::jsonb, 'jmdict'),
    ('ja', '生きる', '活著', '{"kana": "いきる", "jlpt": "N4", "jmdict_seq": 1378520, "meaning_en": "to live"}'::jsonb, 'jmdict'),
    ('ja', '意見', '意見', '{"kana": "いけん", "jlpt": "N4", "jmdict_seq": 1156530, "meaning_en": "opinion"}'::jsonb, 'jmdict'),
    ('ja', '石', '石頭', '{"kana": "いし", "jlpt": "N4", "jmdict_seq": 1382440, "meaning_en": "stone"}'::jsonb, 'jmdict'),
    ('ja', 'いじめる', '欺負', '{"kana": "いじめる", "jlpt": "N4", "jmdict_seq": 1195140, "meaning_en": "to tease"}'::jsonb, 'jmdict'),
    ('ja', '以上', '以上', '{"kana": "いじょう", "jlpt": "N4", "jmdict_seq": 1155120, "meaning_en": "more than,this is all"}'::jsonb, 'jmdict'),
    ('ja', '急ぐ', '趕', '{"kana": "いそぐ", "jlpt": "N4", "jmdict_seq": 1228650, "meaning_en": "to hurry"}'::jsonb, 'jmdict'),
    ('ja', '致す', '做（謙讓）', '{"kana": "いたす", "jlpt": "N4", "jmdict_seq": 1421900, "meaning_en": "(humble) to do"}'::jsonb, 'jmdict'),
    ('ja', 'いただく', '收下（謙讓）', '{"kana": "いただく", "jlpt": "N4", "jmdict_seq": 1587290, "meaning_en": "(humble) to receive"}'::jsonb, 'jmdict'),
    ('ja', '一度', '一次', '{"kana": "いちど", "jlpt": "N4", "jmdict_seq": 1576250, "meaning_en": "once"}'::jsonb, 'jmdict'),
    ('ja', '一生懸命', '拼命', '{"kana": "いっしょうけんめい", "jlpt": "N4", "jmdict_seq": 1164010, "meaning_en": "with utmost effort"}'::jsonb, 'jmdict'),
    ('ja', '一杯', '滿滿', '{"kana": "いっぱい", "jlpt": "N4", "jmdict_seq": 1165670, "meaning_en": "full"}'::jsonb, 'jmdict'),
    ('ja', '糸', '線', '{"kana": "いと", "jlpt": "N4", "jmdict_seq": 1311450, "meaning_en": "thread"}'::jsonb, 'jmdict'),
    ('ja', '以内', '以內', '{"kana": "いない", "jlpt": "N4", "jmdict_seq": 1155180, "meaning_en": "within"}'::jsonb, 'jmdict'),
    ('ja', '田舎', '鄉下', '{"kana": "いなか", "jlpt": "N4", "jmdict_seq": 1442750, "meaning_en": "countryside"}'::jsonb, 'jmdict'),
    ('ja', '祈る', '祈禱', '{"kana": "いのる", "jlpt": "N4", "jmdict_seq": 1222770, "meaning_en": "to pray"}'::jsonb, 'jmdict'),
    ('ja', 'いらっしゃる', '在/來/去（敬語）', '{"kana": "いらっしゃる", "jlpt": "N4", "jmdict_seq": 1000940, "meaning_en": "(respectful) to be,to come or to go"}'::jsonb, 'jmdict'),
    ('ja', '植える', '種', '{"kana": "うえる", "jlpt": "N4", "jmdict_seq": 1357250, "meaning_en": "to plant,to grow"}'::jsonb, 'jmdict'),
    ('ja', '伺う', '拜訪（謙讓）', '{"kana": "うかがう", "jlpt": "N4", "jmdict_seq": 1305700, "meaning_en": "to visit"}'::jsonb, 'jmdict'),
    ('ja', '受付', '櫃台', '{"kana": "うけつけ", "jlpt": "N4", "jmdict_seq": 1588060, "meaning_en": "receipt"}'::jsonb, 'jmdict'),
    ('ja', '受ける', '接受', '{"kana": "うける", "jlpt": "N4", "jmdict_seq": 1329590, "meaning_en": "to take a lesson or test"}'::jsonb, 'jmdict'),
    ('ja', '動く', '動', '{"kana": "うごく", "jlpt": "N4", "jmdict_seq": 1451210, "meaning_en": "to move"}'::jsonb, 'jmdict'),
    ('ja', '嘘', '謊話', '{"kana": "うそ", "jlpt": "N4", "jmdict_seq": 1172400, "meaning_en": "a lie"}'::jsonb, 'jmdict'),
    ('ja', '内', '裡面', '{"kana": "うち", "jlpt": "N4", "jmdict_seq": 1457730, "meaning_en": "within"}'::jsonb, 'jmdict'),
    ('ja', '打つ', '打', '{"kana": "うつ", "jlpt": "N4", "jmdict_seq": 1408810, "meaning_en": "to hit"}'::jsonb, 'jmdict'),
    ('ja', '美しい', '美麗', '{"kana": "うつくしい", "jlpt": "N4", "jmdict_seq": 1486360, "meaning_en": "beautiful"}'::jsonb, 'jmdict'),
    ('ja', '写す', '抄寫/拍照', '{"kana": "うつす", "jlpt": "N4", "jmdict_seq": 1588320, "meaning_en": "to copy or photograph"}'::jsonb, 'jmdict'),
    ('ja', '移る', '搬/轉移', '{"kana": "うつる", "jlpt": "N4", "jmdict_seq": 1158210, "meaning_en": "to move house or transfer"}'::jsonb, 'jmdict'),
    ('ja', '腕', '手臂', '{"kana": "うで", "jlpt": "N4", "jmdict_seq": 1562850, "meaning_en": "arm"}'::jsonb, 'jmdict'),
    ('ja', '上手い', '好吃/拿手', '{"kana": "うまい", "jlpt": "N4", "jmdict_seq": 1310460, "meaning_en": "delicious"}'::jsonb, 'jmdict'),
    ('ja', '裏', '背面', '{"kana": "うら", "jlpt": "N4", "jmdict_seq": 1550190, "meaning_en": "reverse side"}'::jsonb, 'jmdict'),
    ('ja', '売り場', '賣場', '{"kana": "うりば", "jlpt": "N4", "jmdict_seq": 1588550, "meaning_en": "place where things are sold"}'::jsonb, 'jmdict'),
    ('ja', 'うれしい', '開心', '{"kana": "うれしい", "jlpt": "N4", "jmdict_seq": 1219510, "meaning_en": "glad"}'::jsonb, 'jmdict'),
    ('ja', 'うん', '嗯（口語）', '{"kana": "うん", "jlpt": "N4", "jmdict_seq": 1001090, "meaning_en": "(informal) yes"}'::jsonb, 'jmdict'),
    ('ja', '運転', '開車', '{"kana": "うんてん", "jlpt": "N4", "jmdict_seq": 1172830, "meaning_en": "to drive"}'::jsonb, 'jmdict'),
    ('ja', '運転手', '司機', '{"kana": "うんてんしゅ", "jlpt": "N4", "jmdict_seq": 1172870, "meaning_en": "driver"}'::jsonb, 'jmdict'),
    ('ja', '運動', '運動', '{"kana": "うんどう", "jlpt": "N4", "jmdict_seq": 1172910, "meaning_en": "to exercise"}'::jsonb, 'jmdict'),
    ('ja', 'エスカレーター', '電扶梯', '{"kana": "エスカレーター", "jlpt": "N4", "jmdict_seq": 1028580, "meaning_en": "escalator"}'::jsonb, 'jmdict'),
    ('ja', '枝', '樹枝', '{"kana": "えだ", "jlpt": "N4", "jmdict_seq": 1310530, "meaning_en": "branch, twig"}'::jsonb, 'jmdict'),
    ('ja', '選ぶ', '選', '{"kana": "えらぶ", "jlpt": "N4", "jmdict_seq": 1588730, "meaning_en": "to choose"}'::jsonb, 'jmdict'),
    ('ja', '遠慮', '客氣', '{"kana": "えんりょ", "jlpt": "N4", "jmdict_seq": 1178450, "meaning_en": "to be reserved, to be restrained"}'::jsonb, 'jmdict'),
    ('ja', 'おいでになる', '在/來/去（敬語）', '{"kana": "おいでになる", "jlpt": "N4", "jmdict_seq": 1001180, "meaning_en": "(respectful) to be"}'::jsonb, 'jmdict'),
    ('ja', 'お祝い', '祝賀', '{"kana": "おいわい", "jlpt": "N4", "jmdict_seq": 1612770, "meaning_en": "congratulation"}'::jsonb, 'jmdict'),
    ('ja', 'オートバイ', '機車', '{"kana": "オートバイ", "jlpt": "N4", "jmdict_seq": 1032030, "meaning_en": "motorcycle"}'::jsonb, 'jmdict'),
    ('ja', 'おかげ', '託...的福', '{"kana": "おかげ", "jlpt": "N4", "jmdict_seq": 1001640, "meaning_en": "owing to"}'::jsonb, 'jmdict'),
    ('ja', 'おかしい', '奇怪/好笑', '{"kana": "おかしい", "jlpt": "N4", "jmdict_seq": 1190860, "meaning_en": "strange or funny"}'::jsonb, 'jmdict'),
    ('ja', '億', '億', '{"kana": "おく", "jlpt": "N4", "jmdict_seq": 1182620, "meaning_en": "one hundred million"}'::jsonb, 'jmdict'),
    ('ja', '屋上', '頂樓', '{"kana": "おくじょう", "jlpt": "N4", "jmdict_seq": 1182710, "meaning_en": "rooftop"}'::jsonb, 'jmdict'),
    ('ja', '贈り物', '禮物', '{"kana": "おくりもの", "jlpt": "N4", "jmdict_seq": 1589030, "meaning_en": "gift"}'::jsonb, 'jmdict'),
    ('ja', '送る', '送', '{"kana": "おくる", "jlpt": "N4", "jmdict_seq": 1402730, "meaning_en": "to send"}'::jsonb, 'jmdict'),
    ('ja', '遅れる', '遲到', '{"kana": "おくれる", "jlpt": "N4", "jmdict_seq": 1589040, "meaning_en": "to be late"}'::jsonb, 'jmdict'),
    ('ja', '起す', '叫醒', '{"kana": "おこす", "jlpt": "N4", "jmdict_seq": 1223660, "meaning_en": "to wake"}'::jsonb, 'jmdict'),
    ('ja', '行う', '舉行', '{"kana": "おこなう", "jlpt": "N4", "jmdict_seq": 1589060, "meaning_en": "to do"}'::jsonb, 'jmdict'),
    ('ja', '怒る', '生氣', '{"kana": "おこる", "jlpt": "N4", "jmdict_seq": 1445690, "meaning_en": "to get angry,to be angry"}'::jsonb, 'jmdict'),
    ('ja', '押し入れ', '壁櫥', '{"kana": "おしいれ", "jlpt": "N4", "jmdict_seq": 1589110, "meaning_en": "closet"}'::jsonb, 'jmdict'),
    ('ja', 'お嬢さん', '小姐', '{"kana": "おじょうさん", "jlpt": "N4", "jmdict_seq": 1002170, "meaning_en": "young lady"}'::jsonb, 'jmdict'),
    ('ja', 'お宅', '府上', '{"kana": "おたく", "jlpt": "N4", "jmdict_seq": 1002400, "meaning_en": "(polite) your house"}'::jsonb, 'jmdict'),
    ('ja', '落る', '掉落', '{"kana": "おちる", "jlpt": "N4", "jmdict_seq": 1548550, "meaning_en": "to fall or drop"}'::jsonb, 'jmdict'),
    ('ja', 'おっしゃる', '說（敬語）', '{"kana": "おっしゃる", "jlpt": "N4", "jmdict_seq": 1238840, "meaning_en": "(respectful) to say"}'::jsonb, 'jmdict'),
    ('ja', '夫', '丈夫', '{"kana": "おっと", "jlpt": "N4", "jmdict_seq": 1496480, "meaning_en": "husband"}'::jsonb, 'jmdict'),
    ('ja', 'おつり', '找錢', '{"kana": "おつり", "jlpt": "N4", "jmdict_seq": 1270550, "meaning_en": "change from purchase, balance"}'::jsonb, 'jmdict'),
    ('ja', '音', '聲音', '{"kana": "おと", "jlpt": "N4", "jmdict_seq": 1576900, "meaning_en": "sound,note"}'::jsonb, 'jmdict'),
    ('ja', '落す', '弄掉', '{"kana": "おとす", "jlpt": "N4", "jmdict_seq": 1589260, "meaning_en": "to drop"}'::jsonb, 'jmdict'),
    ('ja', '踊り', '舞蹈', '{"kana": "おどり", "jlpt": "N4", "jmdict_seq": 1546880, "meaning_en": "a dance"}'::jsonb, 'jmdict'),
    ('ja', '踊る', '跳舞', '{"kana": "おどる", "jlpt": "N4", "jmdict_seq": 1538440, "meaning_en": "to dance"}'::jsonb, 'jmdict'),
    ('ja', '驚く', '吃驚', '{"kana": "おどろく", "jlpt": "N4", "jmdict_seq": 1238680, "meaning_en": "to be surprised"}'::jsonb, 'jmdict'),
    ('ja', 'お祭り', '祭典', '{"kana": "おまつり", "jlpt": "N4", "jmdict_seq": 1604135, "meaning_en": "festival"}'::jsonb, 'jmdict'),
    ('ja', 'お見舞い', '探病', '{"kana": "おみまい", "jlpt": "N4", "jmdict_seq": 1001870, "meaning_en": "calling on someone who is ill,enquiry"}'::jsonb, 'jmdict'),
    ('ja', 'お土産', '伴手禮', '{"kana": "おみやげ", "jlpt": "N4", "jmdict_seq": 1002500, "meaning_en": "souvenir"}'::jsonb, 'jmdict'),
    ('ja', '思い出す', '想起', '{"kana": "おもいだす", "jlpt": "N4", "jmdict_seq": 1309260, "meaning_en": "to remember"}'::jsonb, 'jmdict'),
    ('ja', '思う', '想/覺得', '{"kana": "おもう", "jlpt": "N4", "jmdict_seq": 1589350, "meaning_en": "to think,to feel"}'::jsonb, 'jmdict'),
    ('ja', 'おもちゃ', '玩具', '{"kana": "おもちゃ", "jlpt": "N4", "jmdict_seq": 1217070, "meaning_en": "toy"}'::jsonb, 'jmdict'),
    ('ja', '表', '正面', '{"kana": "おもて", "jlpt": "N4", "jmdict_seq": 1489340, "meaning_en": "the front"}'::jsonb, 'jmdict'),
    ('ja', '親', '父母', '{"kana": "おや", "jlpt": "N4", "jmdict_seq": 1365040, "meaning_en": "parents"}'::jsonb, 'jmdict'),
    ('ja', '下りる', '下來', '{"kana": "おりる", "jlpt": "N4", "jmdict_seq": 1589500, "meaning_en": "to get off"}'::jsonb, 'jmdict'),
    ('ja', '折る', '折', '{"kana": "おる", "jlpt": "N4", "jmdict_seq": 1385910, "meaning_en": "to break or to fold"}'::jsonb, 'jmdict'),
    ('ja', 'お礼', '謝禮', '{"kana": "おれい", "jlpt": "N4", "jmdict_seq": 1270810, "meaning_en": "expression of gratitude"}'::jsonb, 'jmdict'),
    ('ja', '折れる', '斷掉', '{"kana": "おれる", "jlpt": "N4", "jmdict_seq": 1385920, "meaning_en": "to break or be folded"}'::jsonb, 'jmdict'),
    ('ja', '終わり', '結束', '{"kana": "おわり", "jlpt": "N4", "jmdict_seq": 1589590, "meaning_en": "the end"}'::jsonb, 'jmdict'),
    ('ja', 'カーテン', '窗簾', '{"kana": "カーテン", "jlpt": "N4", "jmdict_seq": 1036290, "meaning_en": "curtain"}'::jsonb, 'jmdict'),
    ('ja', '海岸', '海岸', '{"kana": "かいがん", "jlpt": "N4", "jmdict_seq": 1201280, "meaning_en": "coast"}'::jsonb, 'jmdict'),
    ('ja', '会議', '會議', '{"kana": "かいぎ", "jlpt": "N4", "jmdict_seq": 1198360, "meaning_en": "meeting"}'::jsonb, 'jmdict'),
    ('ja', '会議室', '會議室', '{"kana": "かいぎしつ", "jlpt": "N4", "jmdict_seq": 1198380, "meaning_en": "meeting room"}'::jsonb, 'jmdict'),
    ('ja', '会場', '會場', '{"kana": "かいじょう", "jlpt": "N4", "jmdict_seq": 1198660, "meaning_en": "assembly hall or meeting place"}'::jsonb, 'jmdict'),
    ('ja', '会話', '對話', '{"kana": "かいわ", "jlpt": "N4", "jmdict_seq": 1198880, "meaning_en": "conversation"}'::jsonb, 'jmdict'),
    ('ja', '帰り', '回程', '{"kana": "かえり", "jlpt": "N4", "jmdict_seq": 1221250, "meaning_en": "return"}'::jsonb, 'jmdict'),
    ('ja', '変える', '改變（他動）', '{"kana": "かえる", "jlpt": "N4", "jmdict_seq": 1510650, "meaning_en": "to change"}'::jsonb, 'jmdict'),
    ('ja', '科学', '科學', '{"kana": "かがく", "jlpt": "N4", "jmdict_seq": 1192700, "meaning_en": "science"}'::jsonb, 'jmdict'),
    ('ja', '鏡', '鏡子', '{"kana": "かがみ", "jlpt": "N4", "jmdict_seq": 1238550, "meaning_en": "mirror"}'::jsonb, 'jmdict'),
    ('ja', '飾る', '裝飾', '{"kana": "かざる", "jlpt": "N4", "jmdict_seq": 1357210, "meaning_en": "to decorate"}'::jsonb, 'jmdict'),
    ('ja', '火事', '火災', '{"kana": "かじ", "jlpt": "N4", "jmdict_seq": 1193950, "meaning_en": "fire"}'::jsonb, 'jmdict'),
    ('ja', 'ガス', '瓦斯', '{"kana": "ガス", "jlpt": "N4", "jmdict_seq": 1040060, "meaning_en": "petrol"}'::jsonb, 'jmdict'),
    ('ja', 'ガソリン', '汽油', '{"kana": "ガソリン", "jlpt": "N4", "jmdict_seq": 1040250, "meaning_en": "petrol"}'::jsonb, 'jmdict'),
    ('ja', 'ガソリンスタンド', '加油站', '{"kana": "ガソリンスタンド", "jlpt": "N4", "jmdict_seq": 1040260, "meaning_en": "petrol station"}'::jsonb, 'jmdict'),
    ('ja', '堅い', '硬（堅）', '{"kana": "かたい", "jlpt": "N4", "jmdict_seq": 1257110, "meaning_en": "hard"}'::jsonb, 'jmdict'),
    ('ja', '硬い', '硬（硬）', '{"kana": "かたい", "jlpt": "N4", "jmdict_seq": 1257110, "meaning_en": "hard"}'::jsonb, 'jmdict'),
    ('ja', '固い', '硬（固）', '{"kana": "かたい", "jlpt": "N4", "jmdict_seq": 1257110, "meaning_en": "hard"}'::jsonb, 'jmdict'),
    ('ja', '形', '形狀', '{"kana": "かたち", "jlpt": "N4", "jmdict_seq": 1250220, "meaning_en": "shape"}'::jsonb, 'jmdict'),
    ('ja', '片付ける', '收拾', '{"kana": "かたづける", "jlpt": "N4", "jmdict_seq": 1511790, "meaning_en": "to tidy up"}'::jsonb, 'jmdict'),
    ('ja', '課長', '課長', '{"kana": "かちょう", "jlpt": "N4", "jmdict_seq": 1195840, "meaning_en": "section manager"}'::jsonb, 'jmdict'),
    ('ja', '勝つ', '贏', '{"kana": "かつ", "jlpt": "N4", "jmdict_seq": 1346150, "meaning_en": "to win"}'::jsonb, 'jmdict'),
    ('ja', '格好', '樣子', '{"kana": "かっこう", "jlpt": "N4", "jmdict_seq": 1590480, "meaning_en": "appearance"}'::jsonb, 'jmdict'),
    ('ja', '家内', '內人', '{"kana": "かない", "jlpt": "N4", "jmdict_seq": 1192420, "meaning_en": "housewife"}'::jsonb, 'jmdict'),
    ('ja', '悲しい', '難過', '{"kana": "かなしい", "jlpt": "N4", "jmdict_seq": 1483190, "meaning_en": "sad"}'::jsonb, 'jmdict'),
    ('ja', '必ず', '一定', '{"kana": "かならず", "jlpt": "N4", "jmdict_seq": 1487400, "meaning_en": "certainly,necessarily"}'::jsonb, 'jmdict'),
    ('ja', 'お金持ち', '有錢人', '{"kana": "おかねもち", "jlpt": "N4", "jmdict_seq": 2429350, "meaning_en": "rich man"}'::jsonb, 'jmdict'),
    ('ja', '金持ち', '有錢人', '{"kana": "かねもち", "jlpt": "N4", "jmdict_seq": 1242970, "meaning_en": "rich man"}'::jsonb, 'jmdict'),
    ('ja', '彼女', '她/女朋友', '{"kana": "かのじょ", "jlpt": "N4", "jmdict_seq": 1483150, "meaning_en": "she,girlfriend"}'::jsonb, 'jmdict'),
    ('ja', '壁', '牆壁', '{"kana": "かべ", "jlpt": "N4", "jmdict_seq": 1509290, "meaning_en": "wall"}'::jsonb, 'jmdict'),
    ('ja', 'かまう', '在意', '{"kana": "かまう", "jlpt": "N4", "jmdict_seq": 1279680, "meaning_en": "to mind"}'::jsonb, 'jmdict'),
    ('ja', '髪', '頭髮', '{"kana": "かみ", "jlpt": "N4", "jmdict_seq": 1477950, "meaning_en": "hair"}'::jsonb, 'jmdict'),
    ('ja', '噛む', '咬', '{"kana": "かむ", "jlpt": "N4", "jmdict_seq": 1209240, "meaning_en": "to bite,to chew"}'::jsonb, 'jmdict'),
    ('ja', '通う', '通勤', '{"kana": "かよう", "jlpt": "N4", "jmdict_seq": 1432850, "meaning_en": "to commute"}'::jsonb, 'jmdict'),
    ('ja', 'ガラス', '玻璃', '{"kana": "ガラス", "jlpt": "N4", "jmdict_seq": 1040380, "meaning_en": "a glass pane"}'::jsonb, 'jmdict'),
    ('ja', '彼', '他/男朋友', '{"kana": "かれ", "jlpt": "N4", "jmdict_seq": 1483070, "meaning_en": "he,boyfriend"}'::jsonb, 'jmdict'),
    ('ja', '彼ら', '他們', '{"kana": "かれら", "jlpt": "N4", "jmdict_seq": 1483090, "meaning_en": "they"}'::jsonb, 'jmdict'),
    ('ja', '乾く', '乾', '{"kana": "かわく", "jlpt": "N4", "jmdict_seq": 1209650, "meaning_en": "to get dry"}'::jsonb, 'jmdict'),
    ('ja', '代わり', '代替', '{"kana": "かわり", "jlpt": "N4", "jmdict_seq": 1590770, "meaning_en": "substitute,alternate"}'::jsonb, 'jmdict'),
    ('ja', '変わる', '改變（自動）', '{"kana": "かわる", "jlpt": "N4", "jmdict_seq": 1510790, "meaning_en": "to change"}'::jsonb, 'jmdict'),
    ('ja', '考える', '思考', '{"kana": "かんがえる", "jlpt": "N4", "jmdict_seq": 1281020, "meaning_en": "to consider"}'::jsonb, 'jmdict'),
    ('ja', '関係', '關係', '{"kana": "かんけい", "jlpt": "N4", "jmdict_seq": 1215810, "meaning_en": "relationship"}'::jsonb, 'jmdict'),
    ('ja', '看護婦', '護士', '{"kana": "かんごふ", "jlpt": "N4", "jmdict_seq": 1213870, "meaning_en": "female nurse"}'::jsonb, 'jmdict'),
    ('ja', '簡単', '簡單', '{"kana": "かんたん", "jlpt": "N4", "jmdict_seq": 1214330, "meaning_en": "simple"}'::jsonb, 'jmdict'),
    ('ja', '気', '心情', '{"kana": "き", "jlpt": "N4", "jmdict_seq": 1221520, "meaning_en": "spirit,mood"}'::jsonb, 'jmdict'),
    ('ja', '機会', '機會', '{"kana": "きかい", "jlpt": "N4", "jmdict_seq": 1220800, "meaning_en": "opportunity"}'::jsonb, 'jmdict'),
    ('ja', '危険', '危險', '{"kana": "きけん", "jlpt": "N4", "jmdict_seq": 1218560, "meaning_en": "danger"}'::jsonb, 'jmdict'),
    ('ja', '聞こえる', '聽得到', '{"kana": "きこえる", "jlpt": "N4", "jmdict_seq": 1591150, "meaning_en": "to be heard"}'::jsonb, 'jmdict'),
    ('ja', '汽車', '火車', '{"kana": "きしゃ", "jlpt": "N4", "jmdict_seq": 1222700, "meaning_en": "steam train"}'::jsonb, 'jmdict'),
    ('ja', '技術', '技術', '{"kana": "ぎじゅつ", "jlpt": "N4", "jmdict_seq": 1225130, "meaning_en": "art,technology,skill"}'::jsonb, 'jmdict'),
    ('ja', '季節', '季節', '{"kana": "きせつ", "jlpt": "N4", "jmdict_seq": 1222840, "meaning_en": "season"}'::jsonb, 'jmdict'),
    ('ja', '規則', '規則', '{"kana": "きそく", "jlpt": "N4", "jmdict_seq": 1223021, "meaning_en": "regulations"}'::jsonb, 'jmdict'),
    ('ja', 'きっと', '一定', '{"kana": "きっと", "jlpt": "N4", "jmdict_seq": 1003430, "meaning_en": "surely"}'::jsonb, 'jmdict'),
    ('ja', '絹', '絲', '{"kana": "きぬ", "jlpt": "N4", "jmdict_seq": 1258710, "meaning_en": "silk"}'::jsonb, 'jmdict'),
    ('ja', '厳しい', '嚴格', '{"kana": "きびしい", "jlpt": "N4", "jmdict_seq": 1262530, "meaning_en": "strict"}'::jsonb, 'jmdict'),
    ('ja', '気分', '心情', '{"kana": "きぶん", "jlpt": "N4", "jmdict_seq": 1222590, "meaning_en": "mood"}'::jsonb, 'jmdict'),
    ('ja', '決る', '決定（自動）', '{"kana": "きまる", "jlpt": "N4", "jmdict_seq": 1591420, "meaning_en": "to be decided"}'::jsonb, 'jmdict'),
    ('ja', '君', '你（男對女）', '{"kana": "きみ", "jlpt": "N4", "jmdict_seq": 1247250, "meaning_en": "(informal) You (used by men towards women)"}'::jsonb, 'jmdict'),
    ('ja', '決める', '決定（他動）', '{"kana": "きめる", "jlpt": "N4", "jmdict_seq": 1254180, "meaning_en": "to decide"}'::jsonb, 'jmdict'),
    ('ja', '気持ち', '心情', '{"kana": "きもち", "jlpt": "N4", "jmdict_seq": 1591430, "meaning_en": "feeling,mood"}'::jsonb, 'jmdict'),
    ('ja', '着物', '和服', '{"kana": "きもの", "jlpt": "N4", "jmdict_seq": 1423240, "meaning_en": "kimono"}'::jsonb, 'jmdict'),
    ('ja', '客', '客人', '{"kana": "きゃく", "jlpt": "N4", "jmdict_seq": 1226630, "meaning_en": "guest,customer"}'::jsonb, 'jmdict'),
    ('ja', '急', '緊急', '{"kana": "きゅう", "jlpt": "N4", "jmdict_seq": 1228560, "meaning_en": "urgent, steep"}'::jsonb, 'jmdict'),
    ('ja', '急行', '快車', '{"kana": "きゅうこう", "jlpt": "N4", "jmdict_seq": 1228690, "meaning_en": "speedy, express"}'::jsonb, 'jmdict'),
    ('ja', '教育', '教育', '{"kana": "きょういく", "jlpt": "N4", "jmdict_seq": 1236950, "meaning_en": "education"}'::jsonb, 'jmdict'),
    ('ja', '教会', '教會', '{"kana": "きょうかい", "jlpt": "N4", "jmdict_seq": 1237030, "meaning_en": "church"}'::jsonb, 'jmdict'),
    ('ja', '競争', '競爭', '{"kana": "きょうそう", "jlpt": "N4", "jmdict_seq": 1234140, "meaning_en": "competition"}'::jsonb, 'jmdict'),
    ('ja', '興味', '興趣', '{"kana": "きょうみ", "jlpt": "N4", "jmdict_seq": 1238410, "meaning_en": "an interest"}'::jsonb, 'jmdict'),
    ('ja', '近所', '附近', '{"kana": "きんじょ", "jlpt": "N4", "jmdict_seq": 1242350, "meaning_en": "neighbourhood"}'::jsonb, 'jmdict'),
    ('ja', '具合', '狀況', '{"kana": "ぐあい", "jlpt": "N4", "jmdict_seq": 1592500, "meaning_en": "condition,health"}'::jsonb, 'jmdict'),
    ('ja', '空気', '空氣', '{"kana": "くうき", "jlpt": "N4", "jmdict_seq": 1245470, "meaning_en": "air,atmosphere"}'::jsonb, 'jmdict'),
    ('ja', '空港', '機場', '{"kana": "くうこう", "jlpt": "N4", "jmdict_seq": 1245570, "meaning_en": "airport"}'::jsonb, 'jmdict'),
    ('ja', '草', '草', '{"kana": "くさ", "jlpt": "N4", "jmdict_seq": 1401910, "meaning_en": "grass"}'::jsonb, 'jmdict'),
    ('ja', 'くださる', '給（敬語）', '{"kana": "くださる", "jlpt": "N4", "jmdict_seq": 1184280, "meaning_en": "(respectful) to give"}'::jsonb, 'jmdict'),
    ('ja', '首', '脖子', '{"kana": "くび", "jlpt": "N4", "jmdict_seq": 1592270, "meaning_en": "neck"}'::jsonb, 'jmdict'),
    ('ja', '雲', '雲', '{"kana": "くも", "jlpt": "N4", "jmdict_seq": 1173100, "meaning_en": "cloud"}'::jsonb, 'jmdict'),
    ('ja', '比べる', '比較', '{"kana": "くらべる", "jlpt": "N4", "jmdict_seq": 1483540, "meaning_en": "to compare"}'::jsonb, 'jmdict'),
    ('ja', '呉れる', '給（我）', '{"kana": "くれる", "jlpt": "N4", "jmdict_seq": 1269130, "meaning_en": "to give"}'::jsonb, 'jmdict'),
    ('ja', '暮れる', '天黑', '{"kana": "くれる", "jlpt": "N4", "jmdict_seq": 1514960, "meaning_en": "to get dark,to come to an end"}'::jsonb, 'jmdict'),
    ('ja', '君', '君（年輕男性後綴）', '{"kana": "くん", "jlpt": "N4", "jmdict_seq": 1247260, "meaning_en": "suffix for familiar young male"}'::jsonb, 'jmdict'),
    ('ja', '毛', '毛', '{"kana": "け", "jlpt": "N4", "jmdict_seq": 1533820, "meaning_en": "hair or fur"}'::jsonb, 'jmdict'),
    ('ja', '計画', '計畫', '{"kana": "けいかく", "jlpt": "N4", "jmdict_seq": 1252090, "meaning_en": "to plan"}'::jsonb, 'jmdict'),
    ('ja', '経験', '經驗', '{"kana": "けいけん", "jlpt": "N4", "jmdict_seq": 1251270, "meaning_en": "to experience"}'::jsonb, 'jmdict'),
    ('ja', '経済', '經濟', '{"kana": "けいざい", "jlpt": "N4", "jmdict_seq": 1251320, "meaning_en": "finance,economy"}'::jsonb, 'jmdict'),
    ('ja', '警察', '警察', '{"kana": "けいさつ", "jlpt": "N4", "jmdict_seq": 1252390, "meaning_en": "police"}'::jsonb, 'jmdict'),
    ('ja', 'ケーキ', '蛋糕', '{"kana": "ケーキ", "jlpt": "N4", "jmdict_seq": 1047860, "meaning_en": "cake"}'::jsonb, 'jmdict'),
    ('ja', '怪我', '受傷', '{"kana": "けが", "jlpt": "N4", "jmdict_seq": 1200220, "meaning_en": "to injure"}'::jsonb, 'jmdict'),
    ('ja', '景色', '景色', '{"kana": "けしき", "jlpt": "N4", "jmdict_seq": 1250870, "meaning_en": "scene,landscape"}'::jsonb, 'jmdict'),
    ('ja', '消しゴム', '橡皮擦', '{"kana": "けしゴム", "jlpt": "N4", "jmdict_seq": 1350080, "meaning_en": "eraser"}'::jsonb, 'jmdict'),
    ('ja', '下宿', '寄宿', '{"kana": "げしゅく", "jlpt": "N4", "jmdict_seq": 1185290, "meaning_en": "lodging"}'::jsonb, 'jmdict'),
    ('ja', '決して', '絕對（後接否定）', '{"kana": "けっして", "jlpt": "N4", "jmdict_seq": 1254130, "meaning_en": "never"}'::jsonb, 'jmdict'),
    ('ja', 'けれど', '不過', '{"kana": "けれど", "jlpt": "N4", "jmdict_seq": 2853889, "meaning_en": "however"}'::jsonb, 'jmdict'),
    ('ja', 'けれども', '不過（拉長）', '{"kana": "けれども", "jlpt": "N4", "jmdict_seq": 2853889, "meaning_en": "however"}'::jsonb, 'jmdict'),
    ('ja', '原因', '原因', '{"kana": "げんいん", "jlpt": "N4", "jmdict_seq": 1261190, "meaning_en": "cause,source"}'::jsonb, 'jmdict'),
    ('ja', '喧嘩', '吵架', '{"kana": "けんか", "jlpt": "N4", "jmdict_seq": 1257040, "meaning_en": "to quarrel"}'::jsonb, 'jmdict'),
    ('ja', '研究', '研究', '{"kana": "けんきゅう", "jlpt": "N4", "jmdict_seq": 1258520, "meaning_en": "research"}'::jsonb, 'jmdict'),
    ('ja', '研究室', '研究室', '{"kana": "けんきゅうしつ", "jlpt": "N4", "jmdict_seq": 1258570, "meaning_en": "study room,laboratory"}'::jsonb, 'jmdict'),
    ('ja', '見物', '參觀', '{"kana": "けんぶつ", "jlpt": "N4", "jmdict_seq": 1260000, "meaning_en": "sightseeing"}'::jsonb, 'jmdict'),
    ('ja', '子', '小孩', '{"kana": "こ", "jlpt": "N4", "jmdict_seq": 1307770, "meaning_en": "child"}'::jsonb, 'jmdict'),
    ('ja', '斯う', '這樣', '{"kana": "こう", "jlpt": "N4", "jmdict_seq": 1004310, "meaning_en": "this way"}'::jsonb, 'jmdict'),
    ('ja', '郊外', '郊外', '{"kana": "こうがい", "jlpt": "N4", "jmdict_seq": 1282490, "meaning_en": "outskirts"}'::jsonb, 'jmdict'),
    ('ja', '講義', '講課', '{"kana": "こうぎ", "jlpt": "N4", "jmdict_seq": 1282260, "meaning_en": "lecture"}'::jsonb, 'jmdict'),
    ('ja', '工業', '工業', '{"kana": "こうぎょう", "jlpt": "N4", "jmdict_seq": 1278040, "meaning_en": "the manufacturing industry"}'::jsonb, 'jmdict'),
    ('ja', '高校', '高中', '{"kana": "こうこう", "jlpt": "N4", "jmdict_seq": 1283500, "meaning_en": "high school"}'::jsonb, 'jmdict'),
    ('ja', '高校生', '高中生', '{"kana": "こうこうせい", "jlpt": "N4", "jmdict_seq": 1283510, "meaning_en": "high school student"}'::jsonb, 'jmdict'),
    ('ja', '工場', '工廠', '{"kana": "こうじょう", "jlpt": "N4", "jmdict_seq": 1578700, "meaning_en": "factory"}'::jsonb, 'jmdict'),
    ('ja', '校長', '校長', '{"kana": "こうちょう", "jlpt": "N4", "jmdict_seq": 1279590, "meaning_en": "headmaster"}'::jsonb, 'jmdict'),
    ('ja', '交通', '交通', '{"kana": "こうつう", "jlpt": "N4", "jmdict_seq": 1272280, "meaning_en": "traffic,transportation"}'::jsonb, 'jmdict'),
    ('ja', '講堂', '禮堂', '{"kana": "こうどう", "jlpt": "N4", "jmdict_seq": 1282340, "meaning_en": "auditorium"}'::jsonb, 'jmdict'),
    ('ja', '高等学校', '高級中學', '{"kana": "こうとうがっこう", "jlpt": "N4", "jmdict_seq": 1283860, "meaning_en": "high school"}'::jsonb, 'jmdict'),
    ('ja', '公務員', '公務員', '{"kana": "こうむいん", "jlpt": "N4", "jmdict_seq": 1274820, "meaning_en": "government worker"}'::jsonb, 'jmdict'),
    ('ja', '国際', '國際', '{"kana": "こくさい", "jlpt": "N4", "jmdict_seq": 1286400, "meaning_en": "international"}'::jsonb, 'jmdict'),
    ('ja', '心', '心', '{"kana": "こころ", "jlpt": "N4", "jmdict_seq": 1360480, "meaning_en": "core,heart"}'::jsonb, 'jmdict'),
    ('ja', '御主人', '您先生', '{"kana": "ごしゅじん", "jlpt": "N4", "jmdict_seq": 1270390, "meaning_en": "(honorable) your husband"}'::jsonb, 'jmdict'),
    ('ja', '故障', '故障', '{"kana": "こしょう", "jlpt": "N4", "jmdict_seq": 1267180, "meaning_en": "to break-down"}'::jsonb, 'jmdict'),
    ('ja', 'ご存じ', '知道（敬語）', '{"kana": "ごぞんじ", "jlpt": "N4", "jmdict_seq": 1593570, "meaning_en": "knowing,acquaintance"}'::jsonb, 'jmdict'),
    ('ja', '答', '答案', '{"kana": "こたえ", "jlpt": "N4", "jmdict_seq": 1449530, "meaning_en": "response"}'::jsonb, 'jmdict'),
    ('ja', 'ごちそう', '大餐', '{"kana": "ごちそう", "jlpt": "N4", "jmdict_seq": 1593590, "meaning_en": "a feast"}'::jsonb, 'jmdict'),
    ('ja', 'こと', '事情', '{"kana": "こと", "jlpt": "N4", "jmdict_seq": 2524270, "meaning_en": "thing,matter"}'::jsonb, 'jmdict'),
    ('ja', '小鳥', '小鳥', '{"kana": "ことり", "jlpt": "N4", "jmdict_seq": 1348530, "meaning_en": "small bird"}'::jsonb, 'jmdict'),
    ('ja', 'このあいだ', '前陣子', '{"kana": "このあいだ", "jlpt": "N4", "jmdict_seq": 1004690, "meaning_en": "the other day,recently"}'::jsonb, 'jmdict'),
    ('ja', 'このごろ', '最近', '{"kana": "このごろ", "jlpt": "N4", "jmdict_seq": 1004710, "meaning_en": "these days,nowadays"}'::jsonb, 'jmdict'),
    ('ja', '細かい', '細小', '{"kana": "こまかい", "jlpt": "N4", "jmdict_seq": 1295530, "meaning_en": "small, fine"}'::jsonb, 'jmdict'),
    ('ja', '塵', '垃圾', '{"kana": "ごみ", "jlpt": "N4", "jmdict_seq": 1369900, "meaning_en": "rubbish"}'::jsonb, 'jmdict'),
    ('ja', '込む', '擁擠', '{"kana": "こむ", "jlpt": "N4", "jmdict_seq": 1593410, "meaning_en": "to be crowded"}'::jsonb, 'jmdict'),
    ('ja', '米', '米', '{"kana": "こめ", "jlpt": "N4", "jmdict_seq": 1508750, "meaning_en": "uncooked rice"}'::jsonb, 'jmdict'),
    ('ja', 'ごらんになる', '看（敬語）', '{"kana": "ごらんになる", "jlpt": "N4", "jmdict_seq": 2217040, "meaning_en": "(respectful) to see"}'::jsonb, 'jmdict'),
    ('ja', 'これから', '從現在起', '{"kana": "これから", "jlpt": "N4", "jmdict_seq": 1004790, "meaning_en": "after this"}'::jsonb, 'jmdict'),
    ('ja', '怖い', '可怕', '{"kana": "こわい", "jlpt": "N4", "jmdict_seq": 1593480, "meaning_en": "frightening"}'::jsonb, 'jmdict'),
    ('ja', '壊す', '弄壞（他動）', '{"kana": "こわす", "jlpt": "N4", "jmdict_seq": 1199890, "meaning_en": "to break"}'::jsonb, 'jmdict'),
    ('ja', '壊れる', '壞掉（自動）', '{"kana": "こわれる", "jlpt": "N4", "jmdict_seq": 1199900, "meaning_en": "to be broken"}'::jsonb, 'jmdict'),
    ('ja', 'コンサート', '演唱會', '{"kana": "コンサート", "jlpt": "N4", "jmdict_seq": 1051970, "meaning_en": "concert"}'::jsonb, 'jmdict'),
    ('ja', '今度', '這次/下次', '{"kana": "こんど", "jlpt": "N4", "jmdict_seq": 1289370, "meaning_en": "now,next time"}'::jsonb, 'jmdict'),
    ('ja', 'コンピュータ', '電腦', '{"kana": "コンピュータ", "jlpt": "N4", "jmdict_seq": 1053350, "meaning_en": "computer"}'::jsonb, 'jmdict'),
    ('ja', 'コンピューター', '電腦（拉長）', '{"kana": "コンピューター", "jlpt": "N4", "jmdict_seq": 1053350, "meaning_en": "computer"}'::jsonb, 'jmdict'),
    ('ja', '今夜', '今晚', '{"kana": "こんや", "jlpt": "N4", "jmdict_seq": 1289520, "meaning_en": "tonight"}'::jsonb, 'jmdict'),
    ('ja', '最近', '最近', '{"kana": "さいきん", "jlpt": "N4", "jmdict_seq": 1293780, "meaning_en": "latest,nowadays"}'::jsonb, 'jmdict'),
    ('ja', '最後', '最後', '{"kana": "さいご", "jlpt": "N4", "jmdict_seq": 1293810, "meaning_en": "last,end"}'::jsonb, 'jmdict'),
    ('ja', '最初', '最初', '{"kana": "さいしょ", "jlpt": "N4", "jmdict_seq": 1293990, "meaning_en": "beginning,first"}'::jsonb, 'jmdict'),
    ('ja', '坂', '坡道', '{"kana": "さか", "jlpt": "N4", "jmdict_seq": 1297110, "meaning_en": "slope,hill"}'::jsonb, 'jmdict'),
    ('ja', '探す', '尋找', '{"kana": "さがす", "jlpt": "N4", "jmdict_seq": 1593670, "meaning_en": "to look for"}'::jsonb, 'jmdict'),
    ('ja', '下る', '下降（自動）', '{"kana": "さがる", "jlpt": "N4", "jmdict_seq": 1184160, "meaning_en": "to get down,to descend"}'::jsonb, 'jmdict'),
    ('ja', '盛ん', '盛大', '{"kana": "さかん", "jlpt": "N4", "jmdict_seq": 1379750, "meaning_en": "popularity,prosperous"}'::jsonb, 'jmdict'),
    ('ja', '下げる', '降下（他動）', '{"kana": "さげる", "jlpt": "N4", "jmdict_seq": 1184170, "meaning_en": "to hang,to lower,to move back"}'::jsonb, 'jmdict'),
    ('ja', '差し上げる', '給（敬語）', '{"kana": "さしあげる", "jlpt": "N4", "jmdict_seq": 1291270, "meaning_en": "(polite) to give"}'::jsonb, 'jmdict'),
    ('ja', '先', '剛剛', '{"kana": "さっき", "jlpt": "N4", "jmdict_seq": 1005180, "meaning_en": "some time ago"}'::jsonb, 'jmdict'),
    ('ja', '寂しい', '寂寞', '{"kana": "さびしい", "jlpt": "N4", "jmdict_seq": 1579720, "meaning_en": "lonely"}'::jsonb, 'jmdict'),
    ('ja', 'さ来月', '下下個月', '{"kana": "さらいげつ", "jlpt": "N4", "jmdict_seq": 1293640, "meaning_en": "the month after next"}'::jsonb, 'jmdict'),
    ('ja', 'さ来週', '下下週', '{"kana": "さらいしゅう", "jlpt": "N4", "jmdict_seq": 1293650, "meaning_en": "the week after next"}'::jsonb, 'jmdict'),
    ('ja', 'サラダ', '沙拉', '{"kana": "サラダ", "jlpt": "N4", "jmdict_seq": 1057850, "meaning_en": "salad"}'::jsonb, 'jmdict'),
    ('ja', '騒ぐ', '吵鬧', '{"kana": "さわぐ", "jlpt": "N4", "jmdict_seq": 1403040, "meaning_en": "to make noise,to be excited"}'::jsonb, 'jmdict'),
    ('ja', '触る', '碰', '{"kana": "さわる", "jlpt": "N4", "jmdict_seq": 1357980, "meaning_en": "to touch"}'::jsonb, 'jmdict'),
    ('ja', '産業', '產業', '{"kana": "さんぎょう", "jlpt": "N4", "jmdict_seq": 1303770, "meaning_en": "industry"}'::jsonb, 'jmdict'),
    ('ja', 'サンダル', '涼鞋', '{"kana": "サンダル", "jlpt": "N4", "jmdict_seq": 1058480, "meaning_en": "sandal"}'::jsonb, 'jmdict'),
    ('ja', 'サンドイッチ', '三明治', '{"kana": "サンドイッチ", "jlpt": "N4", "jmdict_seq": 1058580, "meaning_en": "sandwich"}'::jsonb, 'jmdict'),
    ('ja', '残念', '可惜', '{"kana": "ざんねん", "jlpt": "N4", "jmdict_seq": 1304680, "meaning_en": "disappointment"}'::jsonb, 'jmdict'),
    ('ja', '市', '市', '{"kana": "し", "jlpt": "N4", "jmdict_seq": 1308090, "meaning_en": "city"}'::jsonb, 'jmdict'),
    ('ja', '字', '字', '{"kana": "じ", "jlpt": "N4", "jmdict_seq": 1315130, "meaning_en": "character"}'::jsonb, 'jmdict'),
    ('ja', '試合', '比賽', '{"kana": "しあい", "jlpt": "N4", "jmdict_seq": 1312420, "meaning_en": "match,game"}'::jsonb, 'jmdict'),
    ('ja', '仕方', '做法', '{"kana": "しかた", "jlpt": "N4", "jmdict_seq": 1594110, "meaning_en": "method"}'::jsonb, 'jmdict'),
    ('ja', '然る', '罵', '{"kana": "しかる", "jlpt": "N4", "jmdict_seq": 1394730, "meaning_en": "a particular"}'::jsonb, 'jmdict'),
    ('ja', '試験', '考試', '{"kana": "しけん", "jlpt": "N4", "jmdict_seq": 1312350, "meaning_en": "examination"}'::jsonb, 'jmdict'),
    ('ja', '事故', '事故', '{"kana": "じこ", "jlpt": "N4", "jmdict_seq": 1313850, "meaning_en": "accident"}'::jsonb, 'jmdict'),
    ('ja', '地震', '地震', '{"kana": "じしん", "jlpt": "N4", "jmdict_seq": 1421210, "meaning_en": "earthquake"}'::jsonb, 'jmdict'),
    ('ja', '時代', '時代', '{"kana": "じだい", "jlpt": "N4", "jmdict_seq": 1316300, "meaning_en": "era"}'::jsonb, 'jmdict'),
    ('ja', '下着', '內衣', '{"kana": "したぎ", "jlpt": "N4", "jmdict_seq": 1185930, "meaning_en": "underwear"}'::jsonb, 'jmdict'),
    ('ja', '支度', '準備', '{"kana": "したく", "jlpt": "N4", "jmdict_seq": 1310260, "meaning_en": "to prepare"}'::jsonb, 'jmdict'),
    ('ja', 'しっかり', '紮實/穩固', '{"kana": "しっかり", "jlpt": "N4", "jmdict_seq": 1594400, "meaning_en": "firmly,steadily"}'::jsonb, 'jmdict'),
    ('ja', '失敗', '失敗', '{"kana": "しっぱい", "jlpt": "N4", "jmdict_seq": 1320140, "meaning_en": "failure,mistake"}'::jsonb, 'jmdict'),
    ('ja', '辞典', '辭典', '{"kana": "じてん", "jlpt": "N4", "jmdict_seq": 1595270, "meaning_en": "dictionary"}'::jsonb, 'jmdict'),
    ('ja', '品物', '商品', '{"kana": "しなもの", "jlpt": "N4", "jmdict_seq": 1490670, "meaning_en": "goods"}'::jsonb, 'jmdict'),
    ('ja', 'しばらく', '一陣子', '{"kana": "しばらく", "jlpt": "N4", "jmdict_seq": 1304420, "meaning_en": "little while"}'::jsonb, 'jmdict'),
    ('ja', '島', '島', '{"kana": "しま", "jlpt": "N4", "jmdict_seq": 1446760, "meaning_en": "island"}'::jsonb, 'jmdict'),
    ('ja', '市民', '市民', '{"kana": "しみん", "jlpt": "N4", "jmdict_seq": 1308690, "meaning_en": "citizen"}'::jsonb, 'jmdict'),
    ('ja', '事務所', '辦公室', '{"kana": "じむしょ", "jlpt": "N4", "jmdict_seq": 1314400, "meaning_en": "office"}'::jsonb, 'jmdict'),
    ('ja', '社会', '社會', '{"kana": "しゃかい", "jlpt": "N4", "jmdict_seq": 1322700, "meaning_en": "society,public"}'::jsonb, 'jmdict'),
    ('ja', '社長', '社長', '{"kana": "しゃちょう", "jlpt": "N4", "jmdict_seq": 1322920, "meaning_en": "company president"}'::jsonb, 'jmdict'),
    ('ja', 'じゃま', '打擾', '{"kana": "じゃま", "jlpt": "N4", "jmdict_seq": 1323500, "meaning_en": "hindrance,intrusion"}'::jsonb, 'jmdict'),
    ('ja', 'ジャム', '果醬', '{"kana": "ジャム", "jlpt": "N4", "jmdict_seq": 1065680, "meaning_en": "jam"}'::jsonb, 'jmdict'),
    ('ja', '自由', '自由', '{"kana": "じゆう", "jlpt": "N4", "jmdict_seq": 1318720, "meaning_en": "freedom"}'::jsonb, 'jmdict'),
    ('ja', '習慣', '習慣', '{"kana": "しゅうかん", "jlpt": "N4", "jmdict_seq": 1333090, "meaning_en": "custom,manners"}'::jsonb, 'jmdict'),
    ('ja', '住所', '住址', '{"kana": "じゅうしょ", "jlpt": "N4", "jmdict_seq": 1334080, "meaning_en": "an address,a residence"}'::jsonb, 'jmdict'),
    ('ja', '柔道', '柔道', '{"kana": "じゅうどう", "jlpt": "N4", "jmdict_seq": 1335440, "meaning_en": "judo"}'::jsonb, 'jmdict'),
    ('ja', '十分', '充分', '{"kana": "じゅうぶん", "jlpt": "N4", "jmdict_seq": 1335080, "meaning_en": "enough"}'::jsonb, 'jmdict'),
    ('ja', '出席', '出席', '{"kana": "しゅっせき", "jlpt": "N4", "jmdict_seq": 1339460, "meaning_en": "to attend"}'::jsonb, 'jmdict'),
    ('ja', '出発', '出發', '{"kana": "しゅっぱつ", "jlpt": "N4", "jmdict_seq": 1340000, "meaning_en": "to depart"}'::jsonb, 'jmdict'),
    ('ja', '趣味', '興趣', '{"kana": "しゅみ", "jlpt": "N4", "jmdict_seq": 1329000, "meaning_en": "hobby"}'::jsonb, 'jmdict'),
    ('ja', '準備', '準備', '{"kana": "じゅんび", "jlpt": "N4", "jmdict_seq": 1341670, "meaning_en": "to prepare"}'::jsonb, 'jmdict'),
    ('ja', '紹介', '介紹', '{"kana": "しょうかい", "jlpt": "N4", "jmdict_seq": 1351430, "meaning_en": "introduction"}'::jsonb, 'jmdict'),
    ('ja', '小学校', '小學', '{"kana": "しょうがっこう", "jlpt": "N4", "jmdict_seq": 1347870, "meaning_en": "elementary school"}'::jsonb, 'jmdict'),
    ('ja', '小説', '小說', '{"kana": "しょうせつ", "jlpt": "N4", "jmdict_seq": 1348430, "meaning_en": "novel"}'::jsonb, 'jmdict'),
    ('ja', '招待', '邀請', '{"kana": "しょうたい", "jlpt": "N4", "jmdict_seq": 1349610, "meaning_en": "to invite"}'::jsonb, 'jmdict'),
    ('ja', '承知', '同意', '{"kana": "しょうち", "jlpt": "N4", "jmdict_seq": 1349480, "meaning_en": "to consent"}'::jsonb, 'jmdict'),
    ('ja', '将来', '將來', '{"kana": "しょうらい", "jlpt": "N4", "jmdict_seq": 1347710, "meaning_en": "future,prospects"}'::jsonb, 'jmdict'),
    ('ja', '食事', '用餐', '{"kana": "しょくじ", "jlpt": "N4", "jmdict_seq": 1358490, "meaning_en": "to have a meal"}'::jsonb, 'jmdict'),
    ('ja', '食料品', '食品', '{"kana": "しょくりょうひん", "jlpt": "N4", "jmdict_seq": 1358680, "meaning_en": "groceries"}'::jsonb, 'jmdict'),
    ('ja', '女性', '女性', '{"kana": "じょせい", "jlpt": "N4", "jmdict_seq": 1345250, "meaning_en": "woman"}'::jsonb, 'jmdict'),
    ('ja', '知らせる', '通知', '{"kana": "しらせる", "jlpt": "N4", "jmdict_seq": 1420410, "meaning_en": "to notify"}'::jsonb, 'jmdict'),
    ('ja', '調べる', '查', '{"kana": "しらべる", "jlpt": "N4", "jmdict_seq": 1429060, "meaning_en": "to investigate"}'::jsonb, 'jmdict'),
    ('ja', '人口', '人口', '{"kana": "じんこう", "jlpt": "N4", "jmdict_seq": 1367300, "meaning_en": "population"}'::jsonb, 'jmdict'),
    ('ja', '神社', '神社', '{"kana": "じんじゃ", "jlpt": "N4", "jmdict_seq": 1364670, "meaning_en": "Shinto shrine"}'::jsonb, 'jmdict'),
    ('ja', '親切', '親切', '{"kana": "しんせつ", "jlpt": "N4", "jmdict_seq": 1365250, "meaning_en": "kindness"}'::jsonb, 'jmdict'),
    ('ja', '心配', '擔心', '{"kana": "しんぱい", "jlpt": "N4", "jmdict_seq": 1360930, "meaning_en": "to worry"}'::jsonb, 'jmdict'),
    ('ja', '新聞社', '報社', '{"kana": "しんぶんしゃ", "jlpt": "N4", "jmdict_seq": 1362400, "meaning_en": "newspaper company"}'::jsonb, 'jmdict'),
    ('ja', '水泳', '游泳', '{"kana": "すいえい", "jlpt": "N4", "jmdict_seq": 1371320, "meaning_en": "swimming"}'::jsonb, 'jmdict'),
    ('ja', '水道', '自來水', '{"kana": "すいどう", "jlpt": "N4", "jmdict_seq": 1371920, "meaning_en": "water supply"}'::jsonb, 'jmdict'),
    ('ja', 'ずいぶん', '相當', '{"kana": "ずいぶん", "jlpt": "N4", "jmdict_seq": 1372800, "meaning_en": "extremely"}'::jsonb, 'jmdict'),
    ('ja', '数学', '數學', '{"kana": "すうがく", "jlpt": "N4", "jmdict_seq": 1372980, "meaning_en": "mathematics,arithmetic"}'::jsonb, 'jmdict'),
    ('ja', 'スーツ', '套裝', '{"kana": "スーツ", "jlpt": "N4", "jmdict_seq": 1066680, "meaning_en": "suit"}'::jsonb, 'jmdict'),
    ('ja', 'スーツケース', '行李箱', '{"kana": "スーツケース", "jlpt": "N4", "jmdict_seq": 1066690, "meaning_en": "suitcase"}'::jsonb, 'jmdict'),
    ('ja', '過ぎる', '超過', '{"kana": "すぎる", "jlpt": "N4", "jmdict_seq": 1195970, "meaning_en": "to exceed"}'::jsonb, 'jmdict')
  returning id, lemma
)
insert into shrine_words (shrine_id, word_id, position)
select
  (select id from shrines where slug = 'yasaka'),
  nw.id,
  row_number() over (order by nw.lemma)
from new_words nw;
