-- 007_n4_words_heian
-- N4 單字匯入：平安神宮（CSV 行 322-641，共 320 字）
-- 資料源：stephenmk/yomitan-jlpt-vocab (CC-BY, Jonathan Waller / Tanos)
-- 中文翻譯：Claude（學生友善口語風格）

with new_words as (
  insert into words (lang_code, lemma, meaning_zh, meta, source) values
    ('ja', '空く', '空著', '{"kana": "すく", "jlpt": "N4", "jmdict_seq": 1586265, "meaning_en": "to become empty"}'::jsonb, 'jmdict'),
    ('ja', 'スクリーン', '螢幕', '{"kana": "スクリーン", "jlpt": "N4", "jmdict_seq": 1068550, "meaning_en": "screen"}'::jsonb, 'jmdict'),
    ('ja', '凄い', '厲害', '{"kana": "すごい", "jlpt": "N4", "jmdict_seq": 1374550, "meaning_en": "terrific"}'::jsonb, 'jmdict'),
    ('ja', '進む', '前進', '{"kana": "すすむ", "jlpt": "N4", "jmdict_seq": 1365980, "meaning_en": "to make progress"}'::jsonb, 'jmdict'),
    ('ja', 'すっかり', '完全', '{"kana": "すっかり", "jlpt": "N4", "jmdict_seq": 1006110, "meaning_en": "completely"}'::jsonb, 'jmdict'),
    ('ja', 'すっと', '一直/突然', '{"kana": "すっと", "jlpt": "N4", "jmdict_seq": 1006140, "meaning_en": "straight,all of a sudden"}'::jsonb, 'jmdict'),
    ('ja', 'ステーキ', '牛排', '{"kana": "ステーキ", "jlpt": "N4", "jmdict_seq": 1070280, "meaning_en": "steak"}'::jsonb, 'jmdict'),
    ('ja', '捨てる', '丟掉', '{"kana": "すてる", "jlpt": "N4", "jmdict_seq": 1322320, "meaning_en": "to throw away"}'::jsonb, 'jmdict'),
    ('ja', 'ステレオ', '音響', '{"kana": "ステレオ", "jlpt": "N4", "jmdict_seq": 1070650, "meaning_en": "stereo"}'::jsonb, 'jmdict'),
    ('ja', '砂', '沙', '{"kana": "すな", "jlpt": "N4", "jmdict_seq": 1291500, "meaning_en": "sand"}'::jsonb, 'jmdict'),
    ('ja', 'すばらしい', '了不起', '{"kana": "すばらしい", "jlpt": "N4", "jmdict_seq": 1397300, "meaning_en": "wonderful"}'::jsonb, 'jmdict'),
    ('ja', '滑る', '滑', '{"kana": "すべる", "jlpt": "N4", "jmdict_seq": 1208640, "meaning_en": "to slide,to slip"}'::jsonb, 'jmdict'),
    ('ja', '隅', '角落', '{"kana": "すみ", "jlpt": "N4", "jmdict_seq": 1246440, "meaning_en": "corner,nook"}'::jsonb, 'jmdict'),
    ('ja', '済む', '結束', '{"kana": "すむ", "jlpt": "N4", "jmdict_seq": 1295070, "meaning_en": "to finish"}'::jsonb, 'jmdict'),
    ('ja', '掏摸', '扒手', '{"kana": "すり", "jlpt": "N4", "jmdict_seq": 1567450, "meaning_en": "pickpocket"}'::jsonb, 'jmdict'),
    ('ja', 'すると', '結果', '{"kana": "すると", "jlpt": "N4", "jmdict_seq": 1006280, "meaning_en": "then"}'::jsonb, 'jmdict'),
    ('ja', '生活', '生活', '{"kana": "せいかつ", "jlpt": "N4", "jmdict_seq": 1378860, "meaning_en": "to live"}'::jsonb, 'jmdict'),
    ('ja', '生産', '生產', '{"kana": "せいさん", "jlpt": "N4", "jmdict_seq": 1378990, "meaning_en": "to produce"}'::jsonb, 'jmdict'),
    ('ja', '政治', '政治', '{"kana": "せいじ", "jlpt": "N4", "jmdict_seq": 1375970, "meaning_en": "politics,government"}'::jsonb, 'jmdict'),
    ('ja', '西洋', '西洋', '{"kana": "せいよう", "jlpt": "N4", "jmdict_seq": 1381100, "meaning_en": "western countries"}'::jsonb, 'jmdict'),
    ('ja', '世界', '世界', '{"kana": "せかい", "jlpt": "N4", "jmdict_seq": 1373860, "meaning_en": "the world"}'::jsonb, 'jmdict'),
    ('ja', '席', '座位', '{"kana": "せき", "jlpt": "N4", "jmdict_seq": 1382250, "meaning_en": "seat"}'::jsonb, 'jmdict'),
    ('ja', '説明', '說明', '{"kana": "せつめい", "jlpt": "N4", "jmdict_seq": 1386460, "meaning_en": "explanation"}'::jsonb, 'jmdict'),
    ('ja', '背中', '背', '{"kana": "せなか", "jlpt": "N4", "jmdict_seq": 1472800, "meaning_en": "back of the body"}'::jsonb, 'jmdict'),
    ('ja', 'ぜひ', '務必', '{"kana": "ぜひ", "jlpt": "N4", "jmdict_seq": 1374530, "meaning_en": "without fail"}'::jsonb, 'jmdict'),
    ('ja', '世話', '照顧', '{"kana": "せわ", "jlpt": "N4", "jmdict_seq": 1374300, "meaning_en": "to look after"}'::jsonb, 'jmdict'),
    ('ja', '線', '線', '{"kana": "せん", "jlpt": "N4", "jmdict_seq": 1391780, "meaning_en": "line"}'::jsonb, 'jmdict'),
    ('ja', '全然', '完全（後接否定）', '{"kana": "ぜんぜん", "jlpt": "N4", "jmdict_seq": 1395620, "meaning_en": "not entirely (used in a negative sentence)"}'::jsonb, 'jmdict'),
    ('ja', '戦争', '戰爭', '{"kana": "せんそう", "jlpt": "N4", "jmdict_seq": 1390360, "meaning_en": "war"}'::jsonb, 'jmdict'),
    ('ja', '先輩', '前輩', '{"kana": "せんぱい", "jlpt": "N4", "jmdict_seq": 1388410, "meaning_en": "senior"}'::jsonb, 'jmdict'),
    ('ja', 'そう', '是這樣', '{"kana": "そう", "jlpt": "N4", "jmdict_seq": 1006610, "meaning_en": "really"}'::jsonb, 'jmdict'),
    ('ja', '相談', '商量', '{"kana": "そうだん", "jlpt": "N4", "jmdict_seq": 1401210, "meaning_en": "to discuss"}'::jsonb, 'jmdict'),
    ('ja', '育てる', '養育', '{"kana": "そだてる", "jlpt": "N4", "jmdict_seq": 1160570, "meaning_en": "to rear,to bring up"}'::jsonb, 'jmdict'),
    ('ja', '卒業', '畢業', '{"kana": "そつぎょう", "jlpt": "N4", "jmdict_seq": 1405890, "meaning_en": "graduation"}'::jsonb, 'jmdict'),
    ('ja', '祖父', '祖父', '{"kana": "そふ", "jlpt": "N4", "jmdict_seq": 1396840, "meaning_en": "grandfather"}'::jsonb, 'jmdict'),
    ('ja', 'ソフト', '軟', '{"kana": "ソフト", "jlpt": "N4", "jmdict_seq": 1075500, "meaning_en": "soft"}'::jsonb, 'jmdict'),
    ('ja', '祖母', '祖母', '{"kana": "そぼ", "jlpt": "N4", "jmdict_seq": 1396860, "meaning_en": "grandmother"}'::jsonb, 'jmdict'),
    ('ja', 'それで', '然後/所以', '{"kana": "それで", "jlpt": "N4", "jmdict_seq": 1007000, "meaning_en": "because of that"}'::jsonb, 'jmdict'),
    ('ja', 'それに', '而且', '{"kana": "それに", "jlpt": "N4", "jmdict_seq": 1007040, "meaning_en": "moreover"}'::jsonb, 'jmdict'),
    ('ja', 'それほど', '那麼', '{"kana": "それほど", "jlpt": "N4", "jmdict_seq": 1007060, "meaning_en": "to that extent"}'::jsonb, 'jmdict'),
    ('ja', 'そろそろ', '差不多該', '{"kana": "そろそろ", "jlpt": "N4", "jmdict_seq": 1345605, "meaning_en": "gradually,soon"}'::jsonb, 'jmdict'),
    ('ja', 'そんな', '那樣的', '{"kana": "そんな", "jlpt": "N4", "jmdict_seq": 1007130, "meaning_en": "that sort of"}'::jsonb, 'jmdict'),
    ('ja', 'そんなに', '那麼地', '{"kana": "そんなに", "jlpt": "N4", "jmdict_seq": 2008740, "meaning_en": "so much,like that"}'::jsonb, 'jmdict'),
    ('ja', '退院', '出院', '{"kana": "たいいん", "jlpt": "N4", "jmdict_seq": 1411300, "meaning_en": "to leave hospital"}'::jsonb, 'jmdict'),
    ('ja', '大学生', '大學生', '{"kana": "だいがくせい", "jlpt": "N4", "jmdict_seq": 1413260, "meaning_en": "university student"}'::jsonb, 'jmdict'),
    ('ja', '大事', '重要', '{"kana": "だいじ", "jlpt": "N4", "jmdict_seq": 1413940, "meaning_en": "important,valuable,serious matter"}'::jsonb, 'jmdict'),
    ('ja', '大体', '大致', '{"kana": "だいたい", "jlpt": "N4", "jmdict_seq": 1414470, "meaning_en": "generally"}'::jsonb, 'jmdict'),
    ('ja', '大抵', '通常', '{"kana": "たいてい", "jlpt": "N4", "jmdict_seq": 1414580, "meaning_en": "usually"}'::jsonb, 'jmdict'),
    ('ja', 'タイプ', '類型', '{"kana": "タイプ", "jlpt": "N4", "jmdict_seq": 1075940, "meaning_en": "type,style"}'::jsonb, 'jmdict'),
    ('ja', '大分', '相當', '{"kana": "だいぶ", "jlpt": "N4", "jmdict_seq": 1414920, "meaning_en": "greatly"}'::jsonb, 'jmdict'),
    ('ja', '台風', '颱風', '{"kana": "たいふう", "jlpt": "N4", "jmdict_seq": 1596780, "meaning_en": "typhoon"}'::jsonb, 'jmdict'),
    ('ja', '倒れる', '倒下', '{"kana": "たおれる", "jlpt": "N4", "jmdict_seq": 1445790, "meaning_en": "to break down"}'::jsonb, 'jmdict'),
    ('ja', 'だから', '所以', '{"kana": "だから", "jlpt": "N4", "jmdict_seq": 1007310, "meaning_en": "so,therefore"}'::jsonb, 'jmdict'),
    ('ja', '確か', '確實', '{"kana": "たしか", "jlpt": "N4", "jmdict_seq": 1596930, "meaning_en": "definite"}'::jsonb, 'jmdict'),
    ('ja', '足す', '加（數字）', '{"kana": "たす", "jlpt": "N4", "jmdict_seq": 1404700, "meaning_en": "to add a number"}'::jsonb, 'jmdict'),
    ('ja', '訪ねる', '拜訪', '{"kana": "たずねる", "jlpt": "N4", "jmdict_seq": 1518070, "meaning_en": "to visit"}'::jsonb, 'jmdict'),
    ('ja', '尋ねる', '詢問', '{"kana": "たずねる", "jlpt": "N4", "jmdict_seq": 1369940, "meaning_en": "to ask"}'::jsonb, 'jmdict'),
    ('ja', '正しい', '正確', '{"kana": "ただしい", "jlpt": "N4", "jmdict_seq": 1376600, "meaning_en": "correct"}'::jsonb, 'jmdict'),
    ('ja', '畳', '榻榻米', '{"kana": "たたみ", "jlpt": "N4", "jmdict_seq": 1356750, "meaning_en": "Japanese straw mat"}'::jsonb, 'jmdict'),
    ('ja', '立てる', '豎立（他動）', '{"kana": "たてる", "jlpt": "N4", "jmdict_seq": 1551530, "meaning_en": "to stand something up"}'::jsonb, 'jmdict'),
    ('ja', '建てる', '蓋（他動）', '{"kana": "たてる", "jlpt": "N4", "jmdict_seq": 1257330, "meaning_en": "to build"}'::jsonb, 'jmdict'),
    ('ja', '例えば', '例如', '{"kana": "たとえば", "jlpt": "N4", "jmdict_seq": 1556370, "meaning_en": "for example"}'::jsonb, 'jmdict'),
    ('ja', '棚', '架子', '{"kana": "たな", "jlpt": "N4", "jmdict_seq": 1416700, "meaning_en": "shelves"}'::jsonb, 'jmdict'),
    ('ja', '楽しみ', '期待', '{"kana": "たのしみ", "jlpt": "N4", "jmdict_seq": 1207250, "meaning_en": "joy"}'::jsonb, 'jmdict'),
    ('ja', '楽む', '享受', '{"kana": "たのしむ", "jlpt": "N4", "jmdict_seq": 1207270, "meaning_en": "to enjoy oneself"}'::jsonb, 'jmdict'),
    ('ja', 'たまに', '偶爾', '{"kana": "たまに", "jlpt": "N4", "jmdict_seq": 1634500, "meaning_en": "occasionally"}'::jsonb, 'jmdict'),
    ('ja', '為', '為了', '{"kana": "ため", "jlpt": "N4", "jmdict_seq": 1157080, "meaning_en": "in order to"}'::jsonb, 'jmdict'),
    ('ja', 'だめ', '不行', '{"kana": "だめ", "jlpt": "N4", "jmdict_seq": 1409110, "meaning_en": "no good"}'::jsonb, 'jmdict'),
    ('ja', '足りる', '足夠', '{"kana": "たりる", "jlpt": "N4", "jmdict_seq": 1404740, "meaning_en": "to be enough"}'::jsonb, 'jmdict'),
    ('ja', '男性', '男性', '{"kana": "だんせい", "jlpt": "N4", "jmdict_seq": 1420160, "meaning_en": "male"}'::jsonb, 'jmdict'),
    ('ja', '暖房', '暖氣', '{"kana": "だんぼう", "jlpt": "N4", "jmdict_seq": 1419860, "meaning_en": "heating"}'::jsonb, 'jmdict'),
    ('ja', '血', '血', '{"kana": "ち", "jlpt": "N4", "jmdict_seq": 1255060, "meaning_en": "blood"}'::jsonb, 'jmdict'),
    ('ja', 'チェック', '確認', '{"kana": "チェック", "jlpt": "N4", "jmdict_seq": 1077550, "meaning_en": "to check"}'::jsonb, 'jmdict'),
    ('ja', '力', '力量', '{"kana": "ちから", "jlpt": "N4", "jmdict_seq": 1554820, "meaning_en": "strength,power"}'::jsonb, 'jmdict'),
    ('ja', 'ちっとも', '一點也不（後接否定）', '{"kana": "ちっとも", "jlpt": "N4", "jmdict_seq": 1007560, "meaning_en": "not at all (used with a negative verb)"}'::jsonb, 'jmdict'),
    ('ja', 'ちゃん', '小（暱稱）', '{"kana": "ちゃん", "jlpt": "N4", "jmdict_seq": 1007660, "meaning_en": "suffix for familiar female person"}'::jsonb, 'jmdict'),
    ('ja', '注意', '注意', '{"kana": "ちゅうい", "jlpt": "N4", "jmdict_seq": 1426530, "meaning_en": "caution"}'::jsonb, 'jmdict'),
    ('ja', '中学校', '國中', '{"kana": "ちゅうがっこう", "jlpt": "N4", "jmdict_seq": 1423650, "meaning_en": "junior high school,middle school"}'::jsonb, 'jmdict'),
    ('ja', '注射', '打針', '{"kana": "ちゅうしゃ", "jlpt": "N4", "jmdict_seq": 1426590, "meaning_en": "injection"}'::jsonb, 'jmdict'),
    ('ja', '駐車場', '停車場', '{"kana": "ちゅうしゃじょう", "jlpt": "N4", "jmdict_seq": 1426920, "meaning_en": "parking lot"}'::jsonb, 'jmdict'),
    ('ja', '地理', '地理', '{"kana": "ちり", "jlpt": "N4", "jmdict_seq": 1421540, "meaning_en": "geography"}'::jsonb, 'jmdict'),
    ('ja', '捕まえる', '抓住', '{"kana": "つかまえる", "jlpt": "N4", "jmdict_seq": 1597780, "meaning_en": "to seize"}'::jsonb, 'jmdict'),
    ('ja', '月', '月亮', '{"kana": "つき", "jlpt": "N4", "jmdict_seq": 1255430, "meaning_en": "moon"}'::jsonb, 'jmdict'),
    ('ja', '付く', '附著', '{"kana": "つく", "jlpt": "N4", "jmdict_seq": 1495740, "meaning_en": "to be attached"}'::jsonb, 'jmdict'),
    ('ja', '漬ける', '泡/醃', '{"kana": "つける", "jlpt": "N4", "jmdict_seq": 1433680, "meaning_en": "to soak,to pickle"}'::jsonb, 'jmdict'),
    ('ja', '都合', '方便/狀況', '{"kana": "つごう", "jlpt": "N4", "jmdict_seq": 1444980, "meaning_en": "circumstances,convenience"}'::jsonb, 'jmdict'),
    ('ja', '伝える', '轉達', '{"kana": "つたえる", "jlpt": "N4", "jmdict_seq": 1441870, "meaning_en": "to report"}'::jsonb, 'jmdict'),
    ('ja', '続く', '持續（自動）', '{"kana": "つづく", "jlpt": "N4", "jmdict_seq": 1405790, "meaning_en": "to be continued"}'::jsonb, 'jmdict'),
    ('ja', '続ける', '繼續（他動）', '{"kana": "つづける", "jlpt": "N4", "jmdict_seq": 1405800, "meaning_en": "to continue"}'::jsonb, 'jmdict'),
    ('ja', '包む', '包裝', '{"kana": "つつむ", "jlpt": "N4", "jmdict_seq": 1584060, "meaning_en": "to wrap"}'::jsonb, 'jmdict'),
    ('ja', '妻', '妻子（謙稱）', '{"kana": "つま", "jlpt": "N4", "jmdict_seq": 1294330, "meaning_en": "(humble) wife"}'::jsonb, 'jmdict'),
    ('ja', '積もり', '打算', '{"kana": "つもり", "jlpt": "N4", "jmdict_seq": 1382980, "meaning_en": "intention"}'::jsonb, 'jmdict'),
    ('ja', '釣る', '釣', '{"kana": "つる", "jlpt": "N4", "jmdict_seq": 1434120, "meaning_en": "to fish"}'::jsonb, 'jmdict'),
    ('ja', '連れる', '帶（人）', '{"kana": "つれる", "jlpt": "N4", "jmdict_seq": 1559290, "meaning_en": "to lead"}'::jsonb, 'jmdict'),
    ('ja', '丁寧', '有禮貌', '{"kana": "ていねい", "jlpt": "N4", "jmdict_seq": 1427360, "meaning_en": "polite"}'::jsonb, 'jmdict'),
    ('ja', 'テキスト', '課本', '{"kana": "テキスト", "jlpt": "N4", "jmdict_seq": 1079290, "meaning_en": "text,text book"}'::jsonb, 'jmdict'),
    ('ja', '適当', '合適', '{"kana": "てきとう", "jlpt": "N4", "jmdict_seq": 1437450, "meaning_en": "suitability"}'::jsonb, 'jmdict'),
    ('ja', 'できるだけ', '盡量', '{"kana": "できるだけ", "jlpt": "N4", "jmdict_seq": 1340460, "meaning_en": "as much as possible"}'::jsonb, 'jmdict'),
    ('ja', '手伝う', '幫忙', '{"kana": "てつだう", "jlpt": "N4", "jmdict_seq": 1328190, "meaning_en": "to assist"}'::jsonb, 'jmdict'),
    ('ja', 'テニス', '網球', '{"kana": "テニス", "jlpt": "N4", "jmdict_seq": 1080000, "meaning_en": "tennis"}'::jsonb, 'jmdict'),
    ('ja', '手袋', '手套', '{"kana": "てぶくろ", "jlpt": "N4", "jmdict_seq": 1328090, "meaning_en": "glove"}'::jsonb, 'jmdict'),
    ('ja', '寺', '寺廟', '{"kana": "てら", "jlpt": "N4", "jmdict_seq": 1315240, "meaning_en": "temple"}'::jsonb, 'jmdict'),
    ('ja', '点', '點/分數', '{"kana": "てん", "jlpt": "N4", "jmdict_seq": 1441390, "meaning_en": "point,dot"}'::jsonb, 'jmdict'),
    ('ja', '店員', '店員', '{"kana": "てんいん", "jlpt": "N4", "jmdict_seq": 1440670, "meaning_en": "shop assistant"}'::jsonb, 'jmdict'),
    ('ja', '天気予報', '天氣預報', '{"kana": "てんきよほう", "jlpt": "N4", "jmdict_seq": 1438770, "meaning_en": "weather forecast"}'::jsonb, 'jmdict'),
    ('ja', '電灯', '電燈', '{"kana": "でんとう", "jlpt": "N4", "jmdict_seq": 1443660, "meaning_en": "electric light"}'::jsonb, 'jmdict'),
    ('ja', '電報', '電報', '{"kana": "でんぽう", "jlpt": "N4", "jmdict_seq": 1443760, "meaning_en": "telegram"}'::jsonb, 'jmdict'),
    ('ja', '展覧会', '展覽', '{"kana": "てんらんかい", "jlpt": "N4", "jmdict_seq": 1440660, "meaning_en": "exhibition"}'::jsonb, 'jmdict'),
    ('ja', '都', '都（首都）', '{"kana": "と", "jlpt": "N4", "jmdict_seq": 1621470, "meaning_en": "metropolitan"}'::jsonb, 'jmdict'),
    ('ja', '道具', '工具', '{"kana": "どうぐ", "jlpt": "N4", "jmdict_seq": 1454180, "meaning_en": "tool,means"}'::jsonb, 'jmdict'),
    ('ja', '到頭', '終於', '{"kana": "とうとう", "jlpt": "N4", "jmdict_seq": 1449890, "meaning_en": "finally, after all"}'::jsonb, 'jmdict'),
    ('ja', '動物園', '動物園', '{"kana": "どうぶつえん", "jlpt": "N4", "jmdict_seq": 1451490, "meaning_en": "zoo"}'::jsonb, 'jmdict'),
    ('ja', '遠く', '遠處', '{"kana": "とおく", "jlpt": "N4", "jmdict_seq": 1177820, "meaning_en": "distant"}'::jsonb, 'jmdict'),
    ('ja', '通る', '通過', '{"kana": "とおる", "jlpt": "N4", "jmdict_seq": 1433030, "meaning_en": "to go through"}'::jsonb, 'jmdict'),
    ('ja', '特に', '特別', '{"kana": "とくに", "jlpt": "N4", "jmdict_seq": 1454670, "meaning_en": "particularly,especially"}'::jsonb, 'jmdict'),
    ('ja', '特別', '特別的', '{"kana": "とくべつ", "jlpt": "N4", "jmdict_seq": 1455280, "meaning_en": "special"}'::jsonb, 'jmdict'),
    ('ja', 'とこや', '理髮店', '{"kana": "とこや", "jlpt": "N4", "jmdict_seq": 1349410, "meaning_en": "barber"}'::jsonb, 'jmdict'),
    ('ja', '途中', '途中', '{"kana": "とちゅう", "jlpt": "N4", "jmdict_seq": 1582200, "meaning_en": "on the way"}'::jsonb, 'jmdict'),
    ('ja', '特急', '特快車', '{"kana": "とっきゅう", "jlpt": "N4", "jmdict_seq": 1454750, "meaning_en": "limited express train (faster than an express train)"}'::jsonb, 'jmdict'),
    ('ja', '届ける', '送到', '{"kana": "とどける", "jlpt": "N4", "jmdict_seq": 1457210, "meaning_en": "to reach"}'::jsonb, 'jmdict'),
    ('ja', '泊まる', '住宿', '{"kana": "とまる", "jlpt": "N4", "jmdict_seq": 1474850, "meaning_en": "to lodge at"}'::jsonb, 'jmdict'),
    ('ja', '止める', '停下（他動）', '{"kana": "とめる", "jlpt": "N4", "jmdict_seq": 1310670, "meaning_en": "to stop something"}'::jsonb, 'jmdict'),
    ('ja', '取り替える', '更換', '{"kana": "とりかえる", "jlpt": "N4", "jmdict_seq": 1326830, "meaning_en": "to exchange"}'::jsonb, 'jmdict'),
    ('ja', '泥棒', '小偷', '{"kana": "どろぼう", "jlpt": "N4", "jmdict_seq": 1599340, "meaning_en": "thief"}'::jsonb, 'jmdict'),
    ('ja', 'どんどん', '越來越', '{"kana": "どんどん", "jlpt": "N4", "jmdict_seq": 1009320, "meaning_en": "more and more"}'::jsonb, 'jmdict'),
    ('ja', '直す', '修理', '{"kana": "なおす", "jlpt": "N4", "jmdict_seq": 1599390, "meaning_en": "to fix,to repair"}'::jsonb, 'jmdict'),
    ('ja', '直る', '修好（自動）', '{"kana": "なおる", "jlpt": "N4", "jmdict_seq": 2846390, "meaning_en": "to be fixed,to be repaired"}'::jsonb, 'jmdict'),
    ('ja', '治る', '痊癒', '{"kana": "なおる", "jlpt": "N4", "jmdict_seq": 1599400, "meaning_en": "to be cured,to heal"}'::jsonb, 'jmdict'),
    ('ja', '中々', '相當/遲遲（後接否定）', '{"kana": "なかなか", "jlpt": "N4", "jmdict_seq": 1599420, "meaning_en": "considerably"}'::jsonb, 'jmdict'),
    ('ja', '泣く', '哭', '{"kana": "なく", "jlpt": "N4", "jmdict_seq": 1229840, "meaning_en": "to weep"}'::jsonb, 'jmdict'),
    ('ja', '無くなる', '不見', '{"kana": "なくなる", "jlpt": "N4", "jmdict_seq": 1529550, "meaning_en": "to disappear,to get lost"}'::jsonb, 'jmdict'),
    ('ja', '亡くなる', '過世', '{"kana": "なくなる", "jlpt": "N4", "jmdict_seq": 1518540, "meaning_en": "to die"}'::jsonb, 'jmdict'),
    ('ja', '投げる', '丟', '{"kana": "なげる", "jlpt": "N4", "jmdict_seq": 1447000, "meaning_en": "to throw or cast away"}'::jsonb, 'jmdict'),
    ('ja', 'なさる', '做（敬語）', '{"kana": "なさる", "jlpt": "N4", "jmdict_seq": 1157090, "meaning_en": "(respectful) to do"}'::jsonb, 'jmdict'),
    ('ja', '鳴る', '響', '{"kana": "なる", "jlpt": "N4", "jmdict_seq": 1532910, "meaning_en": "to sound"}'::jsonb, 'jmdict'),
    ('ja', 'なるべく', '盡量', '{"kana": "なるべく", "jlpt": "N4", "jmdict_seq": 1375620, "meaning_en": "as much as possible"}'::jsonb, 'jmdict'),
    ('ja', 'なるほど', '原來如此', '{"kana": "なるほど", "jlpt": "N4", "jmdict_seq": 1375820, "meaning_en": "now I understand"}'::jsonb, 'jmdict'),
    ('ja', '慣れる', '習慣', '{"kana": "なれる", "jlpt": "N4", "jmdict_seq": 1212670, "meaning_en": "to grow accustomed to"}'::jsonb, 'jmdict'),
    ('ja', 'におい', '味道（氣味）', '{"kana": "におい", "jlpt": "N4", "jmdict_seq": 1599760, "meaning_en": "a smell"}'::jsonb, 'jmdict'),
    ('ja', '苦い', '苦', '{"kana": "にがい", "jlpt": "N4", "jmdict_seq": 1244310, "meaning_en": "bitter"}'::jsonb, 'jmdict'),
    ('ja', '二階建て', '兩層樓', '{"kana": "にかいだて", "jlpt": "N4", "jmdict_seq": 1599800, "meaning_en": "two storied"}'::jsonb, 'jmdict'),
    ('ja', '逃げる', '逃', '{"kana": "にげる", "jlpt": "N4", "jmdict_seq": 1450330, "meaning_en": "to escape"}'::jsonb, 'jmdict'),
    ('ja', '日記', '日記', '{"kana": "にっき", "jlpt": "N4", "jmdict_seq": 1463930, "meaning_en": "journal"}'::jsonb, 'jmdict'),
    ('ja', '入院', '住院', '{"kana": "にゅういん", "jlpt": "N4", "jmdict_seq": 1465720, "meaning_en": "to hospitalise"}'::jsonb, 'jmdict'),
    ('ja', '入学', '入學', '{"kana": "にゅうがく", "jlpt": "N4", "jmdict_seq": 1465850, "meaning_en": "to enter school or university"}'::jsonb, 'jmdict'),
    ('ja', '似る', '相似', '{"kana": "にる", "jlpt": "N4", "jmdict_seq": 1314600, "meaning_en": "to be similar"}'::jsonb, 'jmdict'),
    ('ja', '人形', '人偶', '{"kana": "にんぎょう", "jlpt": "N4", "jmdict_seq": 1367120, "meaning_en": "doll, figure"}'::jsonb, 'jmdict'),
    ('ja', '盗む', '偷', '{"kana": "ぬすむ", "jlpt": "N4", "jmdict_seq": 1448440, "meaning_en": "to steal"}'::jsonb, 'jmdict'),
    ('ja', '塗る', '塗', '{"kana": "ぬる", "jlpt": "N4", "jmdict_seq": 1444270, "meaning_en": "to paint,to plaster"}'::jsonb, 'jmdict'),
    ('ja', 'ぬれる', '弄濕', '{"kana": "ぬれる", "jlpt": "N4", "jmdict_seq": 1467620, "meaning_en": "to get wet"}'::jsonb, 'jmdict'),
    ('ja', 'ねだん', '價格', '{"kana": "ねだん", "jlpt": "N4", "jmdict_seq": 1600160, "meaning_en": "price"}'::jsonb, 'jmdict'),
    ('ja', '熱', '發燒', '{"kana": "ねつ", "jlpt": "N4", "jmdict_seq": 1467710, "meaning_en": "fever"}'::jsonb, 'jmdict'),
    ('ja', 'ねっしん', '熱心', '{"kana": "ねっしん", "jlpt": "N4", "jmdict_seq": 1467910, "meaning_en": "enthusiasm"}'::jsonb, 'jmdict'),
    ('ja', '寝坊', '睡過頭', '{"kana": "ねぼう", "jlpt": "N4", "jmdict_seq": 1360320, "meaning_en": "sleeping in late"}'::jsonb, 'jmdict'),
    ('ja', '眠い', '想睡', '{"kana": "ねむい", "jlpt": "N4", "jmdict_seq": 1529330, "meaning_en": "sleepy"}'::jsonb, 'jmdict'),
    ('ja', '眠る', '睡覺', '{"kana": "ねむる", "jlpt": "N4", "jmdict_seq": 1529390, "meaning_en": "to sleep"}'::jsonb, 'jmdict'),
    ('ja', '残る', '留下', '{"kana": "のこる", "jlpt": "N4", "jmdict_seq": 1304510, "meaning_en": "to remain"}'::jsonb, 'jmdict'),
    ('ja', '喉', '喉嚨', '{"kana": "のど", "jlpt": "N4", "jmdict_seq": 1600280, "meaning_en": "throat"}'::jsonb, 'jmdict'),
    ('ja', '乗り換える', '換車', '{"kana": "のりかえる", "jlpt": "N4", "jmdict_seq": 1600470, "meaning_en": "to change between buses or trains"}'::jsonb, 'jmdict'),
    ('ja', '乗り物', '交通工具', '{"kana": "のりもの", "jlpt": "N4", "jmdict_seq": 1600530, "meaning_en": "vehicle"}'::jsonb, 'jmdict'),
    ('ja', '葉', '葉子', '{"kana": "は", "jlpt": "N4", "jmdict_seq": 1546550, "meaning_en": "leaf"}'::jsonb, 'jmdict'),
    ('ja', '場合', '情況', '{"kana": "ばあい", "jlpt": "N4", "jmdict_seq": 1355810, "meaning_en": "situation"}'::jsonb, 'jmdict'),
    ('ja', 'パート', '兼職', '{"kana": "パート", "jlpt": "N4", "jmdict_seq": 1100810, "meaning_en": "part time"}'::jsonb, 'jmdict'),
    ('ja', '倍', '倍', '{"kana": "ばい", "jlpt": "N4", "jmdict_seq": 1473230, "meaning_en": "double"}'::jsonb, 'jmdict'),
    ('ja', '拝見', '看（謙讓）', '{"kana": "はいけん", "jlpt": "N4", "jmdict_seq": 1472270, "meaning_en": "(humble) to look at"}'::jsonb, 'jmdict'),
    ('ja', '歯医者', '牙醫', '{"kana": "はいしゃ", "jlpt": "N4", "jmdict_seq": 1313080, "meaning_en": "dentist"}'::jsonb, 'jmdict'),
    ('ja', '運ぶ', '搬運', '{"kana": "はこぶ", "jlpt": "N4", "jmdict_seq": 1172660, "meaning_en": "to transport"}'::jsonb, 'jmdict'),
    ('ja', '始める', '開始（他動）', '{"kana": "はじめる", "jlpt": "N4", "jmdict_seq": 1307550, "meaning_en": "to begin"}'::jsonb, 'jmdict'),
    ('ja', '場所', '地點', '{"kana": "ばしょ", "jlpt": "N4", "jmdict_seq": 1355850, "meaning_en": "location"}'::jsonb, 'jmdict'),
    ('ja', '筈', '應該', '{"kana": "はず", "jlpt": "N4", "jmdict_seq": 1476430, "meaning_en": "it should be so"}'::jsonb, 'jmdict'),
    ('ja', '恥ずかしい', '害羞', '{"kana": "はずかしい", "jlpt": "N4", "jmdict_seq": 1421630, "meaning_en": "embarrassed"}'::jsonb, 'jmdict'),
    ('ja', 'パソコン', '電腦', '{"kana": "パソコン", "jlpt": "N4", "jmdict_seq": 1101570, "meaning_en": "personal computer"}'::jsonb, 'jmdict'),
    ('ja', '発音', '發音', '{"kana": "はつおん", "jlpt": "N4", "jmdict_seq": 1477170, "meaning_en": "pronunciation"}'::jsonb, 'jmdict'),
    ('ja', 'はっきり', '清楚', '{"kana": "はっきり", "jlpt": "N4", "jmdict_seq": 1010150, "meaning_en": "clearly"}'::jsonb, 'jmdict'),
    ('ja', '花見', '賞花', '{"kana": "はなみ", "jlpt": "N4", "jmdict_seq": 1194660, "meaning_en": "cherry-blossom viewing"}'::jsonb, 'jmdict'),
    ('ja', '林', '樹林', '{"kana": "はやし", "jlpt": "N4", "jmdict_seq": 1555440, "meaning_en": "woods,forester"}'::jsonb, 'jmdict'),
    ('ja', '払う', '付（錢）', '{"kana": "はらう", "jlpt": "N4", "jmdict_seq": 1501620, "meaning_en": "to pay"}'::jsonb, 'jmdict'),
    ('ja', '番組', '節目', '{"kana": "ばんぐみ", "jlpt": "N4", "jmdict_seq": 1482340, "meaning_en": "television or radio program"}'::jsonb, 'jmdict'),
    ('ja', '反対', '反對', '{"kana": "はんたい", "jlpt": "N4", "jmdict_seq": 1480670, "meaning_en": "opposition"}'::jsonb, 'jmdict'),
    ('ja', 'ハンドバッグ', '手提包', '{"kana": "ハンドバッグ", "jlpt": "N4", "jmdict_seq": 1096770, "meaning_en": "handbag　"}'::jsonb, 'jmdict'),
    ('ja', '日', '日子/太陽', '{"kana": "ひ", "jlpt": "N4", "jmdict_seq": 1463770, "meaning_en": "day, sun"}'::jsonb, 'jmdict'),
    ('ja', '火', '火', '{"kana": "ひ", "jlpt": "N4", "jmdict_seq": 1193610, "meaning_en": "fire"}'::jsonb, 'jmdict'),
    ('ja', 'ピアノ', '鋼琴', '{"kana": "ピアノ", "jlpt": "N4", "jmdict_seq": 1106400, "meaning_en": "piano"}'::jsonb, 'jmdict'),
    ('ja', '冷える', '變冷', '{"kana": "ひえる", "jlpt": "N4", "jmdict_seq": 1556630, "meaning_en": "to grow cold"}'::jsonb, 'jmdict'),
    ('ja', '光', '光', '{"kana": "ひかり", "jlpt": "N4", "jmdict_seq": 1272780, "meaning_en": "light"}'::jsonb, 'jmdict'),
    ('ja', '光る', '發光', '{"kana": "ひかる", "jlpt": "N4", "jmdict_seq": 1272820, "meaning_en": "to shine,to glitter"}'::jsonb, 'jmdict'),
    ('ja', '引き出し', '抽屜', '{"kana": "ひきだし", "jlpt": "N4", "jmdict_seq": 1601650, "meaning_en": "drawer,drawing out"}'::jsonb, 'jmdict'),
    ('ja', '引き出す', '提領', '{"kana": "ひきだす", "jlpt": "N4", "jmdict_seq": 1601660, "meaning_en": "to withdraw"}'::jsonb, 'jmdict'),
    ('ja', '髭', '鬍子', '{"kana": "ひげ", "jlpt": "N4", "jmdict_seq": 1601810, "meaning_en": "beard"}'::jsonb, 'jmdict'),
    ('ja', '飛行場', '機場', '{"kana": "ひこうじょう", "jlpt": "N4", "jmdict_seq": 1485520, "meaning_en": "airport"}'::jsonb, 'jmdict'),
    ('ja', '久しぶり', '好久不見', '{"kana": "ひさしぶり", "jlpt": "N4", "jmdict_seq": 1227370, "meaning_en": "after a long time"}'::jsonb, 'jmdict'),
    ('ja', '美術館', '美術館', '{"kana": "びじゅつかん", "jlpt": "N4", "jmdict_seq": 1486460, "meaning_en": "art gallery"}'::jsonb, 'jmdict'),
    ('ja', '非常に', '非常', '{"kana": "ひじょうに", "jlpt": "N4", "jmdict_seq": 1484930, "meaning_en": "extremely"}'::jsonb, 'jmdict'),
    ('ja', 'びっくり', '嚇一跳', '{"kana": "びっくり", "jlpt": "N4", "jmdict_seq": 1226360, "meaning_en": "to be surprised"}'::jsonb, 'jmdict'),
    ('ja', '引っ越す', '搬家', '{"kana": "ひっこす", "jlpt": "N4", "jmdict_seq": 1169340, "meaning_en": "to move house"}'::jsonb, 'jmdict'),
    ('ja', '必要', '必要', '{"kana": "ひつよう", "jlpt": "N4", "jmdict_seq": 1487660, "meaning_en": "necessary"}'::jsonb, 'jmdict'),
    ('ja', 'ひどい', '過分', '{"kana": "ひどい", "jlpt": "N4", "jmdict_seq": 1602060, "meaning_en": "awful"}'::jsonb, 'jmdict'),
    ('ja', '開く', '舉辦/打開', '{"kana": "ひらく", "jlpt": "N4", "jmdict_seq": 1202440, "meaning_en": "to open an event"}'::jsonb, 'jmdict'),
    ('ja', 'ビル', '大樓', '{"kana": "ビル", "jlpt": "N4", "jmdict_seq": 1106010, "meaning_en": "building or bill"}'::jsonb, 'jmdict'),
    ('ja', '昼間', '白天', '{"kana": "ひるま", "jlpt": "N4", "jmdict_seq": 1581710, "meaning_en": "daytime,during the day"}'::jsonb, 'jmdict'),
    ('ja', '昼休み', '午休', '{"kana": "ひるやすみ", "jlpt": "N4", "jmdict_seq": 1426290, "meaning_en": "noon break"}'::jsonb, 'jmdict'),
    ('ja', '拾う', '撿', '{"kana": "ひろう", "jlpt": "N4", "jmdict_seq": 1332570, "meaning_en": "to pick up,to gather"}'::jsonb, 'jmdict'),
    ('ja', 'ファックス', '傳真', '{"kana": "ファックス", "jlpt": "N4", "jmdict_seq": 1108180, "meaning_en": "fax"}'::jsonb, 'jmdict'),
    ('ja', '増える', '增加', '{"kana": "ふえる", "jlpt": "N4", "jmdict_seq": 1602440, "meaning_en": "to increase"}'::jsonb, 'jmdict'),
    ('ja', '深い', '深', '{"kana": "ふかい", "jlpt": "N4", "jmdict_seq": 1362640, "meaning_en": "deep"}'::jsonb, 'jmdict'),
    ('ja', '複雑', '複雜', '{"kana": "ふくざつ", "jlpt": "N4", "jmdict_seq": 1501350, "meaning_en": "complexity,complication"}'::jsonb, 'jmdict'),
    ('ja', '復習', '複習', '{"kana": "ふくしゅう", "jlpt": "N4", "jmdict_seq": 1500800, "meaning_en": "revision"}'::jsonb, 'jmdict'),
    ('ja', '部長', '部長', '{"kana": "ぶちょう", "jlpt": "N4", "jmdict_seq": 1499460, "meaning_en": "head of a section"}'::jsonb, 'jmdict'),
    ('ja', '普通', '普通', '{"kana": "ふつう", "jlpt": "N4", "jmdict_seq": 1497190, "meaning_en": "usually, or a train that stops at every station"}'::jsonb, 'jmdict'),
    ('ja', '葡萄', '葡萄', '{"kana": "ぶどう", "jlpt": "N4", "jmdict_seq": 1499230, "meaning_en": "grapes"}'::jsonb, 'jmdict'),
    ('ja', '太る', '變胖', '{"kana": "ふとる", "jlpt": "N4", "jmdict_seq": 1408220, "meaning_en": "to become fat"}'::jsonb, 'jmdict'),
    ('ja', '布団', '棉被', '{"kana": "ふとん", "jlpt": "N4", "jmdict_seq": 1496890, "meaning_en": "Japanese bedding, futon"}'::jsonb, 'jmdict'),
    ('ja', '舟', '船', '{"kana": "ふね", "jlpt": "N4", "jmdict_seq": 1602800, "meaning_en": "ship"}'::jsonb, 'jmdict'),
    ('ja', '不便', '不方便', '{"kana": "ふべん", "jlpt": "N4", "jmdict_seq": 1494860, "meaning_en": "inconvenience"}'::jsonb, 'jmdict'),
    ('ja', '踏む', '踩', '{"kana": "ふむ", "jlpt": "N4", "jmdict_seq": 1450270, "meaning_en": "to step on"}'::jsonb, 'jmdict'),
    ('ja', '降り出す', '開始下（雨）', '{"kana": "ふりだす", "jlpt": "N4", "jmdict_seq": 1282770, "meaning_en": "to start to rain"}'::jsonb, 'jmdict'),
    ('ja', 'プレゼント', '禮物', '{"kana": "プレゼント", "jlpt": "N4", "jmdict_seq": 1116840, "meaning_en": "present"}'::jsonb, 'jmdict'),
    ('ja', '文化', '文化', '{"kana": "ぶんか", "jlpt": "N4", "jmdict_seq": 1505120, "meaning_en": "culture"}'::jsonb, 'jmdict'),
    ('ja', '文学', '文學', '{"kana": "ぶんがく", "jlpt": "N4", "jmdict_seq": 1505190, "meaning_en": "literature"}'::jsonb, 'jmdict'),
    ('ja', '文法', '文法', '{"kana": "ぶんぽう", "jlpt": "N4", "jmdict_seq": 1505600, "meaning_en": "grammar"}'::jsonb, 'jmdict'),
    ('ja', '別', '不同', '{"kana": "べつ", "jlpt": "N4", "jmdict_seq": 1509430, "meaning_en": "different"}'::jsonb, 'jmdict'),
    ('ja', 'ベル', '鈴', '{"kana": "ベル", "jlpt": "N4", "jmdict_seq": 1120010, "meaning_en": "bell"}'::jsonb, 'jmdict'),
    ('ja', '変', '奇怪', '{"kana": "へん", "jlpt": "N4", "jmdict_seq": 1510640, "meaning_en": "strange"}'::jsonb, 'jmdict'),
    ('ja', '返事', '回覆', '{"kana": "へんじ", "jlpt": "N4", "jmdict_seq": 1512220, "meaning_en": "reply"}'::jsonb, 'jmdict'),
    ('ja', '貿易', '貿易', '{"kana": "ぼうえき", "jlpt": "N4", "jmdict_seq": 1520120, "meaning_en": "trade"}'::jsonb, 'jmdict'),
    ('ja', '放送', '播放', '{"kana": "ほうそう", "jlpt": "N4", "jmdict_seq": 1516750, "meaning_en": "to broadcast"}'::jsonb, 'jmdict'),
    ('ja', '法律', '法律', '{"kana": "ほうりつ", "jlpt": "N4", "jmdict_seq": 1517480, "meaning_en": "law"}'::jsonb, 'jmdict'),
    ('ja', '僕', '我（男性）', '{"kana": "ぼく", "jlpt": "N4", "jmdict_seq": 1521400, "meaning_en": "I (used by males)"}'::jsonb, 'jmdict'),
    ('ja', '星', '星星', '{"kana": "ほし", "jlpt": "N4", "jmdict_seq": 1376310, "meaning_en": "star"}'::jsonb, 'jmdict'),
    ('ja', '程', '程度', '{"kana": "ほど", "jlpt": "N4", "jmdict_seq": 1436510, "meaning_en": "extent"}'::jsonb, 'jmdict'),
    ('ja', 'ほとんど', '幾乎', '{"kana": "ほとんど", "jlpt": "N4", "jmdict_seq": 1522050, "meaning_en": "mostly"}'::jsonb, 'jmdict'),
    ('ja', 'ほめる', '稱讚', '{"kana": "ほめる", "jlpt": "N4", "jmdict_seq": 1603550, "meaning_en": "to praise"}'::jsonb, 'jmdict'),
    ('ja', '翻訳', '翻譯', '{"kana": "ほんやく", "jlpt": "N4", "jmdict_seq": 1523400, "meaning_en": "translation"}'::jsonb, 'jmdict'),
    ('ja', '参る', '去/來（謙讓）', '{"kana": "まいる", "jlpt": "N4", "jmdict_seq": 1302070, "meaning_en": "(humble) to go,to come"}'::jsonb, 'jmdict'),
    ('ja', '負ける', '輸', '{"kana": "まける", "jlpt": "N4", "jmdict_seq": 1497980, "meaning_en": "to lose"}'::jsonb, 'jmdict'),
    ('ja', 'まじめ', '認真', '{"kana": "まじめ", "jlpt": "N4", "jmdict_seq": 1364360, "meaning_en": "serious"}'::jsonb, 'jmdict'),
    ('ja', '先ず', '首先', '{"kana": "まず", "jlpt": "N4", "jmdict_seq": 1387240, "meaning_en": "first of all"}'::jsonb, 'jmdict'),
    ('ja', 'または', '或者', '{"kana": "または", "jlpt": "N4", "jmdict_seq": 1524990, "meaning_en": "or,otherwise"}'::jsonb, 'jmdict'),
    ('ja', '間違える', '弄錯', '{"kana": "まちがえる", "jlpt": "N4", "jmdict_seq": 1215330, "meaning_en": "to make a mistake"}'::jsonb, 'jmdict'),
    ('ja', '間に合う', '來得及', '{"kana": "まにあう", "jlpt": "N4", "jmdict_seq": 1215260, "meaning_en": "to be in time for"}'::jsonb, 'jmdict'),
    ('ja', '周り', '周圍', '{"kana": "まわり", "jlpt": "N4", "jmdict_seq": 1604290, "meaning_en": "surroundings"}'::jsonb, 'jmdict'),
    ('ja', '回る', '繞', '{"kana": "まわる", "jlpt": "N4", "jmdict_seq": 1604300, "meaning_en": "to go around"}'::jsonb, 'jmdict'),
    ('ja', '漫画', '漫畫', '{"kana": "まんが", "jlpt": "N4", "jmdict_seq": 1526920, "meaning_en": "comic"}'::jsonb, 'jmdict'),
    ('ja', '真ん中', '正中間', '{"kana": "まんなか", "jlpt": "N4", "jmdict_seq": 1604350, "meaning_en": "middle"}'::jsonb, 'jmdict'),
    ('ja', '見える', '看得到', '{"kana": "みえる", "jlpt": "N4", "jmdict_seq": 1259140, "meaning_en": "to be in sight"}'::jsonb, 'jmdict'),
    ('ja', '湖', '湖', '{"kana": "みずうみ", "jlpt": "N4", "jmdict_seq": 1267280, "meaning_en": "lake"}'::jsonb, 'jmdict'),
    ('ja', '味噌', '味噌', '{"kana": "みそ", "jlpt": "N4", "jmdict_seq": 1527040, "meaning_en": "bean paste"}'::jsonb, 'jmdict'),
    ('ja', '見つかる', '被找到（自動）', '{"kana": "みつかる", "jlpt": "N4", "jmdict_seq": 1604550, "meaning_en": "to be discovered"}'::jsonb, 'jmdict'),
    ('ja', '見つける', '找到（他動）', '{"kana": "みつける", "jlpt": "N4", "jmdict_seq": 1604570, "meaning_en": "to discover"}'::jsonb, 'jmdict'),
    ('ja', '皆', '大家', '{"kana": "みな", "jlpt": "N4", "jmdict_seq": 1202150, "meaning_en": "everybody"}'::jsonb, 'jmdict'),
    ('ja', '港', '港口', '{"kana": "みなと", "jlpt": "N4", "jmdict_seq": 1279990, "meaning_en": "harbour"}'::jsonb, 'jmdict'),
    ('ja', '向かう', '前往', '{"kana": "むかう", "jlpt": "N4", "jmdict_seq": 1604800, "meaning_en": "to face"}'::jsonb, 'jmdict'),
    ('ja', '迎える', '迎接', '{"kana": "むかえる", "jlpt": "N4", "jmdict_seq": 1253190, "meaning_en": "to go out to meet"}'::jsonb, 'jmdict'),
    ('ja', '昔', '從前', '{"kana": "むかし", "jlpt": "N4", "jmdict_seq": 1382370, "meaning_en": "olden days, former"}'::jsonb, 'jmdict'),
    ('ja', '虫', '蟲', '{"kana": "むし", "jlpt": "N4", "jmdict_seq": 1426680, "meaning_en": "insect"}'::jsonb, 'jmdict'),
    ('ja', '息子', '兒子（謙稱）', '{"kana": "むすこ", "jlpt": "N4", "jmdict_seq": 1404390, "meaning_en": "(humble) son"}'::jsonb, 'jmdict'),
    ('ja', '娘', '女兒（謙稱）', '{"kana": "むすめ", "jlpt": "N4", "jmdict_seq": 1531190, "meaning_en": "(humble) daughter"}'::jsonb, 'jmdict'),
    ('ja', '無理', '不可能', '{"kana": "むり", "jlpt": "N4", "jmdict_seq": 1530970, "meaning_en": "impossible"}'::jsonb, 'jmdict'),
    ('ja', '召し上がる', '吃（敬語）', '{"kana": "めしあがる", "jlpt": "N4", "jmdict_seq": 1346370, "meaning_en": "(polite) to eat"}'::jsonb, 'jmdict'),
    ('ja', '珍しい', '稀奇', '{"kana": "めずらしい", "jlpt": "N4", "jmdict_seq": 1431850, "meaning_en": "rare"}'::jsonb, 'jmdict'),
    ('ja', '申し上げる', '說（謙讓）', '{"kana": "もうしあげる", "jlpt": "N4", "jmdict_seq": 1362950, "meaning_en": "(humble) to say,to tell"}'::jsonb, 'jmdict'),
    ('ja', '申す', '叫做（謙讓）', '{"kana": "もうす", "jlpt": "N4", "jmdict_seq": 1363090, "meaning_en": "(humble) to be called,to say"}'::jsonb, 'jmdict'),
    ('ja', 'もうすぐ', '快要', '{"kana": "もうすぐ", "jlpt": "N4", "jmdict_seq": 2015610, "meaning_en": "soon"}'::jsonb, 'jmdict'),
    ('ja', 'もし', '如果', '{"kana": "もし", "jlpt": "N4", "jmdict_seq": 2607730, "meaning_en": "if"}'::jsonb, 'jmdict'),
    ('ja', 'もちろん', '當然', '{"kana": "もちろん", "jlpt": "N4", "jmdict_seq": 1535780, "meaning_en": "of course"}'::jsonb, 'jmdict'),
    ('ja', '最も', '最', '{"kana": "もっとも", "jlpt": "N4", "jmdict_seq": 1293700, "meaning_en": "extremely"}'::jsonb, 'jmdict'),
    ('ja', '戻る', '回去', '{"kana": "もどる", "jlpt": "N4", "jmdict_seq": 1535880, "meaning_en": "to turn back"}'::jsonb, 'jmdict'),
    ('ja', '木綿', '棉', '{"kana": "もめん", "jlpt": "N4", "jmdict_seq": 1534870, "meaning_en": "cotton"}'::jsonb, 'jmdict'),
    ('ja', 'もらう', '收到', '{"kana": "もらう", "jlpt": "N4", "jmdict_seq": 1535910, "meaning_en": "to receive"}'::jsonb, 'jmdict'),
    ('ja', '森', '森林', '{"kana": "もり", "jlpt": "N4", "jmdict_seq": 1362490, "meaning_en": "forest"}'::jsonb, 'jmdict'),
    ('ja', '焼く', '烤', '{"kana": "やく", "jlpt": "N4", "jmdict_seq": 1350600, "meaning_en": "to bake,to grill"}'::jsonb, 'jmdict'),
    ('ja', '約束', '約定', '{"kana": "やくそく", "jlpt": "N4", "jmdict_seq": 1538130, "meaning_en": "promise"}'::jsonb, 'jmdict'),
    ('ja', '役に立つ', '有用', '{"kana": "やくにたつ", "jlpt": "N4", "jmdict_seq": 1537980, "meaning_en": "to be helpful"}'::jsonb, 'jmdict'),
    ('ja', '焼ける', '烤好/燒掉', '{"kana": "やける", "jlpt": "N4", "jmdict_seq": 1350610, "meaning_en": "to burn,to be roasted"}'::jsonb, 'jmdict'),
    ('ja', '優しい', '溫柔', '{"kana": "やさしい", "jlpt": "N4", "jmdict_seq": 1539040, "meaning_en": "kind"}'::jsonb, 'jmdict'),
    ('ja', '痩せる', '變瘦', '{"kana": "やせる", "jlpt": "N4", "jmdict_seq": 1605510, "meaning_en": "to become thin"}'::jsonb, 'jmdict'),
    ('ja', 'やっと', '終於', '{"kana": "やっと", "jlpt": "N4", "jmdict_seq": 1012800, "meaning_en": "at last"}'::jsonb, 'jmdict'),
    ('ja', 'やはり', '果然', '{"kana": "やはり", "jlpt": "N4", "jmdict_seq": 2772770, "meaning_en": "as I thought,absolutely"}'::jsonb, 'jmdict'),
    ('ja', 'やっぱり', '果然（口語）', '{"kana": "やっぱり", "jlpt": "N4", "jmdict_seq": 1012810, "meaning_en": "as I thought,absolutely"}'::jsonb, 'jmdict'),
    ('ja', '止む', '停（雨/動作）', '{"kana": "やむ", "jlpt": "N4", "jmdict_seq": 1310640, "meaning_en": "to stop"}'::jsonb, 'jmdict'),
    ('ja', '止める', '停止/辭掉', '{"kana": "やめる", "jlpt": "N4", "jmdict_seq": 1310680, "meaning_en": "to stop"}'::jsonb, 'jmdict'),
    ('ja', '柔らかい', '柔軟', '{"kana": "やわらかい", "jlpt": "N4", "jmdict_seq": 1605630, "meaning_en": "soft"}'::jsonb, 'jmdict'),
    ('ja', '湯', '熱水', '{"kana": "ゆ", "jlpt": "N4", "jmdict_seq": 1448580, "meaning_en": "hot water"}'::jsonb, 'jmdict'),
    ('ja', '輸出', '出口', '{"kana": "ゆしゅつ", "jlpt": "N4", "jmdict_seq": 1538820, "meaning_en": "to export"}'::jsonb, 'jmdict'),
    ('ja', '輸入', '進口', '{"kana": "ゆにゅう", "jlpt": "N4", "jmdict_seq": 1538870, "meaning_en": "to import"}'::jsonb, 'jmdict'),
    ('ja', '指', '手指', '{"kana": "ゆび", "jlpt": "N4", "jmdict_seq": 1309650, "meaning_en": "finger"}'::jsonb, 'jmdict'),
    ('ja', '指輪', '戒指', '{"kana": "ゆびわ", "jlpt": "N4", "jmdict_seq": 1310050, "meaning_en": "finger ring"}'::jsonb, 'jmdict'),
    ('ja', '夢', '夢', '{"kana": "ゆめ", "jlpt": "N4", "jmdict_seq": 1529410, "meaning_en": "dream"}'::jsonb, 'jmdict'),
    ('ja', '揺れる', '搖晃', '{"kana": "ゆれる", "jlpt": "N4", "jmdict_seq": 1545710, "meaning_en": "to shake,to sway"}'::jsonb, 'jmdict'),
    ('ja', '用', '事情', '{"kana": "よう", "jlpt": "N4", "jmdict_seq": 1546200, "meaning_en": "use"}'::jsonb, 'jmdict'),
    ('ja', '用意', '準備', '{"kana": "ようい", "jlpt": "N4", "jmdict_seq": 1546220, "meaning_en": "preparation"}'::jsonb, 'jmdict'),
    ('ja', '用事', '要辦的事', '{"kana": "ようじ", "jlpt": "N4", "jmdict_seq": 1546300, "meaning_en": "things to do"}'::jsonb, 'jmdict'),
    ('ja', '汚れる', '弄髒', '{"kana": "よごれる", "jlpt": "N4", "jmdict_seq": 1179005, "meaning_en": "to get dirty"}'::jsonb, 'jmdict'),
    ('ja', '予習', '預習', '{"kana": "よしゅう", "jlpt": "N4", "jmdict_seq": 1543070, "meaning_en": "preparation for a lesson"}'::jsonb, 'jmdict'),
    ('ja', '予定', '預定', '{"kana": "よてい", "jlpt": "N4", "jmdict_seq": 1543240, "meaning_en": "arrangement"}'::jsonb, 'jmdict'),
    ('ja', '予約', '預約', '{"kana": "よやく", "jlpt": "N4", "jmdict_seq": 1543750, "meaning_en": "reservation"}'::jsonb, 'jmdict'),
    ('ja', '寄る', '順道過去', '{"kana": "よる", "jlpt": "N4", "jmdict_seq": 1219680, "meaning_en": "to visit"}'::jsonb, 'jmdict'),
    ('ja', '喜ぶ', '高興', '{"kana": "よろこぶ", "jlpt": "N4", "jmdict_seq": 1218760, "meaning_en": "to be delighted"}'::jsonb, 'jmdict'),
    ('ja', 'よろしい', '可以（敬語）', '{"kana": "よろしい", "jlpt": "N4", "jmdict_seq": 1224880, "meaning_en": "(respectful) OK,all right"}'::jsonb, 'jmdict'),
    ('ja', '理由', '理由', '{"kana": "りゆう", "jlpt": "N4", "jmdict_seq": 1550140, "meaning_en": "reason"}'::jsonb, 'jmdict'),
    ('ja', '利用', '利用', '{"kana": "りよう", "jlpt": "N4", "jmdict_seq": 1549660, "meaning_en": "utilization"}'::jsonb, 'jmdict'),
    ('ja', '両方', '兩邊', '{"kana": "りょうほう", "jlpt": "N4", "jmdict_seq": 1554010, "meaning_en": "both sides"}'::jsonb, 'jmdict'),
    ('ja', '旅館', '旅館', '{"kana": "りょかん", "jlpt": "N4", "jmdict_seq": 1553130, "meaning_en": "Japanese hotel"}'::jsonb, 'jmdict'),
    ('ja', '留守', '不在家', '{"kana": "るす", "jlpt": "N4", "jmdict_seq": 1552760, "meaning_en": "absence"}'::jsonb, 'jmdict'),
    ('ja', '冷房', '冷氣', '{"kana": "れいぼう", "jlpt": "N4", "jmdict_seq": 1557290, "meaning_en": "air conditioning"}'::jsonb, 'jmdict'),
    ('ja', '歴史', '歷史', '{"kana": "れきし", "jlpt": "N4", "jmdict_seq": 1558050, "meaning_en": "history"}'::jsonb, 'jmdict'),
    ('ja', 'レジ', '收銀台', '{"kana": "レジ", "jlpt": "N4", "jmdict_seq": 1145130, "meaning_en": "register"}'::jsonb, 'jmdict'),
    ('ja', 'レポート', '報告', '{"kana": "レポート", "jlpt": "N4", "jmdict_seq": 1145990, "meaning_en": "report"}'::jsonb, 'jmdict'),
    ('ja', 'リポート', '報告（リ）', '{"kana": "リポート", "jlpt": "N4", "jmdict_seq": 1145990, "meaning_en": "report"}'::jsonb, 'jmdict'),
    ('ja', '連絡', '聯絡', '{"kana": "れんらく", "jlpt": "N4", "jmdict_seq": 1559900, "meaning_en": "contact"}'::jsonb, 'jmdict'),
    ('ja', 'ワープロ', '文書處理機', '{"kana": "ワープロ", "jlpt": "N4", "jmdict_seq": 1148520, "meaning_en": "word processor"}'::jsonb, 'jmdict'),
    ('ja', '沸かす', '燒（水）', '{"kana": "わかす", "jlpt": "N4", "jmdict_seq": 1501660, "meaning_en": "to boil,to heat"}'::jsonb, 'jmdict'),
    ('ja', '別れる', '分開', '{"kana": "わかれる", "jlpt": "N4", "jmdict_seq": 1606590, "meaning_en": "to separate"}'::jsonb, 'jmdict'),
    ('ja', '沸く', '沸騰', '{"kana": "わく", "jlpt": "N4", "jmdict_seq": 1606680, "meaning_en": "to boil, to grow hot,to get excited"}'::jsonb, 'jmdict'),
    ('ja', '訳', '原因', '{"kana": "わけ", "jlpt": "N4", "jmdict_seq": 1538330, "meaning_en": "meaning,reason"}'::jsonb, 'jmdict'),
    ('ja', '忘れ物', '忘記的東西', '{"kana": "わすれもの", "jlpt": "N4", "jmdict_seq": 1519230, "meaning_en": "lost article"}'::jsonb, 'jmdict'),
    ('ja', '笑う', '笑', '{"kana": "わらう", "jlpt": "N4", "jmdict_seq": 1351360, "meaning_en": "to laugh,to smile"}'::jsonb, 'jmdict'),
    ('ja', '割合', '比例', '{"kana": "わりあい", "jlpt": "N4", "jmdict_seq": 1606810, "meaning_en": "rate,ratio,percentage"}'::jsonb, 'jmdict'),
    ('ja', '割れる', '破掉', '{"kana": "われる", "jlpt": "N4", "jmdict_seq": 1208020, "meaning_en": "to break"}'::jsonb, 'jmdict'),
    ('ja', '泳ぎ方', '游泳的方法', '{"kana": "およぎかた", "jlpt": "N4", "jmdict_seq": 2005990, "meaning_en": "way of swimming"}'::jsonb, 'jmdict')
  returning id, lemma
)
insert into shrine_words (shrine_id, word_id, position)
select
  (select id from shrines where slug = 'heian'),
  nw.id,
  row_number() over (order by nw.lemma)
from new_words nw;
